export interface VivaQuestion {
question: string;
answer: string;
}

export interface MCQ {
question: string;
options: string[];
answer: string;
}

export interface ChapterData {
chapterNumber: number;
chapterName: string;
vivaQuestions: VivaQuestion[];
mcqs: MCQ[];
}

export interface SubjectData {
subjectName: string;
totalChapters: number;
chapters: ChapterData[];
}

export const gtuCompilerDesignViva: SubjectData = {
subjectName: "COMPILER DESIGN",
totalChapters: 8,
chapters: [
{
chapterNumber: 1,
chapterName: "Overview of the Compiler and its Structure",
vivaQuestions: [
{ question: "What is a Compiler?", answer: "Sir, a compiler is a specialized software program that translates source code written in a high-level programming language into low-level machine code or target language that a computer's processor can understand and execute." },
{ question: "What is the difference between a Compiler and an Interpreter?", answer: "Sir, a compiler translates the entire source code into machine code in one go before execution, producing an executable file. An interpreter translates and executes the source code line-by-line simultaneously without producing a separate object code." },
{ question: "What is an Assembler?", answer: "Sir, an assembler is a language processor that translates assembly language code, which uses mnemonics, into relocatable machine code or object code consisting of binary instructions." },
{ question: "Can you name the phases of a Compiler?", answer: "Yes sir, a compiler typically operates in six phases: Lexical Analysis, Syntax Analysis, Semantic Analysis, Intermediate Code Generation, Code Optimization, and Target Code Generation." },
{ question: "What are the 'Cousins of the Compiler'?", answer: "Sir, the cousins of the compiler are the other tools that assist in the execution process, including preprocessors, assemblers, linkers, and loaders." },
{ question: "What is the role of a Preprocessor?", answer: "Sir, a preprocessor processes the source code before it is fed to the compiler. It handles macro expansions, file inclusions, and conditional compilation directives." },
{ question: "What is a Cross-Compiler?", answer: "Sir, a cross-compiler is a compiler that runs on one platform or architecture but generates executable code for a different platform or architecture." },
{ question: "What is a 'Pass' in a compiler?", answer: "Sir, a pass refers to one complete traversal of the source program or its intermediate representation by the compiler. Compilers can be single-pass or multi-pass." },
{ question: "What does the Linker do?", answer: "Sir, the linker takes one or more object files generated by the compiler or assembler and combines them into a single executable program, resolving external references and library functions." },
{ question: "What does the Loader do?", answer: "Sir, the loader is a part of the operating system that reads the executable file from the disk, loads it into the main memory (RAM), and prepares it for execution by the CPU." }
],
mcqs: [
{ question: "Which language processor translates the entire program before execution?", options: ["Interpreter", "Compiler", "Loader", "Linker"], answer: "Compiler" },
{ question: "Which tool resolves external memory addresses and combines object files?", options: ["Assembler", "Preprocessor", "Linker", "Loader"], answer: "Linker" },
{ question: "A compiler that runs on Machine A and produces code for Machine B is a:", options: ["Decompiler", "Interpreter", "Cross-compiler", "Assembler"], answer: "Cross-compiler" },
{ question: "Which of the following is NOT a phase of a compiler?", options: ["Lexical Analysis", "Syntax Analysis", "Process Management", "Code Optimization"], answer: "Process Management" },
{ question: "An interpreter reads the source code:", options: ["All at once", "Line by line", "Block by block", "After compilation"], answer: "Line by line" },
{ question: "Macro expansion and file inclusion are handled by the:", options: ["Compiler", "Linker", "Loader", "Preprocessor"], answer: "Preprocessor" },
{ question: "Which of the following translates Assembly language to Machine code?", options: ["Compiler", "Assembler", "Interpreter", "Macro processor"], answer: "Assembler" },
{ question: "What is the primary output of a Linker?", options: ["Source code", "Assembly code", "Executable code", "Relocatable object code"], answer: "Executable code" },
{ question: "A pass in a compiler refers to:", options: ["A compilation error", "One complete traversal of the source program", "Skipping a block of code", "Linking libraries"], answer: "One complete traversal of the source program" },
{ question: "Which of these is considered a 'cousin' of the compiler?", options: ["Operating System", "Database", "Loader", "Hardware"], answer: "Loader" }
]
},
{
chapterNumber: 2,
chapterName: "Lexical Analysis",
vivaQuestions: [
{ question: "What is the role of the Lexical Analyzer?", answer: "Sir, the lexical analyzer, or scanner, is the first phase of a compiler. It reads the raw source code characters, groups them into meaningful sequences called lexemes, and produces a sequence of tokens." },
{ question: "What is the difference between a Token and a Lexeme?", answer: "Sir, a lexeme is the actual sequence of characters in the source code, like 'count' or 'int'. A token is the abstract category or classification of that lexeme, such as 'IDENTIFIER' or 'KEYWORD'." },
{ question: "How does the Lexical Analyzer handle white spaces and comments?", answer: "Sir, the lexical analyzer strips out all unnecessary white spaces, tabs, newline characters, and comments from the source code, as they are not needed for the syntax analysis phase." },
{ question: "What is Input Buffering?", answer: "Sir, input buffering is a technique used by the lexical analyzer to read source code efficiently in large chunks rather than character by character. It often uses a two-buffer scheme with lookahead pointers." },
{ question: "Why do we use sentinels in input buffering?", answer: "Sir, a sentinel is a special character, typically EOF, placed at the end of a buffer half. It helps the lexical analyzer quickly check if it has reached the end of the buffer, reducing the overhead of boundary checks." },
{ question: "What is 'Lex'?", answer: "Sir, Lex is a popular software tool that automatically generates a lexical analyzer. It takes a file containing regular expressions and associated actions, and outputs C code for a scanner." },
{ question: "How are Regular Expressions used in Lexical Analysis?", answer: "Sir, regular expressions are used to formally specify the patterns for various tokens. For example, they define what constitutes a valid identifier, number, or keyword in the language." },
{ question: "What is the role of Finite Automata in recognizing tokens?", answer: "Sir, finite automata, specifically Deterministic Finite Automata (DFA), are the underlying mathematical models used to implement the regular expressions. They efficiently transition between states to recognize if a string matches a token pattern." },
{ question: "What is a Symbol Table?", answer: "Sir, the symbol table is a data structure maintained by the compiler to store information about identifiers, such as their names, types, and scope. The lexical analyzer inserts identifiers into it when they are first encountered." },
{ question: "Can a Lexical Analyzer detect errors?", answer: "Yes sir, it can detect lexical errors. If it encounters a sequence of characters that does not match any valid token pattern, it reports a lexical error, such as an illegal character." }
],
mcqs: [
{ question: "The output of the Lexical Analyzer is a stream of:", options: ["Parse trees", "Tokens", "Assembly code", "Three-address code"], answer: "Tokens" },
{ question: "Which tool is commonly used to automatically generate a lexical analyzer?", options: ["Yacc", "Bison", "Lex", "GDB"], answer: "Lex" },
{ question: "A sequence of characters in a source program that matches the pattern for a token is a:", options: ["Lexeme", "Syntax", "Grammar", "Node"], answer: "Lexeme" },
{ question: "Which mathematical model is used by lexical analyzers to recognize tokens?", options: ["Pushdown Automata", "Turing Machine", "Finite Automata", "Context Free Grammar"], answer: "Finite Automata" },
{ question: "What is used to specify the patterns of tokens?", options: ["Regular Expressions", "Syntax Trees", "Semantic Rules", "Hash Tables"], answer: "Regular Expressions" },
{ question: "The lexical analyzer communicates directly with which phase?", options: ["Code Generation", "Syntax Analysis", "Semantic Analysis", "Optimization"], answer: "Syntax Analysis" },
{ question: "What is stripped out by the lexical analyzer?", options: ["Keywords", "Identifiers", "White spaces and comments", "Operators"], answer: "White spaces and comments" },
{ question: "In input buffering, a special character marking the end of a buffer is called a:", options: ["Token", "Lexeme", "Sentinel", "Pointer"], answer: "Sentinel" },
{ question: "Which of the following is typically NOT a token?", options: ["Identifier", "Keyword", "Comment", "Operator"], answer: "Comment" },
{ question: "When the scanner cannot match a character sequence to any valid token, it raises a:", options: ["Syntax error", "Semantic error", "Lexical error", "Logical error"], answer: "Lexical error" }
]
},
{
chapterNumber: 3,
chapterName: "Syntax Analysis",
vivaQuestions: [
{ question: "What is the role of the Syntax Analyzer or Parser?", answer: "Sir, the parser receives tokens from the lexical analyzer and checks whether they form a valid sentence according to the grammar rules of the language. Its output is typically a syntax tree or parse tree." },
{ question: "What is a Context-Free Grammar (CFG)?", answer: "Sir, a CFG is a mathematical system for describing language syntax. It consists of a set of terminals, non-terminals, a start symbol, and production rules where the left side is always a single non-terminal." },
{ question: "What is Top-Down Parsing?", answer: "Sir, top-down parsing attempts to construct the parse tree from the root node (start symbol) down to the leaf nodes (tokens). Examples include Recursive Descent and LL(1) parsers." },
{ question: "What is Bottom-Up Parsing?", answer: "Sir, bottom-up parsing attempts to construct the parse tree starting from the leaves (tokens) and working up to the root (start symbol). It uses a technique called shift-reduce parsing. LR parsers use this approach." },
{ question: "What is Left Recursion?", answer: "Sir, left recursion occurs when a grammar production has a non-terminal on the left side that appears as the very first symbol on its right side, like A -> A alpha. It causes top-down parsers to enter an infinite loop." },
{ question: "What is Left Factoring?", answer: "Sir, left factoring is a grammar transformation technique used to remove ambiguity when two or more productions for a non-terminal share the same common prefix. It delays the decision until enough input is seen." },
{ question: "What is an Ambiguous Grammar?", answer: "Sir, a grammar is ambiguous if it can produce more than one valid parse tree (or more than one leftmost derivation) for the exact same input string." },
{ question: "What does LR stand for in LR Parsers?", answer: "Sir, in LR, 'L' stands for scanning the input from Left-to-right, and 'R' stands for constructing a Rightmost derivation in reverse." },
{ question: "What is Operator-Precedence Parsing?", answer: "Sir, it is a type of bottom-up parsing that can only be applied to a small class of grammars called operator grammars, where no empty productions exist and no two non-terminals are adjacent. It heavily relies on precedence relations." },
{ question: "What are Syntax-Directed Definitions (SDD)?", answer: "Sir, an SDD associates attributes with grammar symbols and semantic rules with production rules. It binds the evaluation of semantic actions to the parsing process to generate intermediate code or evaluate expressions." }
],
mcqs: [
{ question: "The output of the Syntax Analyzer is generally a:", options: ["Stream of tokens", "Parse tree", "Machine code", "Symbol table"], answer: "Parse tree" },
{ question: "Context-Free Grammars are strictly used to specify:", options: ["Lexical rules", "Syntax rules", "Semantic rules", "Hardware architecture"], answer: "Syntax rules" },
{ question: "Which parsing method builds the parse tree from the root to the leaves?", options: ["Bottom-up parsing", "Shift-reduce parsing", "Top-down parsing", "Operator precedence"], answer: "Top-down parsing" },
{ question: "Left recursion is a major problem primarily for which type of parsers?", options: ["LR Parsers", "Bottom-up parsers", "Top-down parsers", "Shift-reduce parsers"], answer: "Top-down parsers" },
{ question: "Which technique is used to resolve common prefixes in production rules?", options: ["Left recursion removal", "Left factoring", "Right recursion", "Shift-reduce"], answer: "Left factoring" },
{ question: "A grammar that produces more than one parse tree for the same string is called:", options: ["Ambiguous grammar", "Unambiguous grammar", "Regular grammar", "Linear grammar"], answer: "Ambiguous grammar" },
{ question: "In an LL(1) parser, the first 'L' stands for:", options: ["Leftmost derivation", "Lexical analysis", "Left-to-right scanning", "Lookahead"], answer: "Left-to-right scanning" },
{ question: "Which of the following is the most powerful bottom-up parser?", options: ["SLR", "LALR", "LR(0)", "Canonical LR(1)"], answer: "Canonical LR(1)" },
{ question: "What does 'YACC' stand for?", options: ["Yet Another Compiler Compiler", "Yield And Compile Code", "Your Automatic C Compiler", "Yet Another C Compiler"], answer: "Yet Another Compiler Compiler" },
{ question: "Syntax-Directed Translations rely on attaching what to grammar symbols?", options: ["Pointers", "Attributes", "Tokens", "Registers"], answer: "Attributes" }
]
},
{
chapterNumber: 4,
chapterName: "Error Recovery",
vivaQuestions: [
{ question: "What is Error Recovery in a compiler?", answer: "Sir, error recovery is the process where the compiler attempts to handle a detected error so that it can continue parsing the rest of the code, allowing it to find multiple errors in a single compilation run." },
{ question: "Which phase of the compiler detects the most errors?", answer: "Sir, the syntax analysis phase, or the parser, typically detects the highest number of errors because it checks the structural validity of the program against the grammar rules." },
{ question: "What is Panic Mode error recovery?", answer: "Sir, panic mode is a simple systematic recovery strategy. When an error is found, the parser discards input tokens one at a time until it finds a designated 'synchronizing token', like a semicolon or a closing brace, to safely resume parsing." },
{ question: "What is Phrase-Level recovery?", answer: "Sir, in phrase-level recovery, when a parser detects an error, it performs local correction on the remaining input. For example, it might replace a comma with a semicolon or insert a missing parenthesis to fix the phrase." },
{ question: "What are Ad-Hoc error recovery methods?", answer: "Sir, ad-hoc methods are specific, hand-coded, non-systematic recovery techniques implemented by the compiler designer based on common programming mistakes they anticipate users will make." },
{ question: "What is Error Production?", answer: "Sir, error production involves intentionally adding grammar rules that generate common errors. If an error production is used during parsing, the compiler knows exactly what mistake the programmer made and can give a very specific error message." },
{ question: "What is Global Correction?", answer: "Sir, global correction algorithms aim to find the minimal sequence of changes (insertions, deletions, or mutations) to transform an erroneous input string into a valid string. It is theoretically robust but practically too slow for large files." },
{ question: "What happens if a compiler does not have error recovery?", answer: "Sir, without error recovery, the compiler would halt execution and exit immediately upon encountering the very first error, forcing the programmer to recompile after fixing every single trivial mistake." },
{ question: "What is a synchronizing token?", answer: "Sir, a synchronizing token is a clearly defined delimiter in a language, such as a semicolon, 'end', or '}', which the parser skips forward to in Panic Mode to regain its structural orientation." },
{ question: "Can the lexical analyzer recover from errors?", answer: "Yes sir, the scanner has basic recovery techniques. The simplest panic mode for a scanner is to delete successive illegal characters until a valid token pattern is matched." }
],
mcqs: [
{ question: "Which phase typically detects syntax errors like missing semicolons?", options: ["Lexical Analysis", "Syntax Analysis", "Semantic Analysis", "Code Optimization"], answer: "Syntax Analysis" },
{ question: "The strategy of skipping input tokens until a synchronizing token is found is called:", options: ["Phrase-level recovery", "Global correction", "Panic mode recovery", "Error production"], answer: "Panic mode recovery" },
{ question: "A synchronizing token is typically a:", options: ["Variable name", "Number", "Delimiter like a semicolon", "Mathematical operator"], answer: "Delimiter like a semicolon" },
{ question: "Replacing a comma with a semicolon locally is an example of:", options: ["Panic mode", "Phrase-level recovery", "Global correction", "Ad-hoc recovery"], answer: "Phrase-level recovery" },
{ question: "Adding specific grammar rules to catch common mistakes relies on:", options: ["Panic mode", "Error productions", "Semantic checks", "Lexical stripping"], answer: "Error productions" },
{ question: "Which error recovery method is generally too costly in terms of time and space to use in practice?", options: ["Panic mode", "Phrase-level", "Ad-hoc", "Global correction"], answer: "Global correction" },
{ question: "What is the primary goal of error recovery in compilers?", options: ["To fix the code for the user automatically", "To continue parsing to find further errors", "To format the code", "To optimize the execution speed"], answer: "To continue parsing to find further errors" },
{ question: "Hand-coded, custom error handling routines are known as:", options: ["Systematic methods", "Ad-hoc methods", "Global methods", "Panic methods"], answer: "Ad-hoc methods" },
{ question: "A lexical error occurs when:", options: ["A variable is undeclared", "Parentheses are unbalanced", "An invalid character is encountered", "Types do not match"], answer: "An invalid character is encountered" },
{ question: "Semantic errors are generally related to:", options: ["Missing semicolons", "Illegal characters", "Meaning and type mismatches", "Incorrect spelling of keywords"], answer: "Meaning and type mismatches" }
]
},
{
chapterNumber: 5,
chapterName: "Intermediate-Code Generation",
vivaQuestions: [
{ question: "What is Intermediate Code?", answer: "Sir, intermediate code is a machine-independent, internal representation of the source program created by the compiler between the frontend (parsing) and backend (code generation) phases." },
{ question: "Why do we generate Intermediate Code?", answer: "Sir, it decouples the source language from the target machine. This allows for machine-independent code optimization, and makes it easier to create compilers for multiple languages or multiple machines by sharing the same backend." },
{ question: "What is an Abstract Syntax Tree (AST)?", answer: "Sir, an AST is a variant of a syntax tree where interior nodes represent operators and leaf nodes represent operands. It abstracts away unnecessary grammatical details like parentheses." },
{ question: "What is Three-Address Code (TAC)?", answer: "Sir, Three-Address Code is a linear intermediate representation where each instruction has at most three addresses (two operands and one result) and at most one operator on the right side." },
{ question: "How is Three-Address Code implemented in memory?", answer: "Sir, TAC can be implemented using data structures like Quadruples, Triples, or Indirect Triples." },
{ question: "What is a Quadruple?", answer: "Sir, a quadruple is a data structure for TAC consisting of four fields: Operator, Argument 1, Argument 2, and Result. It stores the result in an explicit temporary variable." },
{ question: "What is a Triple?", answer: "Sir, a triple avoids storing explicit temporary variables. It has three fields: Operator, Argument 1, and Argument 2. The result of a previous operation is referred to by its position or index in the triple array." },
{ question: "What is Type Checking?", answer: "Sir, type checking is a semantic analysis process where the compiler ensures that the operators are supplied with compatible operands according to the language's type system rules." },
{ question: "What is a Syntax-Directed Translation Mechanism?", answer: "Sir, it is a method where the translation of the source code is driven directly by its syntax. We associate semantic actions with the grammar rules to generate the intermediate code as the parse tree is constructed." },
{ question: "What is the difference between Synthesized and Inherited attributes?", answer: "Sir, a synthesized attribute gets its value from the attributes of its child nodes in the parse tree. An inherited attribute gets its value from its parent node or sibling nodes." }
],
mcqs: [
{ question: "Which of the following is an advantage of generating intermediate code?", options: ["It slows down the compiler", "It makes retargeting to new machines easier", "It uses more memory", "It replaces the parser"], answer: "It makes retargeting to new machines easier" },
{ question: "A syntax tree where interior nodes represent operators is called an:", options: ["Abstract Syntax Tree", "Parse Tree", "Derivation Tree", "Decision Tree"], answer: "Abstract Syntax Tree" },
{ question: "An instruction in Three-Address Code can have at most how many addresses?", options: ["One", "Two", "Three", "Four"], answer: "Three" },
{ question: "Which implementation of TAC uses four fields: op, arg1, arg2, and result?", options: ["Triples", "Quadruples", "Indirect Triples", "Syntax Trees"], answer: "Quadruples" },
{ question: "Which TAC implementation refers to intermediate results by their statement position instead of temporary variables?", options: ["Quadruples", "Triples", "Abstract Trees", "DAGs"], answer: "Triples" },
{ question: "Type checking ensures that:", options: ["The grammar is unambiguous", "Operands are compatible with the operators", "There are no missing semicolons", "The code fits in memory"], answer: "Operands are compatible with the operators" },
{ question: "An attribute whose value is computed from the values of its children is called:", options: ["Inherited attribute", "Synthesized attribute", "Static attribute", "Dynamic attribute"], answer: "Synthesized attribute" },
{ question: "An attribute whose value is computed from its parent or siblings is called:", options: ["Inherited attribute", "Synthesized attribute", "Global attribute", "Local attribute"], answer: "Inherited attribute" },
{ question: "Which of the following is NOT a form of intermediate code?", options: ["Syntax Tree", "Postfix Notation", "Three-Address Code", "Assembly Code"], answer: "Assembly Code" },
{ question: "In a syntax-directed definition, semantic rules are attached to:", options: ["Tokens", "Production rules", "Keywords", "Machine registers"], answer: "Production rules" }
]
},
{
chapterNumber: 6,
chapterName: "Run-Time Environments",
vivaQuestions: [
{ question: "What is a Run-Time Environment?", answer: "Sir, a run-time environment is a state setup by the compiler and operating system to manage memory, scope, and the execution of the target program when it actually runs." },
{ question: "What is an Activation Record?", answer: "Sir, an activation record, or stack frame, is a contiguous block of memory allocated on the run-time stack every time a function or procedure is called. It stores local variables, return addresses, and parameters." },
{ question: "What are the typical storage allocations managed by a compiler?", answer: "Sir, compilers typically manage three types of storage allocation: Static Allocation, Stack Allocation, and Heap Allocation." },
{ question: "What is Static Allocation?", answer: "Sir, in static allocation, memory is allocated to variables at compile time. These variables, like global variables, retain their values throughout the entire execution of the program and their addresses do not change." },
{ question: "What is Stack Allocation?", answer: "Sir, stack allocation manages the memory for function calls using a Last-In-First-Out (LIFO) structure. Activation records are pushed onto the stack when a function is called and popped when it returns." },
{ question: "What is Heap Management?", answer: "Sir, heap management handles dynamic memory allocation where blocks of memory are allocated and freed at run-time in any order, such as when using 'malloc' in C or 'new' in Java." },
{ question: "How are non-local variables accessed in the stack?", answer: "Sir, non-local variables (variables in outer scopes) are accessed using access links or a display array, which point to the activation records of the lexically enclosing procedures." },
{ question: "What is the difference between Static and Dynamic Scoping?", answer: "Sir, in static (lexical) scoping, the scope of a variable is determined by the physical structure of the code at compile time. In dynamic scoping, it is determined by the sequence of function calls at run-time." },
{ question: "What is a Dangling Pointer?", answer: "Sir, a dangling pointer occurs in heap management when a pointer still references a memory location that has already been deallocated or freed, leading to unpredictable behavior if accessed." },
{ question: "Why is garbage collection needed in heap management?", answer: "Sir, garbage collection automatically reclaims heap memory that is no longer accessible or referenced by the program, preventing memory leaks and avoiding dangling pointers." }
],
mcqs: [
{ question: "The block of memory pushed onto the stack for a function call is known as an:", options: ["Heap block", "Activation Record", "Static array", "Basic Block"], answer: "Activation Record" },
{ question: "Global variables are typically managed using:", options: ["Heap allocation", "Stack allocation", "Static allocation", "Dynamic allocation"], answer: "Static allocation" },
{ question: "Which memory allocation strategy uses a LIFO (Last-In-First-Out) structure?", options: ["Heap allocation", "Stack allocation", "Static allocation", "Register allocation"], answer: "Stack allocation" },
{ question: "Memory allocated dynamically at run-time (e.g., via malloc) is managed in the:", options: ["Stack", "Data section", "Heap", "Text segment"], answer: "Heap" },
{ question: "Which pointer links an activation record to the activation record of its lexically enclosing function?", options: ["Control link", "Access link", "Dynamic link", "Return pointer"], answer: "Access link" },
{ question: "A pointer referencing deallocated memory is called a:", options: ["Null pointer", "Void pointer", "Dangling pointer", "Wild pointer"], answer: "Dangling pointer" },
{ question: "If scope is determined by the sequence of function calls at execution, it is called:", options: ["Static scoping", "Lexical scoping", "Dynamic scoping", "Block scoping"], answer: "Dynamic scoping" },
{ question: "Which allocation scheme cannot support recursive function calls?", options: ["Static allocation", "Stack allocation", "Heap allocation", "Dynamic allocation"], answer: "Static allocation" },
{ question: "What automatically reclaims unused heap memory in languages like Java?", options: ["The Linker", "The Loader", "Garbage Collector", "The Parser"], answer: "Garbage Collector" },
{ question: "The saved value of the machine's program counter before a function jump is called the:", options: ["Access link", "Control link", "Return address", "Local data"], answer: "Return address" }
]
},
{
chapterNumber: 7,
chapterName: "Code Generation and Optimization",
vivaQuestions: [
{ question: "What is the Code Generation phase?", answer: "Sir, code generation is the final phase of the compiler. It takes the optimized intermediate code and translates it into the target language, which is usually assembly code or machine code." },
{ question: "What is a Basic Block?", answer: "Sir, a basic block is a sequence of consecutive intermediate instructions with exactly one entry point at the beginning and exactly one exit point at the end, with no branching in or out in between." },
{ question: "What is a Flow Graph?", answer: "Sir, a flow graph is a directed graph where the nodes represent basic blocks and the edges represent the control flow or branching between those blocks." },
{ question: "What is the difference between Machine-Dependent and Machine-Independent Optimization?", answer: "Sir, machine-independent optimization improves the intermediate code logic (like loop unrolling or dead code elimination) without caring about CPU architecture. Machine-dependent optimization optimizes specifically for the target CPU's registers and instruction set." },
{ question: "What is Peephole Optimization?", answer: "Sir, peephole optimization is a localized, machine-dependent optimization pass. It looks at a tiny, sliding window (peephole) of target instructions and replaces them with a shorter or faster equivalent sequence." },
{ question: "What is Dead Code Elimination?", answer: "Sir, dead code elimination is an optimization technique where the compiler removes code that calculates values which are never used elsewhere in the program, or code that can never be executed." },
{ question: "What is Common Subexpression Elimination?", answer: "Sir, if the same mathematical expression is evaluated multiple times with unchanged variables, the compiler calculates it once, stores the result, and replaces subsequent occurrences with that stored value to save time." },
{ question: "What is a DAG in code optimization?", answer: "Sir, a Directed Acyclic Graph (DAG) is used to represent the operations within a basic block to easily detect common subexpressions and identify dead code." },
{ question: "What is Register Allocation?", answer: "Sir, register allocation is a crucial task in code generation. Since CPU registers are the fastest memory, the compiler must smartly decide which variables reside in registers to minimize slow memory access." },
{ question: "What are the major issues in the design of a code generator?", answer: "Sir, the major issues include instruction selection, register allocation and assignment, deciding the evaluation order of operations, and managing memory effectively." }
],
mcqs: [
{ question: "A sequence of instructions with only one entry and one exit point is a:", options: ["Flow graph", "Basic block", "Function", "Module"], answer: "Basic block" },
{ question: "In a flow graph, the nodes represent:", options: ["Variables", "Operators", "Basic blocks", "Registers"], answer: "Basic blocks" },
{ question: "Which optimization technique examines a short, sliding window of instructions?", options: ["Loop unrolling", "Peephole optimization", "Global optimization", "Data-flow analysis"], answer: "Peephole optimization" },
{ question: "Removing code whose calculated values are never used is called:", options: ["Loop optimization", "Dead code elimination", "Constant folding", "Strength reduction"], answer: "Dead code elimination" },
{ question: "Replacing an expensive operation (like x * 2) with a cheaper one (like x + x) is called:", options: ["Dead code elimination", "Strength reduction", "Code hoisting", "Common subexpression elimination"], answer: "Strength reduction" },
{ question: "Which data structure is useful for optimizing a single basic block?", options: ["Linked List", "Stack", "DAG (Directed Acyclic Graph)", "Hash Table"], answer: "DAG (Directed Acyclic Graph)" },
{ question: "Which optimization evaluates constant expressions at compile time (e.g., replacing 3*4 with 12)?", options: ["Constant folding", "Loop unrolling", "Strength reduction", "Register allocation"], answer: "Constant folding" },
{ question: "Which of the following is a machine-dependent optimization?", options: ["Dead code elimination", "Register allocation", "Common subexpression elimination", "Loop invariant removal"], answer: "Register allocation" },
{ question: "The final output of the Code Generator is typically:", options: ["Intermediate code", "Target machine/assembly code", "Syntax tree", "Tokens"], answer: "Target machine/assembly code" },
{ question: "Moving code out of a loop that computes the same value every iteration is called:", options: ["Loop invariant code motion", "Loop unrolling", "Dead code elimination", "Strength reduction"], answer: "Loop invariant code motion" }
]
},
{
chapterNumber: 8,
chapterName: "Instruction-Level Parallelism",
vivaQuestions: [
{ question: "What is Instruction-Level Parallelism (ILP)?", answer: "Sir, Instruction-Level Parallelism is the hardware or compiler technique of executing multiple independent instructions simultaneously to improve the execution speed of a program." },
{ question: "How does the compiler help in Instruction-Level Parallelism?", answer: "Sir, modern processors have pipelines. The compiler helps by scheduling and reordering the target instructions so that independent instructions fill the pipeline slots, avoiding CPU stalls." },
{ question: "What is a Code-Scheduling Constraint?", answer: "Sir, code-scheduling constraints are rules that prevent instructions from being reordered arbitrarily. The primary constraints are data dependencies (one instruction needs the result of another) and hardware resource limits." },
{ question: "What is Basic-Block Scheduling?", answer: "Sir, basic-block scheduling is the process of reordering the instructions within a single basic block to maximize instruction-level parallelism while strictly respecting data dependencies." },
{ question: "What is Data Dependence?", answer: "Sir, data dependence occurs when the execution of one instruction depends on the data produced by a preceding instruction. You cannot execute them in parallel." },
{ question: "What is the Pass Structure of an Assembler?", answer: "Sir, a typical assembler is a two-pass system. Pass 1 assigns addresses to all instructions and builds the symbol table for labels. Pass 2 translates the assembly mnemonics into machine code using that symbol table." },
{ question: "Why does an assembler need two passes?", answer: "Sir, an assembler needs two passes primarily to handle forward references. A jump instruction might reference a label defined further down in the code, so Pass 1 must find its address before Pass 2 can generate the code." },
{ question: "What is a processor pipeline?", answer: "Sir, a pipeline divides instruction execution into stages (like fetch, decode, execute). It allows multiple instructions to be in different stages of execution at the same exact time." },
{ question: "What is a hazard in instruction scheduling?", answer: "Sir, a hazard is a situation that prevents the next instruction in the instruction stream from executing during its designated clock cycle. Common types are structural, data, and control hazards." },
{ question: "How does loop unrolling assist ILP?", answer: "Sir, loop unrolling duplicates the loop body, reducing the overhead of loop control instructions and exposing more independent instructions to the compiler, which greatly increases instruction-level parallelism." }
],
mcqs: [
{ question: "Executing multiple instructions simultaneously within a single processor clock cycle is known as:", options: ["Instruction-Level Parallelism (ILP)", "Multiprocessing", "Time-sharing", "Multithreading"], answer: "Instruction-Level Parallelism (ILP)" },
{ question: "The process of reordering instructions to maximize pipeline efficiency is called:", options: ["Lexical analysis", "Code scheduling", "Parsing", "Memory allocation"], answer: "Code scheduling" },
{ question: "What prevents an instruction from executing parallel to another because it needs the other's output?", options: ["Resource constraint", "Data dependence", "Syntax error", "Memory leak"], answer: "Data dependence" },
{ question: "Scheduling instructions strictly within the boundaries of a single basic block is called:", options: ["Global scheduling", "Basic-block scheduling", "Software pipelining", "Trace scheduling"], answer: "Basic-block scheduling" },
{ question: "A typical assembler translates source code in how many passes?", options: ["One", "Two", "Three", "Four"], answer: "Two" },
{ question: "What is the primary purpose of Pass 1 in a two-pass assembler?", options: ["Generating machine code", "Building the symbol table and assigning addresses", "Executing the program", "Optimizing the code"], answer: "Building the symbol table and assigning addresses" },
{ question: "Forward references in assembly language are the main reason assemblers require:", options: ["More RAM", "A two-pass structure", "Object-oriented syntax", "A virtual machine"], answer: "A two-pass structure" },
{ question: "Which CPU feature allows multiple instructions to overlap in execution stages?", options: ["Pipelining", "Caching", "Virtual Memory", "Clock speed"], answer: "Pipelining" },
{ question: "Which optimization technique exposes more ILP by duplicating the body of a loop?", options: ["Dead code elimination", "Loop unrolling", "Constant folding", "Peephole optimization"], answer: "Loop unrolling" },
{ question: "Situations in a pipeline that prevent the next instruction from executing are called:", options: ["Hazards", "Interrupts", "Exceptions", "Deadlocks"], answer: "Hazards" }
]
}
]
};