export const informationRetrievalVivaData = [
  {
    chapterTitle: "Introduction to Information Retrieval",
    vivaQuestions: [
      { question: "What is Information Retrieval (IR)?", answer: "Yes sir, Information Retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources, like searching for documents on the web." },
      { question: "How does Information Retrieval differ from Data Retrieval?", answer: "Sir, data retrieval involves finding exact matches in structured databases like SQL, whereas information retrieval deals with finding relevant or partial matches in unstructured data like text documents." },
      { question: "What do you mean by unstructured text?", answer: "Sir, unstructured text refers to information that either does not have a pre-defined data model or is not organized in a pre-defined manner, like standard English paragraphs or emails." },
      { question: "What is semi-structured text?", answer: "Sir, semi-structured text is data that doesn't reside in a relational database but has some organizational properties that make it easier to analyze, like XML or HTML documents containing tags." },
      { question: "What is an inverted index?", answer: "Yes sir, an inverted index is the core data structure used in search engines. It maps content, such as words or numbers, to its locations in a document or a set of documents." },
      { question: "Why do we use an inverted index instead of a forward index?", answer: "Sir, we use an inverted index because it allows for very fast full-text searches. Instead of scanning every document for a word, the index tells us exactly which documents contain that word." },
      { question: "What is a Boolean query?", answer: "Sir, a Boolean query is a search query that uses logical operators like AND, OR, and NOT to combine keywords, allowing users to define exactly what must or must not be in the results." },
      { question: "Can you explain the AND operator in Boolean retrieval?", answer: "Yes sir, the AND operator requires that all the terms connected by it must be present in the document for it to be retrieved as a match." },
      { question: "How does the OR operator work?", answer: "Sir, the OR operator retrieves a document if at least one of the connected search terms is present in the document, which broadens the search results." },
      { question: "What is the purpose of the NOT operator?", answer: "Sir, the NOT operator excludes documents that contain the specified term, helping to filter out irrelevant results." },
      { question: "What is the main limitation of the Boolean retrieval model?", answer: "The main limitation, sir, is that it relies on exact matches and provides binary decisions—a document is either retrieved or not. It cannot rank documents based on their degree of relevance." },
      { question: "What is an Information Need?", answer: "Sir, an information need is the topic or subject about which a user desires to know more, which they translate into a query for the IR system." },
      { question: "What is a Query?", answer: "Yes sir, a query is the actual string of text or commands that a user submits to an Information Retrieval system to express their information need." },
      { question: "What is a Document Collection or Corpus?", answer: "Sir, a corpus is the total group of documents over which the Information Retrieval system performs its indexing and searching." },
      { question: "What is the role of a web crawler in IR?", answer: "Sir, a web crawler is an automated script that browses the internet systematically to discover and download web pages so they can be indexed by the search engine." },
      { question: "What are the two main phases of an IR system?", answer: "Sir, the two main phases are the Indexing phase, where documents are processed and stored in an inverted index, and the Retrieval phase, where user queries are evaluated against the index." },
      { question: "What is the Dictionary or Lexicon in an inverted index?", answer: "Yes sir, the dictionary is the part of the inverted index that holds all the unique terms found in the document collection, along with pointers to their posting lists." },
      { question: "What is a Postings List?", answer: "Sir, a postings list is a list associated with a specific term in the dictionary that records the document IDs of all documents containing that term." },
      { question: "Why is sorting document IDs in a postings list important?", answer: "Sir, sorting document IDs allows for efficient merging of lists when processing Boolean AND queries, typically using a linear time two-pointer intersection algorithm." },
      { question: "What is an incidence matrix?", answer: "Sir, a term-document incidence matrix is a 2D matrix where rows represent terms, columns represent documents, and cells contain 1 or 0 indicating if the term is present. It is usually too sparse to be efficient, which is why we use inverted indexes." }
    ],
    mcqs: [
      { question: "Which of the following deals with unstructured data?", options: ["Data Retrieval", "Information Retrieval", "Relational Databases", "SQL"], correctAnswer: "Information Retrieval" },
      { question: "What is the primary data structure used by search engines?", options: ["Array", "Linked List", "Inverted Index", "B-Tree"], correctAnswer: "Inverted Index" },
      { question: "Which Boolean operator broadens a search?", options: ["AND", "NOT", "OR", "XOR"], correctAnswer: "OR" },
      { question: "Which Boolean operator narrows a search by requiring all terms?", options: ["AND", "OR", "NOT", "NOR"], correctAnswer: "AND" },
      { question: "What maps words to the documents they appear in?", options: ["Forward Index", "Inverted Index", "Incidence Matrix", "SQL Table"], correctAnswer: "Inverted Index" },
      { question: "HTML and XML are examples of:", options: ["Structured data", "Unstructured data", "Semi-structured data", "Binary data"], correctAnswer: "Semi-structured data" },
      { question: "The list of document IDs for a given term is called:", options: ["Lexicon", "Postings List", "Dictionary", "Corpus"], correctAnswer: "Postings List" },
      { question: "The collection of all documents is referred to as the:", options: ["Corpus", "Lexicon", "Index", "Query"], correctAnswer: "Corpus" },
      { question: "Which of these is a disadvantage of the Boolean model?", options: ["Fast retrieval", "No ranking of documents", "Exact match capabilities", "Uses sets"], correctAnswer: "No ranking of documents" },
      { question: "In a term-document incidence matrix, what does a '1' signify?", options: ["Term absence", "Term presence", "Document deletion", "Query end"], correctAnswer: "Term presence" },
      { question: "Merging two sorted postings lists for an AND query takes what time complexity?", options: ["O(x * y)", "O(x + y)", "O(log(x+y))", "O(x^y)"], correctAnswer: "O(x + y)" },
      { question: "Information Retrieval focuses on finding documents that are:", options: ["Exactly identical", "Relevant", "Encrypted", "Compiled"], correctAnswer: "Relevant" },
      { question: "Which of the following translates an information need into a system format?", options: ["Corpus", "Query", "Index", "Crawler"], correctAnswer: "Query" },
      { question: "The vocabulary of an IR system is stored in the:", options: ["Postings", "Dictionary/Lexicon", "Crawler", "Spam filter"], correctAnswer: "Dictionary/Lexicon" },
      { question: "A query like 'apple AND NOT orange' will retrieve:", options: ["Documents with both", "Documents with neither", "Documents with apple but no orange", "Documents with orange but no apple"], correctAnswer: "Documents with apple but no orange" },
      { question: "Web pages are typically considered:", options: ["Fully structured", "Unstructured or Semi-structured", "Relational", "Tabular"], correctAnswer: "Unstructured or Semi-structured" },
      { question: "The algorithm used to evaluate Boolean AND queries is:", options: ["Binary Search", "List intersection / Merge", "Bubble Sort", "Dijkstra's"], correctAnswer: "List intersection / Merge" },
      { question: "What is the primary reason an incidence matrix is not used for web search?", options: ["Too complex", "Matrix is too sparse and wastes memory", "It cannot evaluate AND", "It is too small"], correctAnswer: "Matrix is too sparse and wastes memory" },
      { question: "Which operator excludes specific terms?", options: ["AND", "OR", "NOT", "IF"], correctAnswer: "NOT" },
      { question: "The transition from a user's thought to text is called forming a:", options: ["Corpus", "Query", "Index", "Relevance list"], correctAnswer: "Query" }
    ]
  },
  {
    chapterTitle: "Text Indexing, Storage and Compression",
    vivaQuestions: [
      { question: "What is tokenization?", answer: "Yes sir, tokenization is the process of breaking down a stream of text into individual words, phrases, or meaningful elements called tokens, which are then used for indexing." },
      { question: "What is stemming?", answer: "Sir, stemming is a heuristic process that reduces words to their base or root form by removing suffixes and prefixes, so words like 'running' and 'runner' are indexed under 'run'." },
      { question: "What is the difference between stemming and lemmatization?", answer: "Sir, stemming chops off word endings blindly, whereas lemmatization uses a dictionary and morphological analysis to accurately return the base word, known as the lemma." },
      { question: "What are stop words?", answer: "Yes sir, stop words are very common words in a language, like 'the', 'is', and 'at', which are often filtered out during indexing to save space and processing time since they carry little meaning." },
      { question: "Why might a modern search engine choose NOT to remove stop words?", answer: "Sir, modern search engines often keep stop words because they are crucial for phrase queries. For example, searching for 'to be or not to be' relies entirely on stop words." },
      { question: "What is index compression and why is it needed?", answer: "Sir, index compression reduces the amount of memory and disk space required to store the inverted index. It is needed to keep the index in fast RAM, which drastically speeds up query processing." },
      { question: "What is Gap encoding?", answer: "Yes sir, gap encoding is a compression technique where, instead of storing actual document IDs in a postings list, we store the mathematical gaps or differences between consecutive IDs to use smaller numbers." },
      { question: "What are Gamma codes?", answer: "Sir, Elias Gamma coding is a variable-length universal code used to compress positive integers. It encodes an integer by representing its length in unary followed by its binary representation." },
      { question: "What does Zipf's Law state?", answer: "Sir, Zipf's Law states that in a large collection of text, the frequency of any word is inversely proportional to its rank in the frequency table. The most frequent word occurs roughly twice as often as the second most frequent." },
      { question: "How does index construction work?", answer: "Sir, index construction involves gathering documents, tokenizing the text, applying linguistic processing like stemming, creating term-document ID pairs, sorting them, and grouping them into a dictionary and postings lists." },
      { question: "What is Block Sort-Based Indexing (BSBI)?", answer: "Yes sir, BSBI is an algorithm for building large indexes where the corpus is divided into blocks that fit in memory, each block is inverted and written to disk, and finally, all blocks are merged." },
      { question: "What is a positional index?", answer: "Sir, a positional index is an advanced inverted index that stores not just the document ID where a term occurs, but also the exact numerical positions of the term within that document." },
      { question: "Why do we need positional indexes?", answer: "We need them for evaluating phrase queries, sir. If a user searches for 'New York', the positional index allows us to check if the word 'York' appears exactly one position after 'New'." },
      { question: "What is an n-gram index?", answer: "Sir, an n-gram index breaks text down into overlapping sequences of 'n' characters or words. For example, a 3-gram index for 'hello' would store 'hel', 'ell', 'llo'." },
      { question: "What is the primary use of an n-gram index?", answer: "Sir, n-gram indexes are primarily used for wildcard queries, spelling correction, and finding terms that are substrings of other terms." },
      { question: "What is dynamic indexing?", answer: "Yes sir, dynamic indexing handles document collections that change over time. It uses a main index and a small auxiliary index in memory for new documents, periodically merging the two." },
      { question: "What is lexicon compression?", answer: "Sir, lexicon compression reduces the size of the dictionary holding the terms. Techniques include converting the dictionary into a single long string and using pointers, or using front coding for words sharing prefixes." },
      { question: "What is front coding?", answer: "Sir, front coding is a lexicon compression technique that stores common prefixes of consecutive words only once. For example, 'automata', 'automate', 'automatic' share the prefix 'automat'." },
      { question: "How do you estimate the size of a postings list?", answer: "Sir, postings size estimation can be done by calculating the expected number of tokens based on document length and applying laws like Heaps' Law for vocabulary growth." },
      { question: "What is Heaps' Law?", answer: "Yes sir, Heaps' Law is an empirical law used to estimate the vocabulary size of a corpus as a function of the total number of words, showing that vocabulary size continues to grow but at a decreasing rate." }
    ],
    mcqs: [
      { question: "The process of breaking text into individual words is called:", options: ["Stemming", "Tokenization", "Lemmatization", "Parsing"], correctAnswer: "Tokenization" },
      { question: "Which technique reduces words to their root form blindly?", options: ["Lemmatization", "Tokenization", "Stemming", "Stop word removal"], correctAnswer: "Stemming" },
      { question: "Words like 'the', 'and', 'is' are known as:", options: ["Keywords", "Stop words", "Tokens", "N-grams"], correctAnswer: "Stop words" },
      { question: "Storing the difference between document IDs rather than the IDs themselves is:", options: ["Gap encoding", "Gamma coding", "Huffman coding", "Front coding"], correctAnswer: "Gap encoding" },
      { question: "Which law states that word frequency is inversely proportional to its rank?", options: ["Heaps' Law", "Zipf's Law", "Moore's Law", "Amdahl's Law"], correctAnswer: "Zipf's Law" },
      { question: "Which index type is required for phrase queries like 'computer science'?", options: ["Bi-word index", "Positional index", "N-gram index", "Both A and B"], correctAnswer: "Both A and B" },
      { question: "To handle wildcard queries like 'comp*ter', which index is best?", options: ["Positional index", "Inverted index", "N-gram index", "Forward index"], correctAnswer: "N-gram index" },
      { question: "Which algorithm is used to build indexes larger than available RAM?", options: ["Bubble Sort", "BSBI (Block Sort-Based Indexing)", "Binary Search", "DFS"], correctAnswer: "BSBI (Block Sort-Based Indexing)" },
      { question: "Which law predicts vocabulary growth as the collection size increases?", options: ["Zipf's Law", "Heaps' Law", "Benford's Law", "Boyle's Law"], correctAnswer: "Heaps' Law" },
      { question: "Which coding scheme uses unary and binary formats to compress integers?", options: ["Gap coding", "ASCII coding", "Elias Gamma coding", "Front coding"], correctAnswer: "Elias Gamma coding" },
      { question: "Front coding is a technique primarily used for compressing the:", options: ["Postings list", "Documents", "Lexicon/Dictionary", "URLs"], correctAnswer: "Lexicon/Dictionary" },
      { question: "What is the primary reason for index compression?", options: ["To make it unreadable", "To fit the index in memory/RAM", "To follow Zipf's law", "To slow down queries"], correctAnswer: "To fit the index in memory/RAM" },
      { question: "Dynamic indexing uses an auxiliary index primarily to handle:", options: ["Deleted words", "New document insertions", "Spelling errors", "Synonyms"], correctAnswer: "New document insertions" },
      { question: "What morphological analysis tool requires a dictionary to find the root word?", options: ["Stemmer", "Lemmatizer", "Tokenizer", "Parser"], correctAnswer: "Lemmatizer" },
      { question: "Which algorithm is commonly used for stemming in English?", options: ["Dijkstra's Algorithm", "Porter Stemmer", "K-means", "Rocchio"], correctAnswer: "Porter Stemmer" },
      { question: "If the first ID is 10 and the second is 15, gap encoding stores them as:", options: ["10, 15", "10, 5", "5, 10", "15, -5"], correctAnswer: "10, 5" },
      { question: "In BSBI, what is done after all blocks are inverted and stored on disk?", options: ["They are deleted", "They are merged into a final index", "They are compressed using JPEG", "They are sent to the user"], correctAnswer: "They are merged into a final index" },
      { question: "What problem does periodic merging in dynamic indexing solve?", options: ["Memory exhaustion from auxiliary index", "Too many stop words", "Low network bandwidth", "Hardware failure"], correctAnswer: "Memory exhaustion from auxiliary index" },
      { question: "Which character is typically appended for wildcard n-gram searches?", options: ["&", "$", "*", "#"], correctAnswer: "$" },
      { question: "Removing stop words usually affects which of the following the most?", options: ["Single word queries", "Phrase queries", "Boolean queries", "Wildcard queries"], correctAnswer: "Phrase queries" }
    ]
  },
  {
    chapterTitle: "Retrieval Models",
    vivaQuestions: [
      { question: "What is the Vector Space Model?", answer: "Yes sir, the Vector Space Model represents documents and queries as algebraic vectors in a multi-dimensional space, where each dimension corresponds to a unique term, allowing us to compute continuous similarity scores." },
      { question: "What is TF-IDF?", answer: "Sir, TF-IDF stands for Term Frequency-Inverse Document Frequency. It is a statistical measure used to evaluate how important a word is to a document in a collection or corpus." },
      { question: "How is Term Frequency (TF) calculated?", answer: "Sir, Term Frequency is the number of times a term appears in a document. It is often logarithmically scaled to dampen the effect of words appearing unusually many times." },
      { question: "What is the significance of Inverse Document Frequency (IDF)?", answer: "Sir, IDF diminishes the weight of terms that occur very frequently in the document set and increases the weight of terms that occur rarely, helping to highlight unique keywords." },
      { question: "What is the Cosine Similarity measure?", answer: "Yes sir, cosine similarity measures the cosine of the angle between the query vector and the document vector. A smaller angle means higher similarity, resulting in a cosine value closer to 1." },
      { question: "Why do we use Cosine measure instead of Euclidean distance?", answer: "Sir, we use cosine similarity because it inherently normalizes for document length. Euclidean distance would unfairly penalize longer documents even if they have similar content proportions to the query." },
      { question: "What is document length normalization?", answer: "Sir, it is a technique applied in vector space scoring to adjust term weights so that short and long documents are evaluated fairly, preventing long documents from naturally scoring higher due to more terms." },
      { question: "What is the Okapi BM25 model?", answer: "Sir, BM25 is a highly effective bag-of-words retrieval function that ranks a set of documents based on the query terms appearing in each document. It improves upon standard TF-IDF by adding term frequency saturation and document length normalization parameters." },
      { question: "What is the Probabilistic Retrieval Model?", answer: "Yes sir, the probabilistic model estimates the probability that a document will be relevant to a user's query, typically utilizing the Probability Ranking Principle to order documents." },
      { question: "What is the Language Modeling approach to IR?", answer: "Sir, in Language Modeling, we build a probabilistic generative model for each document and rank documents based on the probability that their specific language model would generate the user's query." },
      { question: "What is Latent Semantic Indexing (LSI)?", answer: "Sir, LSI uses Singular Value Decomposition (SVD) to reduce the dimensionality of the term-document matrix, capturing the underlying latent 'concepts' rather than exact terms, helping with synonyms." },
      { question: "What problem does LSI solve?", answer: "Sir, LSI primarily solves the problems of synonymy (different words meaning the same thing) and polysemy (one word having multiple meanings) by grouping related terms into concepts." },
      { question: "What is Relevance Feedback?", answer: "Yes sir, Relevance Feedback is an interactive process where the system retrieves initial results, the user marks some as relevant or irrelevant, and the system uses this feedback to refine the query and fetch better results." },
      { question: "What is Query Expansion?", answer: "Sir, Query Expansion involves adding synonyms or related terms to a user's original query to increase recall. It can be done automatically using a thesaurus or through relevance feedback." },
      { question: "What is the Rocchio Algorithm?", answer: "Sir, the Rocchio Algorithm is a classic method for implementing relevance feedback. It modifies the original query vector by moving it closer to the centroid of relevant documents and further away from non-relevant ones." },
      { question: "What is a Bag of Words model?", answer: "Sir, a Bag of Words model ignores grammar and word order, representing text merely as a multi-set of its words and their frequencies." },
      { question: "How do you calculate IDF?", answer: "Sir, IDF is calculated as the logarithm of the total number of documents divided by the number of documents that contain the specific term." },
      { question: "What happens to the cosine similarity if two vectors are orthogonal (perpendicular)?", answer: "Sir, if two vectors are orthogonal, they share no common terms, and their cosine similarity score is zero." },
      { question: "Why is TF-IDF favored over simple Boolean retrieval?", answer: "Yes sir, TF-IDF is favored because it allows for partial matching and provides a ranked list of results based on relevance, unlike the binary 'yes/no' retrieval of the Boolean model." },
      { question: "What is term frequency saturation in BM25?", answer: "Sir, term frequency saturation means that as a term appears more times in a document, its weight increases, but this increase slows down and flattens out to prevent extreme repetition from dominating the score." }
    ],
    mcqs: [
      { question: "Which model represents queries and documents as vectors?", options: ["Boolean Model", "Vector Space Model", "Probabilistic Model", "Language Model"], correctAnswer: "Vector Space Model" },
      { question: "TF-IDF stands for:", options: ["Term Frequency-Inverse Document Frequency", "Text Formatting-Index Data Format", "Term Function-Inverted Document File", "Total Frequency-Index Document Frequency"], correctAnswer: "Term Frequency-Inverse Document Frequency" },
      { question: "In Cosine Similarity, an angle of 0 degrees between vectors means:", options: ["No similarity", "Complete mismatch", "Perfect similarity (score 1)", "Orthogonal documents"], correctAnswer: "Perfect similarity (score 1)" },
      { question: "Which matrix factorization technique is used in Latent Semantic Indexing (LSI)?", options: ["PCA", "SVD (Singular Value Decomposition)", "K-means", "Eigen Decomposition"], correctAnswer: "SVD (Singular Value Decomposition)" },
      { question: "Which algorithm is widely used for relevance feedback?", options: ["Dijkstra's", "PageRank", "Rocchio", "K-Means"], correctAnswer: "Rocchio" },
      { question: "Okapi BM25 improves upon standard TF-IDF by explicitly accounting for:", options: ["Images in documents", "Document length and TF saturation", "Hyperlinks", "HTML tags"], correctAnswer: "Document length and TF saturation" },
      { question: "Query expansion is primarily aimed at improving:", options: ["Precision", "Recall", "Compression ratio", "Index building time"], correctAnswer: "Recall" },
      { question: "IDF assigns higher weight to terms that are:", options: ["Frequent in a document", "Rare across the whole corpus", "Stop words", "Found in the query"], correctAnswer: "Rare across the whole corpus" },
      { question: "What does the Language Modeling approach compute?", options: ["Cosine angle", "Probability that the document model generates the query", "SVD matrix", "Boolean intersections"], correctAnswer: "Probability that the document model generates the query" },
      { question: "In the Rocchio algorithm, the query is moved towards the centroid of:", options: ["All documents", "Irrelevant documents", "Relevant documents", "The lexicon"], correctAnswer: "Relevant documents" },
      { question: "Cosine similarity compensates for:", options: ["Synonyms", "Polysemy", "Document length", "Stop words"], correctAnswer: "Document length" },
      { question: "LSI is particularly effective at resolving issues related to:", options: ["Synonymy", "Spelling errors", "Boolean logic", "Network latency"], correctAnswer: "Synonymy" },
      { question: "A document containing the query word 100 times compared to 10 times:", options: ["Is 10 times more relevant in TF-IDF", "Has diminishing returns due to log scaling", "Is less relevant", "Is rejected as spam"], correctAnswer: "Has diminishing returns due to log scaling" },
      { question: "Adding terms from a thesaurus to the user's search is called:", options: ["Query expansion", "Stemming", "Relevance feedback", "Tokenization"], correctAnswer: "Query expansion" },
      { question: "The problem of one word having multiple meanings is called:", options: ["Synonymy", "Polysemy", "Homophony", "Stemming"], correctAnswer: "Polysemy" },
      { question: "Which of the following is a ranked retrieval model?", options: ["Boolean model", "Vector Space Model", "Unigram model", "Set theory"], correctAnswer: "Vector Space Model" },
      { question: "Relevance feedback can be explicitly gathered from:", options: ["User clicks/ratings", "Hyperlinks", "Zipf's law", "The compiler"], correctAnswer: "User clicks/ratings" },
      { question: "If a term appears in every document in the corpus, its IDF value will be:", options: ["1", "Infinite", "0", "Negative"], correctAnswer: "0" },
      { question: "Which formula adjusts scores so long documents don't naturally dominate?", options: ["TF-IDF", "Rocchio", "Document length normalization", "SVD"], correctAnswer: "Document length normalization" },
      { question: "The probability ranking principle is the basis for which model?", options: ["Vector Space Model", "Probabilistic Retrieval Model", "Boolean Model", "LSI"], correctAnswer: "Probabilistic Retrieval Model" }
    ]
  },
  {
    chapterTitle: "Performance Evaluation",
    vivaQuestions: [
      { question: "Why is Performance Evaluation important in IR?", answer: "Yes sir, it is important to quantitatively measure how well a search engine is fulfilling the user's information need, allowing developers to tune algorithms and compare different retrieval models." },
      { question: "What is Precision?", answer: "Sir, Precision is the fraction of the retrieved documents that are actually relevant to the user's query. It measures the exactness or quality of the results." },
      { question: "What is Recall?", answer: "Sir, Recall is the fraction of all the relevant documents in the entire collection that were successfully retrieved. It measures the completeness of the results." },
      { question: "Can you explain the trade-off between Precision and Recall?", answer: "Yes sir. Usually, as you retrieve more documents, Recall increases because you find more relevant ones, but Precision drops because you also start including more irrelevant documents." },
      { question: "What is the F-measure?", answer: "Sir, the F-measure, or F1 score, is the harmonic mean of Precision and Recall. It provides a single metric that balances both exactness and completeness." },
      { question: "Why use the harmonic mean for F-measure instead of arithmetic mean?", answer: "Sir, the harmonic mean penalizes extreme values. If a system has 100% recall but 0% precision, the arithmetic mean would be 50%, which is misleading, while the harmonic mean would be 0%, accurately reflecting the failure." },
      { question: "How do we define User Happiness in IR?", answer: "Sir, User Happiness encompasses several factors including the relevance of search results, response time, UI design, and whether the system quickly satisfied their ultimate information need." },
      { question: "What components are needed to create a Test Collection?", answer: "Yes sir, a standard test collection requires three things: a document corpus, a set of standard user queries (information needs), and a set of relevance judgments (ground truth)." },
      { question: "What are Relevance Judgments?", answer: "Sir, they are manual assessments made by human experts indicating which documents in the collection are relevant to which specific queries, acting as the ground truth for evaluation." },
      { question: "What is the TREC collection?", answer: "Sir, TREC stands for Text REtrieval Conference, co-sponsored by NIST. It provides massive, standardized test collections for researchers to evaluate their IR systems on a level playing field." },
      { question: "What is Interjudge Agreement?", answer: "Sir, it measures how often human assessors agree on whether a document is relevant to a query. High agreement means the task is well-defined, while low agreement implies ambiguity." },
      { question: "What is the Kappa measure?", answer: "Yes sir, the Kappa statistic is a mathematical metric used to calculate interjudge agreement, correcting for the probability that the judges might agree simply by chance." },
      { question: "What is Mean Average Precision (MAP)?", answer: "Sir, MAP is a popular metric that computes the average precision across multiple queries. It considers the rank of relevant documents, rewarding systems that place relevant documents at the top." },
      { question: "What is Precision at k (P@k)?", answer: "Sir, Precision at k measures the precision calculated considering only the top 'k' retrieved documents, which is very useful for web search where users rarely look past the first page." },
      { question: "What is Discounted Cumulative Gain (DCG)?", answer: "Sir, DCG is a metric that evaluates ranked result lists. It relies on graded relevance (e.g., highly relevant, somewhat relevant) and penalizes relevant documents that appear lower in the list using a logarithmic discount." },
      { question: "What is a False Positive in IR?", answer: "Sir, a false positive occurs when the system retrieves a document claiming it is relevant, but it is actually irrelevant." },
      { question: "What is a False Negative in IR?", answer: "Sir, a false negative is when a document is actually relevant to the query, but the search system fails to retrieve it." },
      { question: "What is A/B testing in search engines?", answer: "Yes sir, A/B testing is testing two versions of a search algorithm simultaneously on live users to see which one yields better user happiness metrics, like higher click-through rates." },
      { question: "Why is evaluating web search engines difficult?", answer: "Sir, it is difficult because the web corpus is constantly changing, queries are vast and unpredictable, and assessing absolute recall is impossible since we can't judge the entire web." },
      { question: "What does an F-measure of 1 indicate?", answer: "Sir, an F-measure of 1 is the perfect score, indicating that the system achieved 100% precision and 100% recall." }
    ],
    mcqs: [
      { question: "The fraction of retrieved documents that are relevant is:", options: ["Recall", "Precision", "F-measure", "Accuracy"], correctAnswer: "Precision" },
      { question: "The fraction of relevant documents that are successfully retrieved is:", options: ["Recall", "Precision", "F-measure", "Kappa"], correctAnswer: "Recall" },
      { question: "Which metric is the harmonic mean of Precision and Recall?", options: ["MAP", "F-measure", "DCG", "Kappa"], correctAnswer: "F-measure" },
      { question: "Which statistic measures agreement between human judges correcting for chance?", options: ["F1-score", "Kappa measure", "Recall", "R-squared"], correctAnswer: "Kappa measure" },
      { question: "TREC is widely known for providing:", options: ["Search algorithms", "Standardized test collections", "Hardware", "Web browsers"], correctAnswer: "Standardized test collections" },
      { question: "Which metric heavily rewards ranking relevant documents at the very top?", options: ["Mean Average Precision (MAP)", "Recall", "Document size", "Total hits"], correctAnswer: "Mean Average Precision (MAP)" },
      { question: "If a system retrieves 0 irrelevant documents but misses many relevant ones, it has:", options: ["High precision, low recall", "Low precision, high recall", "High precision, high recall", "Low precision, low recall"], correctAnswer: "High precision, low recall" },
      { question: "Precision at k (P@k) evaluates:", options: ["The first k queries", "The top k retrieved documents", "The k-th document only", "The bottom k documents"], correctAnswer: "The top k retrieved documents" },
      { question: "Discounted Cumulative Gain (DCG) is useful because it handles:", options: ["Boolean logic", "Graded relevance (e.g. scores 0-3)", "Stemming errors", "Images"], correctAnswer: "Graded relevance (e.g. scores 0-3)" },
      { question: "A retrieved document that is actually irrelevant is a:", options: ["True positive", "False positive", "True negative", "False negative"], correctAnswer: "False positive" },
      { question: "What is necessary to calculate Recall?", options: ["Knowing the total number of relevant documents in the corpus", "Knowing the user's password", "Having a fast processor", "Using Google"], correctAnswer: "Knowing the total number of relevant documents in the corpus" },
      { question: "Why use harmonic mean for F-measure?", options: ["It's easier to calculate", "It penalizes unbalanced values of precision and recall", "It maximizes the score", "It ignores recall"], correctAnswer: "It penalizes unbalanced values of precision and recall" },
      { question: "A ground truth set of relevance judgments is created by:", options: ["Algorithms", "Human experts (assessors)", "Web crawlers", "Compilers"], correctAnswer: "Human experts (assessors)" },
      { question: "In A/B testing, evaluating 'User Happiness' often relies on:", options: ["Click-through rates", "TF-IDF scores", "Stemming accuracy", "Corpus size"], correctAnswer: "Click-through rates" },
      { question: "If an IR system returns all documents in the collection, what is its recall?", options: ["0%", "50%", "100%", "Undefined"], correctAnswer: "100%" },
      { question: "If an IR system returns all documents in the collection, its precision will likely be:", options: ["Very high", "Very low", "100%", "Negative"], correctAnswer: "Very low" },
      { question: "The Kappa measure value of 1 indicates:", options: ["No agreement", "Random agreement", "Perfect agreement among judges", "Negative agreement"], correctAnswer: "Perfect agreement among judges" },
      { question: "The trade-off curve between precision and recall generally slopes:", options: ["Upwards", "Downwards", "Stays flat", "Is a perfect circle"], correctAnswer: "Downwards" },
      { question: "Test collections are static, meaning:", options: ["The corpus and queries don't change during evaluation", "They run on RAM", "They update in real-time", "They are dynamically generated"], correctAnswer: "The corpus and queries don't change during evaluation" },
      { question: "Which of the following is NOT required for a standard IR test collection?", options: ["Document collection", "Relevance judgments", "Information needs/Queries", "A live web crawler"], correctAnswer: "A live web crawler" }
    ]
  },
  {
    chapterTitle: "Text Categorization and Filtering",
    vivaQuestions: [
      { question: "What is Text Classification or Categorization?", answer: "Yes sir, text classification is the automated process of assigning predefined tags or categories to text documents based on their content." },
      { question: "How does classification differ from clustering?", answer: "Sir, classification is supervised learning where the categories are predefined and training data is labeled, whereas clustering is unsupervised learning where the system finds natural groupings without predefined labels." },
      { question: "What is Spam Filtering?", answer: "Sir, spam filtering is a classic text classification problem where emails or messages are automatically categorized into two classes: 'spam' (junk) or 'ham' (legitimate)." },
      { question: "What is the Naive Bayes classifier?", answer: "Yes sir, Naive Bayes is a probabilistic classifier based on Bayes' Theorem. It calculates the probability of a document belonging to a category based on the frequencies of the words it contains." },
      { question: "Why is the Naive Bayes algorithm called 'Naive'?", answer: "Sir, it is called 'naive' because it makes the strong, unrealistic assumption that the occurrence of each word in a document is independent of the occurrence of all other words." },
      { question: "What is Vector Space Classification?", answer: "Sir, it involves representing documents as vectors in a space and assigning categories based on geometric boundaries, like hyperplanes, separating different classes." },
      { question: "What is a Centroid in classification?", answer: "Sir, a centroid is the average or center of mass of all the document vectors belonging to a specific class. In centroid-based classification, a new document is assigned to the class with the closest centroid." },
      { question: "What is the k Nearest Neighbors (kNN) classifier?", answer: "Yes sir, kNN is a lazy learning algorithm. It classifies a new document by finding the 'k' most similar training documents in the vector space and assigning the majority class among those neighbors." },
      { question: "Why is kNN called a 'lazy' learner?", answer: "Sir, it is called lazy because it doesn't build an explicit model during the training phase; it simply stores the training data and performs all the heavy computation during the classification phase." },
      { question: "What is a Support Vector Machine (SVM)?", answer: "Sir, SVM is a highly powerful classification algorithm that finds the optimal hyperplane that separates document vectors of different classes with the maximum possible margin." },
      { question: "What is the margin in SVM?", answer: "Yes sir, the margin is the distance between the separating hyperplane and the closest data points from each class. SVM aims to maximize this margin to improve generalization." },
      { question: "What are Support Vectors?", answer: "Sir, support vectors are the specific training data points that lie closest to the decision hyperplane. They are the critical elements that dictate the position of the hyperplane." },
      { question: "What is a Kernel Function in SVM?", answer: "Sir, a kernel function is a mathematical trick that maps data into a higher-dimensional space. This allows SVM to find a linear hyperplane for data that is not linearly separable in its original space." },
      { question: "Can you name a common Kernel function?", answer: "Yes sir, common kernel functions include the Polynomial kernel and the Radial Basis Function (RBF) kernel." },
      { question: "What is Boosting?", answer: "Sir, boosting is an ensemble machine learning meta-algorithm. It works by combining many weak classifiers into a single strong classifier, focusing iteratively on the data points that were misclassified in previous rounds." },
      { question: "What is feature selection in text categorization?", answer: "Sir, feature selection is the process of choosing the most relevant words or features to use in the classifier, removing noisy or irrelevant words to improve accuracy and speed." },
      { question: "What is a training set?", answer: "Sir, a training set is a collection of documents that have been manually labeled with correct categories, used to train the classification algorithm." },
      { question: "What is a test set in classification?", answer: "Yes sir, a test set is a separate collection of labeled documents withheld during training, used exclusively to evaluate the accuracy of the trained model." },
      { question: "What happens if 'k' is too small in kNN?", answer: "Sir, if 'k' is very small, like k=1, the model becomes highly sensitive to noise and outliers, leading to overfitting." },
      { question: "How does Naive Bayes handle words it hasn't seen in training?", answer: "Sir, it uses a technique called Laplace smoothing (or add-one smoothing) to give unseen words a small non-zero probability, preventing the entire document probability from becoming zero." }
    ],
    mcqs: [
      { question: "Text classification is an example of:", options: ["Unsupervised learning", "Supervised learning", "Reinforcement learning", "Clustering"], correctAnswer: "Supervised learning" },
      { question: "Which algorithm relies on Bayes' Theorem?", options: ["SVM", "kNN", "Naive Bayes", "K-Means"], correctAnswer: "Naive Bayes" },
      { question: "The 'naive' assumption in Naive Bayes is:", options: ["Classes are equal", "Features (words) are conditionally independent", "Vectors are orthogonal", "All documents are relevant"], correctAnswer: "Features (words) are conditionally independent" },
      { question: "Which classifier finds a hyperplane that maximizes the margin?", options: ["Naive Bayes", "Centroid classifier", "Support Vector Machine (SVM)", "kNN"], correctAnswer: "Support Vector Machine (SVM)" },
      { question: "In SVM, the data points closest to the hyperplane are called:", options: ["Centroids", "Support vectors", "Neighbors", "Outliers"], correctAnswer: "Support vectors" },
      { question: "Which function maps non-linear data into a higher dimensional space in SVM?", options: ["Hash function", "Kernel function", "Sigmoid function", "Loss function"], correctAnswer: "Kernel function" },
      { question: "In kNN, a new document is assigned the class of its:", options: ["Furthest neighbor", "Majority class among 'k' nearest neighbors", "Centroid", "Support vector"], correctAnswer: "Majority class among 'k' nearest neighbors" },
      { question: "Which of the following is considered a 'lazy learner'?", options: ["kNN", "Naive Bayes", "SVM", "Decision Tree"], correctAnswer: "kNN" },
      { question: "Spam filtering is a primary application of:", options: ["Text Classification", "Web crawling", "PageRank", "Gap encoding"], correctAnswer: "Text Classification" },
      { question: "Boosting combines multiple:", options: ["Strong classifiers", "Weak classifiers", "Hyperplanes", "Centroids"], correctAnswer: "Weak classifiers" },
      { question: "The average vector of all documents in a class is called its:", options: ["Margin", "Support vector", "Centroid", "Prior probability"], correctAnswer: "Centroid" },
      { question: "To prevent zero probabilities for unseen words, Naive Bayes uses:", options: ["Boosting", "Laplace smoothing", "Margin maximization", "Stemming"], correctAnswer: "Laplace smoothing" },
      { question: "Which evaluation set is used to evaluate the final classifier?", options: ["Training set", "Validation set", "Test set", "Feature set"], correctAnswer: "Test set" },
      { question: "Polynomial and Radial Basis Function (RBF) are types of:", options: ["Kernel functions", "Distance metrics", "Clustering algorithms", "Stemmers"], correctAnswer: "Kernel functions" },
      { question: "In kNN, how is the distance between documents usually measured?", options: ["Euclidean or Cosine distance", "Bayes Theorem", "Laplace transform", "Zipf's law"], correctAnswer: "Euclidean or Cosine distance" },
      { question: "Which method adjusts weights of training instances that were misclassified?", options: ["kNN", "Boosting", "Centroid", "Naive Bayes"], correctAnswer: "Boosting" },
      { question: "Feature selection aims to:", options: ["Increase index size", "Remove noisy/irrelevant features", "Add random words", "Slow down training"], correctAnswer: "Remove noisy/irrelevant features" },
      { question: "SVM is primarily a:", options: ["Binary classifier", "Unsupervised clusterer", "Generative model", "Search engine"], correctAnswer: "Binary classifier" },
      { question: "If k=1 in k-Nearest Neighbors, the prediction is based on:", options: ["The average of all points", "The single closest training example", "A random point", "The centroid"], correctAnswer: "The single closest training example" },
      { question: "Vector space classification represents documents as:", options: ["Strings", "Points/Vectors in a multidimensional space", "Trees", "Graphs"], correctAnswer: "Points/Vectors in a multidimensional space" }
    ]
  },
  {
    chapterTitle: "Text Clustering",
    vivaQuestions: [
      { question: "What is Text Clustering?", answer: "Yes sir, text clustering is an unsupervised machine learning process that automatically groups a set of documents into clusters based on their similarities, without predefined categories." },
      { question: "What is the key difference between Clustering and Classification?", answer: "Sir, classification requires labeled training data and assigns documents to known categories. Clustering does not use labeled data; it discovers hidden structures and groups documents on its own." },
      { question: "What are Partitioning methods in clustering?", answer: "Sir, partitioning methods divide the dataset into a set of 'k' distinct, non-overlapping clusters simultaneously, where each document belongs to exactly one cluster." },
      { question: "Can you explain the k-means clustering algorithm?", answer: "Yes sir, k-means is a partitioning algorithm that initializes 'k' random centroids, assigns each document to the nearest centroid, recalculates the centroids based on the group, and repeats until the clusters stop changing." },
      { question: "What is the role of 'k' in k-means?", answer: "Sir, 'k' is a hyperparameter defined by the user that specifies the exact number of clusters the algorithm should create." },
      { question: "What is a major limitation of k-means clustering?", answer: "Sir, its limitations include the need to specify 'k' in advance, sensitivity to the initial random placement of centroids, and struggling with non-spherical clusters." },
      { question: "What is the Mixture of Gaussians model?", answer: "Yes sir, it is a probabilistic clustering model where it assumes that the data is generated from a mixture of several Gaussian distributions, allowing for soft assignments where a document has probabilities of belonging to multiple clusters." },
      { question: "What does Hierarchical Agglomerative Clustering (HAC) mean?", answer: "Sir, HAC is a bottom-up clustering approach. It starts by treating each document as its own cluster and repeatedly merges the two most similar clusters until all documents are in a single massive root cluster." },
      { question: "What is a dendrogram?", answer: "Sir, a dendrogram is a tree-like diagram that records the sequence of merges performed by hierarchical clustering, showing how clusters relate at different levels of granularity." },
      { question: "How do you define the similarity between two clusters in HAC?", answer: "Sir, we use linkage criteria. Single-linkage looks at the closest points between clusters, complete-linkage looks at the furthest points, and group-average linkage looks at the average similarity between all points." },
      { question: "What is Single-linkage clustering?", answer: "Yes sir, in single-linkage, the similarity between two clusters is defined by the similarity of their two most similar members (the closest points)." },
      { question: "What is Complete-linkage clustering?", answer: "Sir, in complete-linkage, the similarity is defined by the least similar members (the furthest points), which tends to produce tighter, spherical clusters." },
      { question: "What is meant by 'Clustering terms using documents'?", answer: "Sir, instead of grouping similar documents based on the words they contain, we can transpose the matrix to group similar words (terms) based on the documents they co-occur in, which is useful for building automatic thesauri." },
      { question: "Is clustering supervised or unsupervised?", answer: "Sir, clustering is strictly an unsupervised learning technique as it operates on unlabeled data." },
      { question: "How do we measure the quality of clusters?", answer: "Yes sir, we can measure it internally by calculating intra-cluster similarity (tightness) and inter-cluster distance (separation), or externally using metrics like Purity against known ground truth." },
      { question: "What is an objective function in clustering?", answer: "Sir, an objective function is a mathematical formula that the clustering algorithm tries to optimize, such as minimizing the sum of squared distances from points to their centroids in k-means." },
      { question: "Does hierarchical clustering require specifying the number of clusters 'k'?", answer: "No sir, it does not. You build the entire hierarchy first and can later 'cut' the dendrogram at any level to get the desired number of clusters." },
      { question: "What is soft clustering?", answer: "Sir, soft clustering assigns a document a probability or weight of belonging to each cluster, rather than a hard, absolute assignment to a single cluster, as seen in the Mixture of Gaussians model." },
      { question: "What is hard clustering?", answer: "Sir, in hard clustering, like standard k-means, every document belongs to exactly one cluster with 100% certainty." },
      { question: "Why is HAC computationally expensive?", answer: "Yes sir, HAC requires computing and constantly updating an N x N similarity matrix for all documents, making its time complexity O(N^3), which is too slow for massive datasets." }
    ],
    mcqs: [
      { question: "Clustering is a form of:", options: ["Supervised learning", "Unsupervised learning", "Reinforcement learning", "Boolean retrieval"], correctAnswer: "Unsupervised learning" },
      { question: "Which algorithm requires the number of clusters 'k' to be specified in advance?", options: ["Hierarchical Agglomerative", "k-means", "Single linkage", "Dendrogram"], correctAnswer: "k-means" },
      { question: "Hierarchical Agglomerative Clustering operates:", options: ["Top-down", "Bottom-up", "Randomly", "Linearly"], correctAnswer: "Bottom-up" },
      { question: "A tree diagram used to visualize hierarchical clustering is called a:", options: ["Histogram", "Scatter plot", "Dendrogram", "Pie chart"], correctAnswer: "Dendrogram" },
      { question: "In k-means, a point is assigned to the cluster with the closest:", options: ["Outlier", "Centroid", "Margin", "Hyperplane"], correctAnswer: "Centroid" },
      { question: "Which model allows 'soft' assignment of documents to clusters using probabilities?", options: ["k-means", "Mixture of Gaussians", "Complete linkage", "BSBI"], correctAnswer: "Mixture of Gaussians" },
      { question: "Defining cluster similarity based on the closest pair of points between them is:", options: ["Complete-linkage", "Single-linkage", "Average-linkage", "Centroid-linkage"], correctAnswer: "Single-linkage" },
      { question: "Defining cluster similarity based on the furthest pair of points is:", options: ["Single-linkage", "Complete-linkage", "K-means", "PageRank"], correctAnswer: "Complete-linkage" },
      { question: "Clustering differs from classification primarily because:", options: ["It uses vectors", "It operates on unlabeled data", "It is faster", "It uses Bayes theorem"], correctAnswer: "It operates on unlabeled data" },
      { question: "Which method divides the data into distinct, non-overlapping groups?", options: ["Partitioning methods", "Hierarchical methods", "Language modeling", "Zipf's law"], correctAnswer: "Partitioning methods" },
      { question: "In clustering, we desire:", options: ["Low intra-cluster similarity, High inter-cluster similarity", "High intra-cluster similarity, Low inter-cluster similarity", "Zero distance", "Random grouping"], correctAnswer: "High intra-cluster similarity, Low inter-cluster similarity" },
      { question: "Clustering terms (words) instead of documents is used for:", options: ["Compressing text", "Building an automatic thesaurus/concept groups", "Spam filtering", "Page ranking"], correctAnswer: "Building an automatic thesaurus/concept groups" },
      { question: "Which step is repeated iteratively in the k-means algorithm?", options: ["Cutting the dendrogram", "Recomputing centroids and reassigning points", "Maximizing the margin", "Stemming words"], correctAnswer: "Recomputing centroids and reassigning points" },
      { question: "A major drawback of standard k-means is:", options: ["It is unsupervised", "It is sensitive to initial random centroid placement", "It creates a dendrogram", "It takes O(N^3) time"], correctAnswer: "It is sensitive to initial random centroid placement" },
      { question: "Hierarchical Agglomerative clustering time complexity is typically:", options: ["O(N)", "O(log N)", "O(N^2) or O(N^3)", "O(1)"], correctAnswer: "O(N^2) or O(N^3)" },
      { question: "Hard clustering means:", options: ["The math is difficult", "Each document belongs to exactly one cluster", "Clusters overlap", "It requires labeled data"], correctAnswer: "Each document belongs to exactly one cluster" },
      { question: "Which clustering technique builds a hierarchy without needing 'k' initially?", options: ["Naive Bayes", "k-means", "Hierarchical Agglomerative", "Rocchio"], correctAnswer: "Hierarchical Agglomerative" },
      { question: "K-means tries to minimize the distance between points and their:", options: ["Nearest neighbor", "Cluster centroid", "The origin", "Support vector"], correctAnswer: "Cluster centroid" },
      { question: "In a dendrogram, the y-axis typically represents:", options: ["Time", "Similarity/Distance level at which merges occurred", "Document ID", "Term frequency"], correctAnswer: "Similarity/Distance level at which merges occurred" },
      { question: "Gaussian Mixture Models rely heavily on which algorithm for parameter estimation?", options: ["Dijkstra's", "Expectation-Maximization (EM)", "Binary Search", "Quick Sort"], correctAnswer: "Expectation-Maximization (EM)" }
    ]
  },
  {
    chapterTitle: "Advanced Topics",
    vivaQuestions: [
      { question: "What is Text Summarization?", answer: "Yes sir, text summarization is the process of generating a concise and meaningful summary of text from multiple documents or a single document while preserving the key information." },
      { question: "What is Extractive Summarization?", answer: "Sir, extractive summarization works by identifying and copying the most important existing sentences directly from the original text to form a summary." },
      { question: "What is Abstractive Summarization?", answer: "Sir, abstractive summarization uses natural language processing to generate entirely new sentences that convey the main ideas, similar to how a human would write a summary." },
      { question: "What is Topic Detection and Tracking (TDT)?", answer: "Yes sir, TDT is a field of research focused on finding and following new events or topics in a stream of broadcast news or text data over time." },
      { question: "What is Personalization in IR?", answer: "Sir, personalization modifies search results based on an individual user's historical data, location, and preferences, ensuring different users searching the same query get results tailored to them." },
      { question: "How does a system achieve Personalization?", answer: "Sir, it collects user context through implicit feedback like past search queries, click history, and browsing behavior, building a user profile to re-rank results." },
      { question: "What is Question Answering (QA) in IR?", answer: "Yes sir, unlike standard search that returns documents, QA systems aim to return a precise, direct answer (like a specific fact or sentence) to a query posed in natural language." },
      { question: "What are the main steps in a Question Answering system?", answer: "Sir, the main steps are Question Processing to identify what is being asked, Document Retrieval to find relevant texts, and Answer Extraction to pull out the exact fact." },
      { question: "What is Cross-Language Information Retrieval (CLIR)?", answer: "Sir, CLIR allows a user to query an IR system in one language (e.g., English) and retrieve relevant documents that are written in a different language (e.g., French)." },
      { question: "How is CLIR generally implemented?", answer: "Yes sir, it is usually implemented by translating the user's query into the document's language using bilingual dictionaries or machine translation, and then performing the search." },
      { question: "What is a 'First Story Detection' in TDT?", answer: "Sir, it is a sub-task of Topic Detection and Tracking where the system must identify if a news article discusses a completely novel, unseen event." },
      { question: "Why is abstractive summarization harder than extractive?", answer: "Sir, it is harder because it requires deep semantic understanding of the text, language generation capabilities, and grammatical restructuring, not just statistical sentence scoring." },
      { question: "What is collaborative filtering in personalization?", answer: "Sir, it is recommending items or ranking results based on the preferences of similar users in the system." },
      { question: "What is content-based filtering?", answer: "Sir, it recommends items based on comparing the content of the items to a profile of the user's past interests." },
      { question: "What is Factoid Question Answering?", answer: "Yes sir, it is a QA system designed to answer questions that require short, factual answers like names, dates, or places (e.g., 'Who is the CEO of Google?')." },
      { question: "What is the role of Named Entity Recognition (NER) in QA?", answer: "Sir, NER is crucial in QA to identify entities like persons, locations, and organizations in the text, which are very often the answers to factoid questions." },
      { question: "What is the challenge of translating queries in CLIR?", answer: "Sir, queries are short and lack context, making translation difficult due to ambiguity and polysemy. The system might translate a word incorrectly without context." },
      { question: "What is single-document vs multi-document summarization?", answer: "Sir, single-document summarizes one text, whereas multi-document takes a cluster of related articles on the same topic and generates a single comprehensive summary, managing redundancy." },
      { question: "How does TF-IDF help in extractive summarization?", answer: "Yes sir, sentences containing words with high TF-IDF scores are considered highly informative and are typically selected for the extractive summary." },
      { question: "What is implicit vs explicit feedback for personalization?", answer: "Sir, explicit feedback is when a user directly rates an item, while implicit feedback infers preference from user actions like clicking, dwelling on a page, or scrolling." }
    ],
    mcqs: [
      { question: "Which summarization type creates new sentences not found in the original text?", options: ["Extractive", "Abstractive", "Boolean", "Predictive"], correctAnswer: "Abstractive" },
      { question: "Which summarization type copies important sentences directly?", options: ["Abstractive", "Generative", "Extractive", "Clustering"], correctAnswer: "Extractive" },
      { question: "TDT stands for:", options: ["Text Data Transfer", "Topic Detection and Tracking", "Term Document Tracking", "Topic Data Type"], correctAnswer: "Topic Detection and Tracking" },
      { question: "Returning a specific, short fact instead of a document is the goal of:", options: ["Question Answering", "Personalization", "Stemming", "Tokenization"], correctAnswer: "Question Answering" },
      { question: "Searching in English and getting documents in Japanese is called:", options: ["Topic tracking", "Cross Language Information Retrieval (CLIR)", "Abstractive summarization", "Positional indexing"], correctAnswer: "Cross Language Information Retrieval (CLIR)" },
      { question: "Tailoring search results based on a user's past clicks and location is:", options: ["Standardization", "Personalization", "Generalization", "Clustering"], correctAnswer: "Personalization" },
      { question: "A QA system identifying names, dates, and locations relies heavily on:", options: ["NER (Named Entity Recognition)", "Gap encoding", "Hyperjacking", "Gamma codes"], correctAnswer: "NER (Named Entity Recognition)" },
      { question: "First Story Detection is a task within:", options: ["Summarization", "Topic Detection and Tracking", "Spam Filtering", "CLIR"], correctAnswer: "Topic Detection and Tracking" },
      { question: "Using bilingual dictionaries to translate a query is standard in:", options: ["TDT", "QA", "CLIR", "HAC"], correctAnswer: "CLIR" },
      { question: "Questions like 'When was Einstein born?' are known as:", options: ["Factoid questions", "Boolean questions", "Abstract questions", "Extractive questions"], correctAnswer: "Factoid questions" },
      { question: "Monitoring a news stream to track a specific ongoing event is:", options: ["Personalization", "Topic Tracking", "Stemming", "Link analysis"], correctAnswer: "Topic Tracking" },
      { question: "Inferring user preference from their search history is an example of:", options: ["Explicit feedback", "Implicit feedback", "Supervised training", "Abstractive feedback"], correctAnswer: "Implicit feedback" },
      { question: "Redundancy is a major challenge in which specific task?", options: ["Single-document summarization", "Multi-document summarization", "Boolean AND queries", "Stop word removal"], correctAnswer: "Multi-document summarization" },
      { question: "Which type of summarization is generally easier for a computer to perform?", options: ["Abstractive", "Extractive", "Both are equally easy", "Neither"], correctAnswer: "Extractive" },
      { question: "Recommending results based on what similar users liked is:", options: ["Content-based filtering", "Collaborative filtering", "TDT", "CLIR"], correctAnswer: "Collaborative filtering" },
      { question: "The ambiguity of short queries makes which process difficult?", options: ["Document retrieval", "Query translation in CLIR", "Index compression", "Gap encoding"], correctAnswer: "Query translation in CLIR" },
      { question: "Which step in QA analyzes the grammar and intent of the user's input?", options: ["Answer extraction", "Document retrieval", "Question processing", "Feedback looping"], correctAnswer: "Question processing" },
      { question: "Personalization aims to increase which evaluation metric for the specific user?", options: ["Index size", "User Happiness / Relevance", "Hardware cost", "Zipf's constant"], correctAnswer: "User Happiness / Relevance" },
      { question: "Which technique is vital for finding the exact sentence containing an answer?", options: ["Passage retrieval", "Web crawling", "Image processing", "Gap encoding"], correctAnswer: "Passage retrieval" },
      { question: "Abstractive summarization relies heavily on:", options: ["Simple counting", "Natural Language Generation (NLG)", "Boolean logic", "Stemming alone"], correctAnswer: "Natural Language Generation (NLG)" }
    ]
  },
  {
    chapterTitle: "Web Information Retrieval",
    vivaQuestions: [
      { question: "What is Web Information Retrieval?", answer: "Yes sir, it is the application of Information Retrieval techniques specifically tailored to the massive, dynamic, and hyperlinked environment of the World Wide Web." },
      { question: "How is the Web different from a standard document corpus?", answer: "Sir, the web is massive, constantly changing, contains varying degrees of quality including spam, and documents are interconnected via hyperlinks, which provide valuable ranking signals." },
      { question: "What is a Web Crawler (or Spider)?", answer: "Yes sir, a web crawler is an automated program that navigates the web by downloading a web page, extracting its hyperlinks, and recursively visiting those new links to build an index." },
      { question: "What is the Crawler Frontier?", answer: "Sir, the frontier is the data structure (usually a queue) within a crawler that holds the list of unvisited URLs waiting to be fetched." },
      { question: "What is robots.txt?", answer: "Sir, robots.txt is a standard file on websites that tells web crawlers which pages they are allowed or forbidden to crawl, helping to respect the site's bandwidth and privacy." },
      { question: "What is Link Analysis?", answer: "Yes sir, link analysis evaluates the hyperlinks between web pages to determine their importance or authority, assuming a link from page A to page B is a 'vote' for page B." },
      { question: "What is the PageRank algorithm?", answer: "Sir, PageRank is a link analysis algorithm used by Google. It assigns a numerical weighting to each webpage based on the quantity and quality of incoming links to measure its relative importance." },
      { question: "How does the 'Random Surfer' model explain PageRank?", answer: "Sir, the random surfer model imagines a person randomly clicking links on the web. PageRank is the mathematical probability that the surfer ends up on a specific page at any given time." },
      { question: "What is a 'dead end' in PageRank?", answer: "Sir, a dead end is a webpage that has incoming links but no outgoing links, causing the random surfer to get stuck and the probability score to pool unproductively." },
      { question: "What is a 'spider trap'?", answer: "Sir, a spider trap is a set of web pages that link exclusively to each other. Crawlers can get stuck in infinite loops, and PageRank can get trapped, breaking the calculations." },
      { question: "How does PageRank solve dead ends and spider traps?", answer: "Yes sir, it solves them using a 'teleportation' or 'damping' factor, usually set to 0.85, which means 15% of the time the surfer gets bored and randomly jumps to any other page on the web." },
      { question: "What is HITS algorithm?", answer: "Sir, HITS stands for Hypertext-Induced Topic Search. It evaluates pages in two roles: as 'Hubs' (pages that link to good authorities) and 'Authorities' (pages linked to by good hubs)." },
      { question: "What is the difference between PageRank and HITS?", answer: "Sir, PageRank calculates a single global importance score for a page regardless of the query, while HITS computes query-specific scores dynamically, assigning both a hub and an authority score." },
      { question: "What is anchor text?", answer: "Sir, anchor text is the clickable text in a hyperlink. Search engines index anchor text heavily because it often provides an accurate, brief description of the target page." },
      { question: "What is Search Engine Optimization (SEO)?", answer: "Yes sir, SEO is the process of improving a website's content and structure to increase its visibility and ranking on search engine result pages." },
      { question: "What is Web Spam?", answer: "Sir, web spam consists of deceptive techniques used to manipulate search engine rankings, like keyword stuffing or buying massive amounts of fake incoming links (link spam)." },
      { question: "What is a seed URL in crawling?", answer: "Sir, seed URLs are the initial set of high-quality starting points given to a web crawler to begin its journey across the web." },
      { question: "What is politeness in web crawling?", answer: "Sir, politeness policies dictate that a crawler should not request pages from a single server too rapidly, spacing out requests to avoid crashing the target website." },
      { question: "What does an Authority page signify in HITS?", answer: "Sir, an Authority page is a web page that contains highly relevant, definitive information on a topic, usually receiving incoming links from many Hub pages." },
      { question: "Why is web IR more challenging than standard text IR?", answer: "Sir, because the web is decentralized, documents are highly unstructured, there is a massive scale of data, and adversarial users actively try to manipulate the ranking system." }
    ],
    mcqs: [
      { question: "Which algorithm computes a global importance score based on incoming links?", options: ["HITS", "PageRank", "Rocchio", "k-means"], correctAnswer: "PageRank" },
      { question: "The list of URLs waiting to be crawled is called the:", options: ["Lexicon", "Frontier", "Index", "Centroid"], correctAnswer: "Frontier" },
      { question: "Which file dictates crawling permissions for a website?", options: ["index.html", "robots.txt", "config.xml", "sitemap.xml"], correctAnswer: "robots.txt" },
      { question: "In the HITS algorithm, a page that links to many highly relevant pages is a:", options: ["Authority", "Hub", "Node", "Seed"], correctAnswer: "Hub" },
      { question: "In HITS, a page containing definitive information on a topic is an:", options: ["Authority", "Hub", "Frontier", "Spider"], correctAnswer: "Authority" },
      { question: "The concept that a user might jump to a random web page instead of following a link is called:", options: ["Stemming", "Teleportation / Damping factor", "Crawling", "Indexing"], correctAnswer: "Teleportation / Damping factor" },
      { question: "A web page with no outgoing links is called a:", options: ["Hub", "Seed", "Dead end", "Spider trap"], correctAnswer: "Dead end" },
      { question: "The clickable text in a hyperlink is called:", options: ["Hypertext", "Anchor text", "Alt text", "Metadata"], correctAnswer: "Anchor text" },
      { question: "Which algorithm computes scores specific to the user's query dynamically?", options: ["PageRank", "HITS", "Naive Bayes", "Gap encoding"], correctAnswer: "HITS" },
      { question: "The starting URLs given to a web crawler are called:", options: ["Roots", "Seeds", "Nodes", "Hubs"], correctAnswer: "Seeds" },
      { question: "A crawler avoiding hitting a server too frequently is practicing:", options: ["Stemming", "Politeness", "Teleportation", "SEO"], correctAnswer: "Politeness" },
      { question: "Creating fake link networks to manipulate PageRank is known as:", options: ["Link spam", "Content spam", "Hubbing", "Teleporting"], correctAnswer: "Link spam" },
      { question: "The 'Random Surfer' model is the theoretical foundation of:", options: ["HITS", "PageRank", "SVM", "Vector Space Model"], correctAnswer: "PageRank" },
      { question: "Which link is considered a 'vote' for a page's quality?", options: ["Outgoing link", "Incoming link", "Broken link", "Internal link"], correctAnswer: "Incoming link" },
      { question: "PageRank computation is essentially solving for the principal eigenvector of the:", options: ["Term-document matrix", "Link adjacency matrix", "Distance matrix", "Covariance matrix"], correctAnswer: "Link adjacency matrix" },
      { question: "A group of pages that only link to each other, trapping crawlers, is a:", options: ["Dead end", "Spider trap", "Hub network", "Frontier"], correctAnswer: "Spider trap" },
      { question: "Unlike standard text IR, Web IR must aggressively handle:", options: ["Adversarial spam", "Small document sizes", "Perfectly formatted text", "Static documents"], correctAnswer: "Adversarial spam" },
      { question: "What is typically NOT a function of a web crawler?", options: ["Fetching pages", "Extracting links", "Rendering 3D graphics", "Adding links to frontier"], correctAnswer: "Rendering 3D graphics" },
      { question: "In HITS, a good hub points to:", options: ["Many good hubs", "Many good authorities", "Dead ends", "The frontier"], correctAnswer: "Many good authorities" },
      { question: "PageRank scores across the entire web mathematically sum to:", options: ["0", "1", "Infinity", "Depends on the query"], correctAnswer: "1" }
    ]
  },
  {
    chapterTitle: "Retrieving Structured Documents",
    vivaQuestions: [
      { question: "What is meant by Retrieving Structured Documents?", answer: "Yes sir, it means performing search on documents that have explicit structural markup, like XML, allowing users to query both the text content and the structural hierarchy." },
      { question: "What is XML?", answer: "Sir, XML stands for eXtensible Markup Language. It is a flexible, tree-structured text format used to define data structures and store data with custom tags." },
      { question: "How does XML retrieval differ from standard text retrieval?", answer: "Sir, in standard text retrieval we search for keywords across the whole document. In XML retrieval, we can restrict searches to specific elements, like searching for a word only inside the `<title>` or `<author>` tags." },
      { question: "What is a Content-Only (CO) query in XML retrieval?", answer: "Sir, a Content-Only query is a standard keyword search that ignores the XML structure and just looks for the presence of words anywhere in the document." },
      { question: "What is a Content-And-Structure (CAS) query?", answer: "Yes sir, a CAS query specifies both the content to find and the specific XML structural element it must be found within, like: find 'Hamlet' only inside the `<play_title>` tag." },
      { question: "What is the Semantic Web?", answer: "Sir, the Semantic Web is an extension of the World Wide Web set by the W3C. Its goal is to make web data machine-readable, linking data in a way that software agents can understand the meaning and context." },
      { question: "What is RDF in the Semantic Web?", answer: "Sir, RDF stands for Resource Description Framework. It is a standard for modeling web data as 'triples' comprising a subject, a predicate, and an object, forming a network of relationships." },
      { question: "What is an Ontology in the context of the Semantic Web?", answer: "Yes sir, an ontology is a formal vocabulary that defines concepts and the relationships between them in a specific domain, allowing machines to infer knowledge." },
      { question: "How is XML structured conceptually?", answer: "Sir, an XML document is structured as a hierarchical tree of nodes, where there is a single root node and nested child nodes defined by tags." },
      { question: "What is the challenge of granularity in XML retrieval?", answer: "Sir, the challenge is deciding which level of the tree to return to the user. If they search for a word, should the system return the specific paragraph node, the section node, or the whole document node?" },
      { question: "What is NEXI?", answer: "Sir, NEXI stands for Narrowed Extended XPath I. It is a popular query language designed specifically for XML information retrieval, allowing CAS queries." },
      { question: "Why is standard XPath not enough for XML Information Retrieval?", answer: "Sir, standard XPath does exact matching of strings and structure, returning Boolean true/false. IR requires ranked retrieval and partial matching based on relevance." },
      { question: "What is the role of URIs in the Semantic Web?", answer: "Sir, Uniform Resource Identifiers (URIs) are used to uniquely identify resources, concepts, and relationships globally so data can be linked across different datasets." },
      { question: "What is SPARQL?", answer: "Yes sir, SPARQL is the standard query language for databases and data sources that store data in the RDF format on the Semantic Web." },
      { question: "What does 'machine-understandable' mean in the Semantic Web?", answer: "Sir, it means data is tagged with formal semantics (meaning) rather than just formatting (like HTML), allowing computer programs to logically process the information, not just display it." },
      { question: "How do you index XML documents?", answer: "Sir, indexing XML requires storing not just the terms, but the structural paths or element tags associated with those terms so that structural queries can be resolved." },
      { question: "What is an element in XML?", answer: "Sir, an XML element is everything from its starting tag to its ending tag, including text content, attributes, and any nested child elements." },
      { question: "How can Vector Space models be adapted for XML?", answer: "Yes sir, they can be adapted by treating distinct XML elements (like chapters or sections) as separate 'documents' in the index, or by incorporating structural weights into the term vectors." },
      { question: "What is Linked Data?", answer: "Sir, Linked Data refers to a set of best practices for publishing structured data on the web using URIs and RDF, so that it can be interlinked and become more useful." },
      { question: "What is the difference between HTML and XML?", answer: "Sir, HTML is designed to display data and focuses on how data looks. XML is designed to describe, store, and transport data, focusing on what data is." }
    ],
    mcqs: [
      { question: "XML documents are conceptually structured as a:", options: ["Flat file", "Tree", "Linear array", "Complete graph"], correctAnswer: "Tree" },
      { question: "A query that looks for keywords only inside specific tags is called:", options: ["Content-Only (CO) query", "Content-And-Structure (CAS) query", "Boolean query", "PageRank"], correctAnswer: "Content-And-Structure (CAS) query" },
      { question: "Which W3C standard is designed to make web data machine-understandable?", options: ["HTML5", "The Semantic Web", "TCP/IP", "CSS"], correctAnswer: "The Semantic Web" },
      { question: "The core data model of the Semantic Web based on 'triples' is:", options: ["XML", "HTML", "RDF", "JSON"], correctAnswer: "RDF" },
      { question: "An RDF triple consists of:", options: ["Root, Branch, Leaf", "Subject, Predicate, Object", "Class, Object, Method", "Query, Index, Document"], correctAnswer: "Subject, Predicate, Object" },
      { question: "Which language is specifically used to query RDF data?", options: ["SQL", "SPARQL", "C++", "HTML"], correctAnswer: "SPARQL" },
      { question: "A formal vocabulary defining concepts and relationships in a domain is an:", options: ["Index", "Ontology", "Lexicon", "Stemmer"], correctAnswer: "Ontology" },
      { question: "NEXI is a query language derived from XPath specifically for:", options: ["Relational databases", "XML Information Retrieval", "Image processing", "Web crawling"], correctAnswer: "XML Information Retrieval" },
      { question: "The problem of deciding whether to return a paragraph, section, or chapter in XML IR is known as:", options: ["Tokenization", "The Granularity problem", "Stemming", "Link analysis"], correctAnswer: "The Granularity problem" },
      { question: "Which identifier is heavily used in the Semantic Web to uniquely label resources?", options: ["ISBN", "URI", "MAC Address", "SSN"], correctAnswer: "URI" },
      { question: "HTML specifies how data looks, while XML specifies:", options: ["Network routes", "What data is (structure and meaning)", "CPU operations", "CSS styles"], correctAnswer: "What data is (structure and meaning)" },
      { question: "Searching for the word 'Apple' in the entire XML without caring about tags is a:", options: ["CAS Query", "Content-Only (CO) query", "SPARQL query", "Link query"], correctAnswer: "Content-Only (CO) query" },
      { question: "Unlike standard text IR, indexing XML requires storing:", options: ["Images", "Structural paths / Element tags", "Hyperlinks only", "CSS styles"], correctAnswer: "Structural paths / Element tags" },
      { question: "Standard XPath is not sufficient for IR because it:", options: ["Returns ranked results", "Is too fast", "Performs exact matching without ranking relevance", "Cannot read XML"], correctAnswer: "Performs exact matching without ranking relevance" },
      { question: "The Semantic Web is often referred to as Web:", options: ["1.0", "2.0", "3.0", "4.0"], correctAnswer: "3.0" },
      { question: "Which of the following represents unstructured data?", options: ["SQL database", "XML file", "Plain text email", "RDF triple"], correctAnswer: "Plain text email" },
      { question: "What defines the custom tags allowed in a specific XML document class?", options: ["CSS", "DTD (Document Type Definition) or XML Schema", "HTML", "Robots.txt"], correctAnswer: "DTD (Document Type Definition) or XML Schema" },
      { question: "The concept of linking related datasets on the Semantic Web is called:", options: ["Web Crawling", "Linked Data", "Hypertext", "PageRank"], correctAnswer: "Linked Data" },
      { question: "In XML, an element nested inside another element is a:", options: ["Root", "Child", "Parent", "Sibling"], correctAnswer: "Child" },
      { question: "XML retrieval systems must evaluate relevance at:", options: ["The document level only", "Multiple levels of the XML tree", "The server level", "The database row level"], correctAnswer: "Multiple levels of the XML tree" }
    ]
  }
];  
