export const microprocessorAndInterfacingViva = [
  {
    chapterNumber: 1,
    chapterName: "Introduction to Microprocessor, Components of a Microprocessor",
    questions: [
      {
        question: "What is a Microprocessor?",
        answer: "A microprocessor is a multipurpose, programmable, clock-driven, register-based electronic device. It reads binary instructions from a storage device called memory, accepts binary data as input, and processes data according to those instructions."
      },
      {
        question: "What are the three main components of a Microprocessor?",
        answer: "The three primary components are the Arithmetic and Logic Unit (ALU), the Control Unit (CU), and the Register Array. Together, they fetch, decode, and execute instructions."
      },
      {
        question: "What is the function of the ALU?",
        answer: "The Arithmetic and Logic Unit (ALU) performs computing functions. It handles arithmetic operations like addition and subtraction, and logical operations like AND, OR, and XOR on binary data."
      },
      {
        question: "Explain the role of the Control Unit (CU).",
        answer: "The Control Unit provides the necessary timing and control signals to all the operations in the microcomputer. It controls the flow of data between the microprocessor, memory, and peripherals."
      },
      {
        question: "What are Registers in a microprocessor?",
        answer: "Registers are small, fast, temporary storage locations inside the microprocessor. They are used to store data, addresses, and intermediate results during program execution."
      },
      {
        question: "What is a System Bus?",
        answer: "A System Bus is a communication path made of a group of conducting wires over which data, addresses, and control signals are transmitted between the microprocessor and its peripherals."
      },
      {
        question: "Describe the Address Bus.",
        answer: "The Address Bus is a group of unidirectional lines used by the microprocessor to send the address of a memory location or an I/O port. Its width determines the maximum addressable memory."
      },
      {
        question: "What is the Data Bus?",
        answer: "The Data Bus is a group of bidirectional lines used for data transfer between the microprocessor and memory or I/O devices. The width of the data bus determines the word length of the processor."
      },
      {
        question: "What is the Control Bus?",
        answer: "The Control Bus consists of various individual lines that carry synchronization and control signals (like Read and Write signals) to govern the timing of operations across the system."
      },
      {
        question: "What does 'Word Length' mean?",
        answer: "Word length is the number of bits a microprocessor can process or transfer simultaneously. An 8-bit microprocessor like the 8085 has a word length of 8 bits."
      },
      {
        question: "What is the role of a Clock in a microprocessor?",
        answer: "The clock generates a continuous stream of square-wave pulses. It synchronizes all internal operations of the microprocessor and determines the speed of instruction execution."
      },
      {
        question: "What is an Accumulator?",
        answer: "The Accumulator is a special-purpose register in the ALU where mathematical and logical operations are performed. One of the operands is usually stored here, and the result is also saved here."
      },
      {
        question: "How does a microprocessor system communicate with the outside world?",
        answer: "It communicates using Input/Output (I/O) devices. Input devices (like keyboards) feed data into the system, while Output devices (like displays) present the processed data."
      },
      {
        question: "What is the difference between a microprocessor and a microcomputer?",
        answer: "A microprocessor is a single IC acting as the CPU. A microcomputer is a complete system that includes a microprocessor, memory, and I/O devices connected via buses."
      },
      {
        question: "Why is the address bus unidirectional?",
        answer: "The address bus is unidirectional because the address is always generated by the Master (the microprocessor) to locate a specific memory or I/O device; devices never send addresses to the processor."
      },
      {
        question: "Why is the data bus bidirectional?",
        answer: "The data bus must be bidirectional because the microprocessor needs to both read data from memory/peripherals (input) and write data to them (output)."
      },
      {
        question: "What is the Program Counter (PC)?",
        answer: "The Program Counter is a special register that holds the memory address of the next instruction to be fetched and executed, automatically incrementing after each fetch."
      },
      {
        question: "What is a Microcontroller?",
        answer: "A microcontroller is a single chip that integrates a microprocessor, memory (RAM/ROM), and I/O ports. It is designed for specific embedded control applications."
      },
      {
        question: "What does instruction decoding mean?",
        answer: "Instruction decoding is the process where the Control Unit interprets the fetched binary instruction (opcode) to determine what operation needs to be performed."
      },
      {
        question: "What is a Bus Organization?",
        answer: "Bus organization refers to the structured arrangement of the address, data, and control buses that logically connect the CPU, Memory, and I/O devices into a functional system."
      }
    ],
    mcqs: [
      {
        question: "Which component of the microprocessor performs mathematical operations?",
        options: ["Control Unit", "ALU", "Program Counter", "Address Bus"],
        correctAnswer: "ALU"
      },
      {
        question: "What type of bus is the Address Bus?",
        options: ["Bidirectional", "Unidirectional", "Omnidirectional", "Multiplexed strictly"],
        correctAnswer: "Unidirectional"
      },
      {
        question: "Which bus carries the Read and Write signals?",
        options: ["Data Bus", "Address Bus", "Control Bus", "Memory Bus"],
        correctAnswer: "Control Bus"
      },
      {
        question: "What determines the maximum memory a microprocessor can access?",
        options: ["Data Bus width", "Address Bus width", "Control Bus width", "ALU size"],
        correctAnswer: "Address Bus width"
      },
      {
        question: "Which register holds the address of the next instruction to be executed?",
        options: ["Accumulator", "Instruction Register", "Stack Pointer", "Program Counter"],
        correctAnswer: "Program Counter"
      },
      {
        question: "A microprocessor is a _______ device.",
        options: ["Mechanical", "Programmable electronic", "Optical", "Hydraulic"],
        correctAnswer: "Programmable electronic"
      },
      {
        question: "The width of the data bus defines the microprocessor's:",
        options: ["Address space", "Word length", "Clock speed", "Power consumption"],
        correctAnswer: "Word length"
      },
      {
        question: "Which part provides timing and synchronization signals?",
        options: ["ALU", "Control Unit", "Registers", "ROM"],
        correctAnswer: "Control Unit"
      },
      {
        question: "Which is an example of an input device?",
        options: ["Monitor", "Printer", "Keyboard", "LED"],
        correctAnswer: "Keyboard"
      },
      {
        question: "The Accumulator is generally an:",
        options: ["8-bit register in 8085", "16-bit register in 8085", "Address bus", "Output port"],
        correctAnswer: "8-bit register in 8085"
      },
      {
        question: "Data flow on the Data Bus is:",
        options: ["Unidirectional", "Bidirectional", "Only towards CPU", "Only towards Memory"],
        correctAnswer: "Bidirectional"
      },
      {
        question: "Which memory is used to store permanent programs like BIOS?",
        options: ["RAM", "ROM", "Cache", "Registers"],
        correctAnswer: "ROM"
      },
      {
        question: "The process of getting an instruction from memory is called:",
        options: ["Decode", "Execute", "Fetch", "Store"],
        correctAnswer: "Fetch"
      },
      {
        question: "The collection of conducting wires connecting CPU with other peripherals is known as:",
        options: ["Cable", "Bus", "Port", "Link"],
        correctAnswer: "Bus"
      },
      {
        question: "In a microcomputer, the CPU is implemented on a single chip known as:",
        options: ["Motherboard", "Microprocessor", "RAM", "I/O Controller"],
        correctAnswer: "Microprocessor"
      },
      {
        question: "What translates the fetched instruction so the processor understands it?",
        options: ["ALU", "Instruction Decoder", "Accumulator", "Address Bus"],
        correctAnswer: "Instruction Decoder"
      },
      {
        question: "Which of the following is NOT a system bus?",
        options: ["Address Bus", "Data Bus", "Control Bus", "Power Bus"],
        correctAnswer: "Power Bus"
      },
      {
        question: "What dictates the speed at which a microprocessor executes instructions?",
        options: ["Clock frequency", "Memory size", "Data bus width", "Number of peripherals"],
        correctAnswer: "Clock frequency"
      },
      {
        question: "A device that contains a CPU, memory, and I/O on a single chip is a:",
        options: ["Microprocessor", "Microcontroller", "Mainframe", "Supercomputer"],
        correctAnswer: "Microcontroller"
      },
      {
        question: "The operation where the CPU sends data to memory is called a:",
        options: ["Read operation", "Fetch operation", "Write operation", "Decode operation"],
        correctAnswer: "Write operation"
      }
    ]
  },
  {
    chapterNumber: 2,
    chapterName: "Microprocessor Architecture and Operations, Memory, I/O",
    questions: [
      {
        question: "What are the primary operations performed by a microprocessor?",
        answer: "A microprocessor mainly performs four basic operations: Memory Read, Memory Write, I/O Read, and I/O Write, coordinated by control signals."
      },
      {
        question: "Explain the Memory Read operation.",
        answer: "In a Memory Read operation, the microprocessor places a memory address on the address bus, activates the memory read control signal, and reads the data sent by the memory on the data bus."
      },
      {
        question: "Explain the Memory Write operation.",
        answer: "In a Memory Write operation, the microprocessor sends an address to the address bus, places data on the data bus, and activates the memory write control signal to store the data in memory."
      },
      {
        question: "What is Memory-Mapped I/O?",
        answer: "In Memory-Mapped I/O, I/O devices are assigned addresses from the total memory space. The microprocessor treats these I/O devices exactly like memory locations using memory read/write instructions."
      },
      {
        question: "What is I/O-Mapped I/O (Isolated I/O)?",
        answer: "In I/O-Mapped I/O, peripheral devices are assigned an independent address space separate from memory. Special instructions (like IN and OUT) are used to access these devices."
      },
      {
        question: "What is a Tri-state logic device?",
        answer: "A tri-state logic device has three output states: Logic 0, Logic 1, and High Impedance (High-Z). The High-Z state disconnects the device from the bus, allowing multiple devices to share the same bus."
      },
      {
        question: "Why are buffers used in a microprocessor system?",
        answer: "Buffers are used to increase the driving capacity of the microprocessor's bus signals. They isolate the processor from external devices and provide the necessary current to drive multiple loads."
      },
      {
        question: "What is the function of a Latch?",
        answer: "A latch is a temporary storage device used to hold data or address bits. It is commonly used to demultiplex the address/data bus, capturing the address when a specific control signal (like ALE) is high."
      },
      {
        question: "What is address decoding?",
        answer: "Address decoding is the process of using logic gates or decoders (like the 74LS138) to generate a Chip Select (CS) signal for a specific memory chip or I/O device based on the address bus status."
      },
      {
        question: "Why is a Chip Select (CS) signal necessary?",
        answer: "Multiple memory and I/O chips share the same data bus. The Chip Select signal ensures that only one specific chip is activated at a time to read or write data, avoiding bus contention."
      },
      {
        question: "What is the difference between RAM and ROM?",
        answer: "RAM (Random Access Memory) is volatile and used for temporary data storage during execution. ROM (Read-Only Memory) is non-volatile and stores permanent firmware like the monitor program."
      },
      {
        question: "What happens during an I/O Read operation?",
        answer: "The microprocessor places the port address on the address bus, asserts the I/O read control signal, and the selected input device places its data on the data bus for the processor to read."
      },
      {
        question: "What happens during an I/O Write operation?",
        answer: "The processor places the port address on the address bus, puts the data on the data bus, and asserts the I/O write control signal to send the data to the selected output device."
      },
      {
        question: "What is Primary Memory?",
        answer: "Primary memory is the memory directly accessible by the CPU, consisting of RAM and ROM. It holds the instructions and data currently being executed."
      },
      {
        question: "What does 'Volatile Memory' mean?",
        answer: "Volatile memory requires continuous power to retain its stored information. If the power is turned off, all data currently held in volatile memory (like RAM) is immediately lost."
      },
      {
        question: "What is an Interfacing circuit?",
        answer: "An interfacing circuit is hardware that acts as a bridge between the microprocessor and an external device. It matches signal levels, timing, and data formats to enable communication."
      },
      {
        question: "How many addresses can be accessed with a 16-bit address bus?",
        answer: "A 16-bit address bus can access 2^16 addresses, which equals 65,536 distinct memory locations, commonly referred to as 64 Kilobytes (64 KB) of memory."
      },
      {
        question: "What is an Output Port?",
        answer: "An output port is an interfacing circuit, typically consisting of latches, that captures data from the data bus and holds it stable for an external output device (like LEDs or a display)."
      },
      {
        question: "What is an Input Port?",
        answer: "An input port is an interfacing circuit, typically consisting of tri-state buffers, that takes data from an external input device and places it onto the data bus when requested by the CPU."
      },
      {
        question: "What is bus contention?",
        answer: "Bus contention occurs when multiple devices attempt to drive data onto the same bus lines simultaneously, causing data corruption and potential hardware damage."
      }
    ],
    mcqs: [
      {
        question: "Which operation involves the CPU sending data to a memory location?",
        options: ["Memory Read", "Memory Write", "I/O Read", "I/O Write"],
        correctAnswer: "Memory Write"
      },
      {
        question: "In Memory-Mapped I/O, I/O devices are treated as:",
        options: ["Memory locations", "Interrupts", "Registers", "DMA controllers"],
        correctAnswer: "Memory locations"
      },
      {
        question: "What state disconnects a tri-state logic device from the bus?",
        options: ["Logic 1", "Logic 0", "High Impedance (High-Z)", "Active Low"],
        correctAnswer: "High Impedance (High-Z)"
      },
      {
        question: "Which component is used to hold the address temporarily during demultiplexing?",
        options: ["Buffer", "Latch", "Decoder", "ALU"],
        correctAnswer: "Latch"
      },
      {
        question: "Address decoding is used to generate which critical signal?",
        options: ["Clock", "Chip Select (CS)", "Read (RD)", "Write (WR)"],
        correctAnswer: "Chip Select (CS)"
      },
      {
        question: "Which memory type loses its data when power is removed?",
        options: ["ROM", "EPROM", "RAM", "EEPROM"],
        correctAnswer: "RAM"
      },
      {
        question: "How many memory locations can a 16-bit address bus access?",
        options: ["16 KB", "32 KB", "64 KB", "128 KB"],
        correctAnswer: "64 KB"
      },
      {
        question: "In I/O Mapped I/O, the processor uses specific instructions like:",
        options: ["MOV", "IN and OUT", "ADD and SUB", "PUSH and POP"],
        correctAnswer: "IN and OUT"
      },
      {
        question: "What is used to increase the driving capability of a bus?",
        options: ["Latch", "Buffer", "Decoder", "Multiplexer"],
        correctAnswer: "Buffer"
      },
      {
        question: "Which device is primarily used to input data into the microprocessor system?",
        options: ["Printer", "LED Display", "ADC (Analog to Digital Converter)", "DAC"],
        correctAnswer: "ADC (Analog to Digital Converter)"
      },
      {
        question: "An 8-bit data bus can carry maximum how many unique values simultaneously?",
        options: ["8", "16", "256", "65536"],
        correctAnswer: "256"
      },
      {
        question: "To perform an I/O Read, which control signal must be active?",
        options: ["MEMW'", "MEMR'", "IOW'", "IOR'"],
        correctAnswer: "IOR'"
      },
      {
        question: "The physical circuit that connects a peripheral to the CPU bus is called:",
        options: ["Operating System", "Interfacing Circuit", "Compiler", "Assembler"],
        correctAnswer: "Interfacing Circuit"
      },
      {
        question: "Which logic gate is commonly used for basic address decoding?",
        options: ["NAND", "OR", "XOR", "NOT"],
        correctAnswer: "NAND"
      },
      {
        question: "An Output Port is essentially a:",
        options: ["Tri-state buffer", "Latch", "Decoder", "Microphone"],
        correctAnswer: "Latch"
      },
      {
        question: "An Input Port is essentially a:",
        options: ["Tri-state buffer", "Latch", "Flip-Flop", "Timer"],
        correctAnswer: "Tri-state buffer"
      },
      {
        question: "Bus contention is avoided by ensuring that:",
        options: ["All chips are selected at once", "Only one Chip Select is active at a time", "Clock speed is doubled", "Power is reduced"],
        correctAnswer: "Only one Chip Select is active at a time"
      },
      {
        question: "In an 8085 system, the lower order address bus is multiplexed with:",
        options: ["Control Bus", "Higher order address bus", "Data Bus", "Interrupt lines"],
        correctAnswer: "Data Bus"
      },
      {
        question: "Which of the following is non-volatile memory?",
        options: ["SRAM", "DRAM", "ROM", "Cache"],
        correctAnswer: "ROM"
      },
      {
        question: "What is the primary function of memory in a microcomputer system?",
        options: ["To perform arithmetic", "To store instructions and data", "To display output", "To act as a clock"],
        correctAnswer: "To store instructions and data"
      }
    ]
  },
  {
    chapterNumber: 3,
    chapterName: "8085 Microprocessor Architecture",
    questions: [
      {
        question: "What is the architecture of the 8085 microprocessor?",
        answer: "The 8085 is an 8-bit microprocessor in a 40-pin DIP. It features an 8-bit data bus, a 16-bit address bus, an ALU, a 16-bit Program Counter, a 16-bit Stack Pointer, and six 8-bit general-purpose registers."
      },
      {
        question: "What is the purpose of the ALE pin?",
        answer: "ALE stands for Address Latch Enable. It is a positive-going pulse generated every machine cycle, used to latch the lower 8 bits of the address from the multiplexed AD0-AD7 bus."
      },
      {
        question: "Why are AD0-AD7 pins multiplexed?",
        answer: "AD0-AD7 are multiplexed to carry both the lower 8-bit address and the 8-bit data to reduce the total pin count of the 8085 IC, making it possible to fit in a 40-pin package."
      },
      {
        question: "What is the IO/M' signal?",
        answer: "IO/M' is a status signal that distinguishes between Memory and I/O operations. When High, it indicates an I/O operation; when Low, it indicates a Memory operation."
      },
      {
        question: "What is an Instruction Cycle?",
        answer: "An Instruction Cycle is the total time required by the microprocessor to fetch, decode, and completely execute a single instruction."
      },
      {
        question: "What is a Machine Cycle?",
        answer: "A Machine Cycle is the time required to complete one basic operation of accessing memory or I/O. Examples include Opcode Fetch, Memory Read, and Memory Write."
      },
      {
        question: "What is a T-State?",
        answer: "A T-State (Clock State) is one subdivision of the operation performed in one clock period. Machine cycles are usually comprised of 3 to 6 T-States."
      },
      {
        question: "Explain the Opcode Fetch machine cycle.",
        answer: "It is the first machine cycle of every instruction. The processor places the PC address on the bus, asserts the read signal, and brings the operation code (opcode) from memory into the instruction decoder."
      },
      {
        question: "What are S0 and S1 pins?",
        answer: "S0 and S1 are status signals that indicate the type of machine cycle currently executing. For example, S1=1, S0=1 indicates an Opcode Fetch cycle."
      },
      {
        question: "What is the function of the HOLD and HLDA pins?",
        answer: "HOLD is an input signal from a DMA controller requesting bus control. HLDA (Hold Acknowledge) is the output signal acknowledging that the 8085 will relinquish the buses in the next clock cycle."
      },
      {
        question: "What is the Flag Register in 8085?",
        answer: "It is an 8-bit register containing 5 flip-flops that change status according to the ALU result. The flags are Zero (Z), Carry (CY), Sign (S), Parity (P), and Auxiliary Carry (AC)."
      },
      {
        question: "What does the READY pin do?",
        answer: "The READY pin is used to synchronize slower peripherals with the faster microprocessor. If READY is low, the microprocessor enters a wait state until the pin goes high."
      },
      {
        question: "Name the general-purpose registers in 8085.",
        answer: "The 8085 has six 8-bit general-purpose registers: B, C, D, E, H, and L. They can be combined into 16-bit register pairs: BC, DE, and HL."
      },
      {
        question: "What is the significance of the HL register pair?",
        answer: "The HL register pair often acts as a data pointer, holding the 16-bit memory address for instructions that perform indirect memory access (referenced as 'M' in instructions)."
      },
      {
        question: "What are the X1 and X2 pins used for?",
        answer: "X1 and X2 are connected to an external crystal oscillator. The 8085 divides this crystal frequency by 2 to generate its internal operating clock frequency."
      },
      {
        question: "What is the RESET IN' pin?",
        answer: "RESET IN' is an active-low input. When asserted, it suspends execution, clears the Program Counter to 0000H, resets the buses to high impedance, and resets the Interrupt Enable flip-flop."
      },
      {
        question: "What is the RESET OUT pin?",
        answer: "RESET OUT is an active-high output signal indicating that the 8085 is being reset. It is used to simultaneously reset other connected peripherals in the system."
      },
      {
        question: "How are control signals generated in 8085?",
        answer: "Control signals like MEMR', MEMW', IOR', and IOW' are generated by logically combining the IO/M', RD', and WR' signals using external logic gates like NAND or 3-to-8 decoders."
      },
      {
        question: "What is the standard operating frequency of the 8085?",
        answer: "The standard 8085 operates at a 3 MHz internal clock frequency, which requires connecting a 6 MHz crystal to the X1 and X2 pins."
      },
      {
        question: "What is Memory Interfacing?",
        answer: "Memory interfacing is the process of connecting memory chips to the processor buses. It involves connecting data and address lines, and designing decoding logic to provide the correct Chip Select signal."
      }
    ],
    mcqs: [
      {
        question: "How many pins does the 8085 microprocessor IC have?",
        options: ["20", "28", "40", "48"],
        correctAnswer: "40"
      },
      {
        question: "Which signal is used to demultiplex the AD0-AD7 bus?",
        options: ["READY", "ALE", "HOLD", "INTR"],
        correctAnswer: "ALE"
      },
      {
        question: "Which pin indicates whether the current operation accesses Memory or I/O?",
        options: ["S0", "S1", "IO/M'", "READY"],
        correctAnswer: "IO/M'"
      },
      {
        question: "One clock period in the 8085 timing diagram is called a:",
        options: ["Machine Cycle", "Instruction Cycle", "T-State", "Fetch Cycle"],
        correctAnswer: "T-State"
      },
      {
        question: "An Opcode Fetch cycle typically consists of how many T-States?",
        options: ["1 or 2", "4 or 6", "10", "16"],
        correctAnswer: "4 or 6"
      },
      {
        question: "Which register pair is commonly used as a memory pointer?",
        options: ["BC", "DE", "HL", "AF"],
        correctAnswer: "HL"
      },
      {
        question: "Which flag is set when the result of an arithmetic operation is zero?",
        options: ["Carry", "Parity", "Zero", "Sign"],
        correctAnswer: "Zero"
      },
      {
        question: "If a 6 MHz crystal is connected to X1 and X2, what is the internal clock frequency?",
        options: ["3 MHz", "6 MHz", "12 MHz", "1.5 MHz"],
        correctAnswer: "3 MHz"
      },
      {
        question: "Which signal is an output acknowledging a DMA request?",
        options: ["HOLD", "HLDA", "READY", "INTA'"],
        correctAnswer: "HLDA"
      },
      {
        question: "Which pins act as status signals to specify the machine cycle type?",
        options: ["RD and WR", "S0 and S1", "ALE and READY", "X1 and X2"],
        correctAnswer: "S0 and S1"
      },
      {
        question: "The Program Counter in 8085 is a:",
        options: ["8-bit register", "16-bit register", "4-bit register", "32-bit register"],
        correctAnswer: "16-bit register"
      },
      {
        question: "When RESET IN' is activated, the Program Counter is loaded with:",
        options: ["FFFFH", "8000H", "0000H", "Random value"],
        correctAnswer: "0000H"
      },
      {
        question: "To generate the MEMW' control signal, which 8085 signals are used?",
        options: ["IO/M'=0, WR'=0", "IO/M'=1, WR'=0", "IO/M'=0, RD'=0", "IO/M'=1, RD'=0"],
        correctAnswer: "IO/M'=0, WR'=0"
      },
      {
        question: "What is the purpose of the READY pin?",
        options: ["Reset the processor", "Synchronize slower peripherals", "Request DMA", "Provide power"],
        correctAnswer: "Synchronize slower peripherals"
      },
      {
        question: "How many general-purpose 8-bit registers does the 8085 have?",
        options: ["4", "6", "8", "16"],
        correctAnswer: "6"
      },
      {
        question: "Which operation is always the first machine cycle of any instruction?",
        options: ["Memory Read", "Memory Write", "I/O Read", "Opcode Fetch"],
        correctAnswer: "Opcode Fetch"
      },
      {
        question: "Which flag is NOT present in the 8085 Flag Register?",
        options: ["Zero", "Carry", "Overflow", "Parity"],
        correctAnswer: "Overflow"
      },
      {
        question: "What does the instruction cycle consist of?",
        options: ["Only Fetch", "Only Execute", "Fetch, Decode, and Execute", "Only Decode"],
        correctAnswer: "Fetch, Decode, and Execute"
      },
      {
        question: "To access 64KB of memory, how many address lines are required?",
        options: ["8", "12", "16", "20"],
        correctAnswer: "16"
      },
      {
        question: "The higher order address bus (A8-A15) is:",
        options: ["Bidirectional", "Multiplexed", "Unidirectional", "Tri-stated permanently"],
        correctAnswer: "Unidirectional"
      }
    ]
  },
  {
    chapterNumber: 4,
    chapterName: "Assembly Language Programming Basics",
    questions: [
      {
        question: "What is an Assembly Language?",
        answer: "Assembly language is a low-level programming language that uses alphanumeric mnemonics (like ADD, MOV) to represent machine code instructions, making it easier for humans to write and understand."
      },
      {
        question: "What is an Assembler?",
        answer: "An Assembler is a software program that translates assembly language code (mnemonics) into binary machine code (hexadecimal/binary objects) that the microprocessor can execute."
      },
      {
        question: "What is an Opcode?",
        answer: "Opcode (Operation Code) is the first part of an instruction that specifies the specific task or operation to be performed by the microprocessor, such as addition or data transfer."
      },
      {
        question: "What is an Operand?",
        answer: "The Operand is the second part of an instruction which specifies the data to be operated on. It can be a register, a memory address, or 8-bit/16-bit immediate data."
      },
      {
        question: "What are Addressing Modes?",
        answer: "Addressing modes refer to the various ways a microprocessor can specify the operand (data) in an instruction. The 8085 has five main addressing modes."
      },
      {
        question: "Explain Immediate Addressing Mode.",
        answer: "In immediate addressing mode, the actual 8-bit or 16-bit data is specified directly within the instruction itself. Example: MVI A, 05H (Load Accumulator with 05H)."
      },
      {
        question: "Explain Register Addressing Mode.",
        answer: "In register addressing mode, the operand is stored in one of the general-purpose registers, and the instruction specifies that register. Example: MOV A, B (Copy data from B to A)."
      },
      {
        question: "Explain Direct Addressing Mode.",
        answer: "In direct addressing mode, the 16-bit memory address or 8-bit I/O port address of the operand is given explicitly in the instruction. Example: LDA 2000H."
      },
      {
        question: "Explain Indirect Addressing Mode.",
        answer: "In indirect addressing mode, the memory address of the data is held in a register pair (usually HL). The instruction uses this pair as a pointer. Example: MOV A, M."
      },
      {
        question: "What is Implied (Implicit) Addressing Mode?",
        answer: "In implied addressing mode, the operand is hidden and implicitly defined in the opcode itself. No operand needs to be specified. Example: CMA (Complement Accumulator)."
      },
      {
        question: "What is a 1-byte instruction?",
        answer: "A 1-byte instruction includes both the opcode and operand within a single 8-bit hex code. Example: MOV A, B or CMA. It requires only one memory location."
      },
      {
        question: "What is a 2-byte instruction?",
        answer: "A 2-byte instruction requires two memory locations. The first byte is the opcode, and the second byte is an 8-bit data or an 8-bit port address. Example: MVI A, 32H."
      },
      {
        question: "What is a 3-byte instruction?",
        answer: "A 3-byte instruction requires three memory locations. The first byte is the opcode, and the next two bytes represent a 16-bit address or 16-bit data. Example: JMP 4000H."
      },
      {
        question: "What are mnemonics?",
        answer: "Mnemonics are English-like abbreviations used in assembly language to represent the binary opcodes of a processor, such as ADD, SUB, or MOV."
      },
      {
        question: "How are instructions classified in 8085?",
        answer: "Instructions are classified into five functional categories: Data Transfer, Arithmetic, Logical, Branching, and Machine Control operations."
      },
      {
        question: "What is a Label in assembly language?",
        answer: "A label is a symbolic name given to a memory location or a line of code. It acts as a target for branching instructions like JMP or CALL, making the code readable."
      },
      {
        question: "What is the process of Executing a program?",
        answer: "Executing a program means the microprocessor continuously fetches instructions from memory, decodes them, and performs the specified operations until a Halt (HLT) instruction is reached."
      },
      {
        question: "What is Debugging?",
        answer: "Debugging is the process of finding and fixing logical or syntax errors (bugs) in an assembly language program using tools like simulators, breakpoints, or single-stepping."
      },
      {
        question: "What does the HLT instruction do?",
        answer: "HLT stands for Halt. It is a machine control instruction that stops the microprocessor's execution. The processor waits until a reset or a valid interrupt occurs."
      },
      {
        question: "In what order are the bytes of a 3-byte instruction stored in memory?",
        answer: "The first memory location stores the opcode. The second location stores the lower byte of the 16-bit address/data, and the third location stores the higher byte (Little Endian format)."
      }
    ],
    mcqs: [
      {
        question: "Which addressing mode is used in the instruction MVI B, 45H?",
        options: ["Register", "Direct", "Immediate", "Implied"],
        correctAnswer: "Immediate"
      },
      {
        question: "Which addressing mode is used in the instruction MOV A, M?",
        options: ["Direct", "Indirect", "Implied", "Register"],
        correctAnswer: "Indirect"
      },
      {
        question: "The instruction LDA 2050H is an example of which addressing mode?",
        options: ["Direct", "Indirect", "Immediate", "Implied"],
        correctAnswer: "Direct"
      },
      {
        question: "Which addressing mode is used in CMA?",
        options: ["Immediate", "Direct", "Implied", "Indirect"],
        correctAnswer: "Implied"
      },
      {
        question: "How many bytes does the instruction LXI H, 2000H occupy?",
        options: ["1 byte", "2 bytes", "3 bytes", "4 bytes"],
        correctAnswer: "3 bytes"
      },
      {
        question: "How many bytes does the instruction MOV C, D occupy?",
        options: ["1 byte", "2 bytes", "3 bytes", "0 bytes"],
        correctAnswer: "1 byte"
      },
      {
        question: "What translates assembly mnemonics into machine code?",
        options: ["Compiler", "Interpreter", "Assembler", "Linker"],
        correctAnswer: "Assembler"
      },
      {
        question: "Which part of the instruction specifies the task to be performed?",
        options: ["Operand", "Opcode", "Label", "Comment"],
        correctAnswer: "Opcode"
      },
      {
        question: "The second byte of a 2-byte instruction is typically:",
        options: ["Opcode", "16-bit address", "8-bit data or port address", "A register name"],
        correctAnswer: "8-bit data or port address"
      },
      {
        question: "In little-endian format (used in 8085), a 16-bit address is stored as:",
        options: ["Higher byte first, lower byte second", "Lower byte first, higher byte second", "Both together", "Randomly"],
        correctAnswer: "Lower byte first, higher byte second"
      },
      {
        question: "The instruction ADD B falls under which category?",
        options: ["Data Transfer", "Logical", "Arithmetic", "Branch"],
        correctAnswer: "Arithmetic"
      },
      {
        question: "The instruction JMP 4000H falls under which category?",
        options: ["Data Transfer", "Branching", "Logical", "Machine Control"],
        correctAnswer: "Branching"
      },
      {
        question: "What is used to represent the memory location pointed to by the HL register pair?",
        options: ["A", "H", "L", "M"],
        correctAnswer: "M"
      },
      {
        question: "Which instruction stops the execution of the microprocessor?",
        options: ["NOP", "HLT", "RET", "END"],
        correctAnswer: "HLT"
      },
      {
        question: "Which is a valid mnemonic for copying data from register C to accumulator?",
        options: ["MOV C, A", "MOV A, C", "COPY A, C", "LOAD A, C"],
        correctAnswer: "MOV A, C"
      },
      {
        question: "What is finding and fixing errors in an assembly program called?",
        options: ["Executing", "Assembling", "Debugging", "Linking"],
        correctAnswer: "Debugging"
      },
      {
        question: "Which of the following is an instruction and data format classification?",
        options: ["4-byte", "1-byte", "0-byte", "Half-byte"],
        correctAnswer: "1-byte"
      },
      {
        question: "Which of the following instructions does NOT affect any flags?",
        options: ["ADD B", "SUB C", "MOV A, B", "CMP D"],
        correctAnswer: "MOV A, B"
      },
      {
        question: "What does NOP stand for?",
        options: ["No Output Port", "No Operation", "Not Operand", "Next Operation"],
        correctAnswer: "No Operation"
      },
      {
        question: "A symbolic name for an address in assembly is known as a:",
        options: ["Opcode", "Label", "Macro", "Directive"],
        correctAnswer: "Label"
      }
    ]
  },
  {
    chapterNumber: 5,
    chapterName: "Writing 8085 Assembly Language Programs",
    questions: [
      {
        question: "What are Data Transfer instructions?",
        answer: "Data transfer instructions copy data from a source to a destination without modifying the source data or affecting any flags. Examples include MOV, MVI, LXI, LDA, and STA."
      },
      {
        question: "Explain the MOV instruction.",
        answer: "MOV Rd, Rs copies the 8-bit contents of the source register (Rs) into the destination register (Rd). For example, MOV A, B copies the contents of B into the Accumulator."
      },
      {
        question: "What does the LXI instruction do?",
        answer: "LXI Rp, 16-bit_data loads a 16-bit immediate value directly into a register pair. For example, LXI H, 2000H loads 2000H into the HL register pair."
      },
      {
        question: "What are Arithmetic instructions?",
        answer: "Arithmetic instructions perform math operations like addition, subtraction, increment, and decrement. They modify the contents of registers and update the status flags. Examples: ADD, SUB, INR, DCR."
      },
      {
        question: "Explain the ADD M instruction.",
        answer: "ADD M adds the contents of the memory location whose address is currently stored in the HL register pair to the contents of the Accumulator, storing the result in the Accumulator."
      },
      {
        question: "What is the difference between INR and INX?",
        answer: "INR increments the content of an 8-bit register or memory location by 1. INX increments the content of a 16-bit register pair (like BC, DE, or HL) by 1."
      },
      {
        question: "What are Logical instructions?",
        answer: "Logical instructions perform bitwise boolean operations such as AND, OR, XOR, Rotate, and Compare. They operate on the Accumulator and another register/memory. Examples: ANA, ORA, XRA, CMP."
      },
      {
        question: "What does the CMP instruction do?",
        answer: "CMP compares a register or memory with the Accumulator by performing an internal subtraction (A - Reg). It does not change the Accumulator's content but updates the flags (Zero, Carry, Sign) based on the result."
      },
      {
        question: "How do you clear the Accumulator without using MVI A, 00H?",
        answer: "You can clear the Accumulator by using the instruction XRA A or SUB A. XORing or subtracting a register with itself always results in 00H."
      },
      {
        question: "What are Branch instructions?",
        answer: "Branch instructions alter the normal sequential execution of a program. They force the Program Counter to jump to a new 16-bit address. Examples: JMP, JZ, JNZ."
      },
      {
        question: "What is the difference between conditional and unconditional jumps?",
        answer: "An unconditional jump (JMP) transfers control to the specified address no matter what. A conditional jump (like JZ, JC) transfers control only if a specific status flag condition is met."
      },
      {
        question: "Explain the JZ instruction.",
        answer: "JZ (Jump on Zero) checks the Zero flag. If the Zero flag is 1 (meaning the previous operation resulted in zero), the processor jumps to the specified 16-bit address."
      },
      {
        question: "How do you implement a loop in 8085?",
        answer: "Initialize a register as a counter, perform the repetitive task, decrement the counter (DCR), and use a conditional jump (like JNZ) to loop back if the counter is not zero."
      },
      {
        question: "What does LDA 3000H do?",
        answer: "LDA 3000H loads the 8-bit contents of the memory location 3000H directly into the Accumulator."
      },
      {
        question: "What does STA 4000H do?",
        answer: "STA 4000H stores the 8-bit contents currently in the Accumulator directly into the memory location 4000H."
      },
      {
        question: "Explain the XCHG instruction.",
        answer: "XCHG exchanges the 16-bit contents of the HL register pair with the 16-bit contents of the DE register pair. No other registers or flags are affected."
      },
      {
        question: "What does the RAL instruction do?",
        answer: "RAL (Rotate Accumulator Left through Carry) shifts all bits in the Accumulator left by one position. The MSB goes to the Carry flag, and the Carry flag goes to the LSB."
      },
      {
        question: "How is a decision-making structure (if-else) implemented?",
        answer: "It is implemented using the Compare (CMP) instruction followed by a conditional jump (like JC, JZ). The jump directs the flow to different code blocks based on the comparison result."
      },
      {
        question: "What happens during DCR M?",
        answer: "DCR M decrements the contents of the memory location pointed to by the HL register pair by 1, and updates the Z, S, P, and AC flags (but not the Carry flag)."
      },
      {
        question: "Why does the 8085 instruction set lack a direct multiply instruction?",
        answer: "The 8085 is a basic 8-bit processor with a simple ALU that only performs addition and subtraction. Multiplication must be implemented in software using repeated addition or shift-and-add algorithms."
      }
    ],
    mcqs: [
      {
        question: "Which instruction loads a 16-bit immediate value into the HL pair?",
        options: ["MVI H", "LXI H", "LDA H", "LHLD"],
        correctAnswer: "LXI H"
      },
      {
        question: "Which instruction copies data from Memory to the Accumulator?",
        options: ["MOV M, A", "MOV A, M", "STA", "XCHG"],
        correctAnswer: "MOV A, M"
      },
      {
        question: "What does the instruction SUB B do?",
        options: ["A = A - B", "B = A - B", "A = B - A", "B = B - A"],
        correctAnswer: "A = A - B"
      },
      {
        question: "Which instruction increments the DE register pair by 1?",
        options: ["INR D", "INR E", "INX D", "INX DE"],
        correctAnswer: "INX D"
      },
      {
        question: "Which instruction compares register C with the Accumulator?",
        options: ["CMP C", "SUB C", "CPI C", "ANA C"],
        correctAnswer: "CMP C"
      },
      {
        question: "Which instruction performs a bitwise AND between register B and the Accumulator?",
        options: ["ORA B", "XRA B", "ANA B", "AND B"],
        correctAnswer: "ANA B"
      },
      {
        question: "What does XRA A achieve?",
        options: ["Sets Accumulator to FFH", "Clears the Accumulator to 00H", "Rotates Accumulator", "Exchanges A with B"],
        correctAnswer: "Clears the Accumulator to 00H"
      },
      {
        question: "JNZ 2050H branches to 2050H if:",
        options: ["Zero flag is 1", "Carry flag is 1", "Zero flag is 0", "Carry flag is 0"],
        correctAnswer: "Zero flag is 0"
      },
      {
        question: "JC 3000H will jump if:",
        options: ["Carry flag = 0", "Carry flag = 1", "Zero flag = 1", "Sign flag = 1"],
        correctAnswer: "Carry flag = 1"
      },
      {
        question: "Which instruction is used to unconditionally branch to a memory location?",
        options: ["JNZ", "JMP", "CALL", "RET"],
        correctAnswer: "JMP"
      },
      {
        question: "The typical instruction used to decrement a loop counter is:",
        options: ["SUB", "DCR", "DCX", "DEC"],
        correctAnswer: "DCR"
      },
      {
        question: "What does the STA instruction do?",
        options: ["Stores Accumulator contents to a 16-bit address", "Loads Accumulator from a 16-bit address", "Stores register B to Accumulator", "Stops the program"],
        correctAnswer: "Stores Accumulator contents to a 16-bit address"
      },
      {
        question: "Which instruction exchanges the contents of HL and DE pairs?",
        options: ["XCHG", "XTHL", "SPHL", "PCHL"],
        correctAnswer: "XCHG"
      },
      {
        question: "Rotate Accumulator Right without Carry is written as:",
        options: ["RAL", "RAR", "RLC", "RRC"],
        correctAnswer: "RRC"
      },
      {
        question: "To implement an IF-ELSE logic, which combination is mostly used?",
        options: ["ADD and SUB", "CMP and Conditional Jumps", "MOV and MVI", "IN and OUT"],
        correctAnswer: "CMP and Conditional Jumps"
      },
      {
        question: "Data Transfer instructions affect how many flags?",
        options: ["All flags", "Only Zero flag", "Only Carry flag", "None"],
        correctAnswer: "None"
      },
      {
        question: "LHLD 2000H loads data from 2000H and 2001H into:",
        options: ["B and C", "D and E", "L and H respectively", "H and L respectively"],
        correctAnswer: "L and H respectively"
      },
      {
        question: "Which instruction performs Accumulator OR with Memory?",
        options: ["ORA M", "ANA M", "XRA M", "ADD M"],
        correctAnswer: "ORA M"
      },
      {
        question: "If A=05H and B=05H, after CMP B, the Zero flag will be:",
        options: ["0", "1", "Unchanged", "Unknown"],
        correctAnswer: "1"
      },
      {
        question: "What is the result of CMA if A = F0H?",
        options: ["0FH", "FFH", "00H", "F0H"],
        correctAnswer: "0FH"
      }
    ]
  },
  {
    chapterNumber: 6,
    chapterName: "Stack & Subroutines, Counters and Time Delays",
    questions: [
      {
        question: "What is the Stack in 8085?",
        answer: "The stack is a reserved area of RAM used for temporary storage of data and addresses during program execution. It operates on the LIFO (Last In, First Out) principle."
      },
      {
        question: "What is the Stack Pointer (SP)?",
        answer: "The Stack Pointer is a 16-bit register that holds the memory address of the top of the stack. It must be initialized by the programmer (e.g., LXI SP, 2099H) before using the stack."
      },
      {
        question: "Explain the PUSH instruction.",
        answer: "PUSH Rp pushes the 16-bit contents of a register pair onto the stack. The SP is decremented by 1 to store the high byte, and decremented again by 1 to store the low byte."
      },
      {
        question: "Explain the POP instruction.",
        answer: "POP Rp removes two bytes from the top of the stack and stores them into the specified register pair. The SP is incremented by 1 after each byte is retrieved."
      },
      {
        question: "What is a Subroutine?",
        answer: "A subroutine is a reusable block of code that performs a specific task. Instead of writing the same code repeatedly, the main program 'calls' the subroutine whenever the task is needed."
      },
      {
        question: "How does the CALL instruction work?",
        answer: "CALL 16-bit_address pushes the current Program Counter (the return address) onto the stack and then loads the specified 16-bit address into the PC to jump to the subroutine."
      },
      {
        question: "How does the RET instruction work?",
        answer: "RET (Return) is used at the end of a subroutine. It pops the top two bytes from the stack into the Program Counter, causing execution to resume in the main program where it left off."
      },
      {
        question: "What is a Delay Loop?",
        answer: "A delay loop is a software routine that uses a counter initialized to a specific value. The processor executes a loop decrementing the counter to zero, simply to pass a specific amount of time."
      },
      {
        question: "How is a time delay calculated?",
        answer: "Time Delay = (Total T-States in the loop) × (Duration of one T-State). The duration of one T-State is 1 / (clock frequency)."
      },
      {
        question: "What is the DAA instruction?",
        answer: "DAA (Decimal Adjust Accumulator) is used after an ADD instruction to adjust the 8-bit binary result in the Accumulator to form two valid 4-bit BCD (Binary Coded Decimal) digits."
      },
      {
        question: "Why is BCD arithmetic different from binary arithmetic?",
        answer: "BCD represents decimal digits (0-9) using 4 bits. When adding BCD numbers in binary, if a nibble exceeds 9 or produces an auxiliary carry, 6 (0110) must be added to correct it."
      },
      {
        question: "What is a 16-bit addition in 8085?",
        answer: "Since the ALU is 8-bit, 16-bit addition is typically done using the DAD instruction, which adds the 16-bit content of a register pair to the HL pair and stores the result in HL."
      },
      {
        question: "What happens during stack underflow?",
        answer: "Stack underflow occurs when a POP or RET instruction is executed, but the stack is empty. It retrieves garbage data into the register or PC, likely crashing the program."
      },
      {
        question: "What happens during stack overflow?",
        answer: "Stack overflow occurs when continuous PUSH or CALL instructions exceed the reserved RAM size, overwriting program code or crucial data areas in memory."
      },
      {
        question: "How do you implement a 16-bit counter?",
        answer: "Load a 16-bit value into a register pair (e.g., LXI B, FFFFH), decrement the pair using DCX B, and use an OR operation (MOV A, B; ORA C) to check if the pair has reached zero."
      },
      {
        question: "What is the significance of PSW in stack operations?",
        answer: "PSW stands for Program Status Word, representing the Accumulator and the Flag register as a pair. PUSH PSW saves both the Accumulator and flags to the stack simultaneously."
      },
      {
        question: "How do you convert BCD to Binary?",
        answer: "Multiply the tens digit by 0AH (10) and add the units digit to get the binary (hexadecimal) equivalent of the packed BCD number."
      },
      {
        question: "How do you convert Binary to BCD?",
        answer: "Repeatedly divide the binary number by 0AH (10). The remainders form the units, tens, and hundreds BCD digits."
      },
      {
        question: "Can subroutines call other subroutines?",
        answer: "Yes, this is called nesting. The 8085 supports nested subroutines limited only by the available stack memory to store the multiple return addresses."
      },
      {
        question: "Why is saving registers important in subroutines?",
        answer: "Subroutines often modify registers. Using PUSH at the start and POP at the end preserves the original register values so the main program remains unaffected."
      }
    ],
    mcqs: [
      {
        question: "Which principle does the Stack follow?",
        options: ["FIFO", "LIFO", "FILO", "Random Access"],
        correctAnswer: "LIFO"
      },
      {
        question: "Which register keeps track of the top of the stack?",
        options: ["Program Counter", "Accumulator", "Stack Pointer", "Instruction Register"],
        correctAnswer: "Stack Pointer"
      },
      {
        question: "The PUSH instruction operates on:",
        options: ["8-bit registers only", "16-bit register pairs only", "Memory only", "Accumulator only"],
        correctAnswer: "16-bit register pairs only"
      },
      {
        question: "When a PUSH B instruction is executed, the Stack Pointer is:",
        options: ["Incremented by 2", "Decremented by 2", "Incremented by 1", "Decremented by 1"],
        correctAnswer: "Decremented by 2"
      },
      {
        question: "When a POP D instruction is executed, the Stack Pointer is:",
        options: ["Incremented by 2", "Decremented by 2", "Incremented by 1", "Decremented by 1"],
        correctAnswer: "Incremented by 2"
      },
      {
        question: "Which instruction transfers program control to a subroutine?",
        options: ["JMP", "CALL", "RET", "HLT"],
        correctAnswer: "CALL"
      },
      {
        question: "What does the CALL instruction save on the stack?",
        options: ["Accumulator", "Flag register", "Return address (PC)", "Stack Pointer"],
        correctAnswer: "Return address (PC)"
      },
      {
        question: "Which instruction brings control back to the main program from a subroutine?",
        options: ["JMP", "RET", "POP", "CALL"],
        correctAnswer: "RET"
      },
      {
        question: "Which instruction adjusts the Accumulator to valid BCD digits after addition?",
        options: ["ADC", "DAA", "CMA", "BCD"],
        correctAnswer: "DAA"
      },
      {
        question: "DAA adds 06H to the lower nibble if:",
        options: ["Auxiliary Carry is 1 or lower nibble > 9", "Carry is 1", "Zero flag is 1", "Sign flag is 1"],
        correctAnswer: "Auxiliary Carry is 1 or lower nibble > 9"
      },
      {
        question: "Which instruction adds the 16-bit contents of a register pair to the HL pair?",
        options: ["ADD", "ADC", "DAD", "INX"],
        correctAnswer: "DAD"
      },
      {
        question: "To produce a software time delay, the processor is typically trapped in a:",
        options: ["Halt state", "Subroutine", "Counting loop", "Interrupt"],
        correctAnswer: "Counting loop"
      },
      {
        question: "What is pushed to the stack using the PUSH PSW instruction?",
        options: ["Accumulator and B register", "HL pair", "Accumulator and Flag register", "Program Counter"],
        correctAnswer: "Accumulator and Flag register"
      },
      {
        question: "How many T-States does an instruction take if Clock Freq is 2MHz and T-states=4?",
        options: ["2 microseconds", "4 microseconds", "0.5 microseconds", "1 microsecond"],
        correctAnswer: "2 microseconds"
      },
      {
        question: "In 8085, the Stack grows:",
        options: ["From lower to higher addresses", "From higher to lower addresses", "In ROM", "Horizontally"],
        correctAnswer: "From higher to lower addresses"
      },
      {
        question: "Which instruction pair is essential for preserving data before executing a subroutine task?",
        options: ["MOV and MVI", "PUSH and POP", "CALL and RET", "IN and OUT"],
        correctAnswer: "PUSH and POP"
      },
      {
        question: "A subroutine calling another subroutine is known as:",
        options: ["Looping", "Recursion", "Nesting", "Branching"],
        correctAnswer: "Nesting"
      },
      {
        question: "Code conversion from Binary to BCD requires repeated:",
        options: ["Multiplication by 10", "Division by 10", "Addition of 6", "Subtraction of 6"],
        correctAnswer: "Division by 10"
      },
      {
        question: "DCX B does not affect the:",
        options: ["Register B", "Register C", "Zero Flag", "Value of the pair"],
        correctAnswer: "Zero Flag"
      },
      {
        question: "A common use for time delay routines is:",
        options: ["Multiplying numbers", "Interfacing slow peripherals like displays", "Memory read", "Dividing numbers"],
        correctAnswer: "Interfacing slow peripherals like displays"
      }
    ]
  },
  {
    chapterNumber: 7,
    chapterName: "Interfacing Concepts, Ports, Interrupts, 8259A, 8255A",
    questions: [
      {
        question: "What is an Interrupt?",
        answer: "An interrupt is a hardware or software signal that pauses the microprocessor's current execution, forcing it to branch to a specific service routine to handle an urgent task."
      },
      {
        question: "What is an ISR?",
        answer: "ISR stands for Interrupt Service Routine. It is a specific sub-program written by the user that the microprocessor executes when a particular interrupt is triggered."
      },
      {
        question: "Name the five hardware interrupts in the 8085.",
        answer: "The five hardware interrupt pins on the 8085 are TRAP, RST 7.5, RST 6.5, RST 5.5, and INTR."
      },
      {
        question: "What is the TRAP interrupt?",
        answer: "TRAP is the highest priority, non-maskable hardware interrupt in the 8085. It is both edge and level-triggered and cannot be disabled by the programmer. It is usually used for critical errors like power failure."
      },
      {
        question: "What does 'Maskable Interrupt' mean?",
        answer: "A maskable interrupt is an interrupt whose request can be ignored (disabled) by the microprocessor using software instructions like DI (Disable Interrupts) or SIM."
      },
      {
        question: "What is a Vectored Interrupt?",
        answer: "A vectored interrupt automatically directs the microprocessor to a specific, predefined memory address (the vector address) to execute the ISR. TRAP and the RST interrupts are vectored."
      },
      {
        question: "What is the INTR pin?",
        answer: "INTR is a non-vectored, maskable, and lowest-priority interrupt. When triggered, the microprocessor expects the external interrupting device to supply the opcode for the ISR address (usually a RST instruction)."
      },
      {
        question: "What is the 8259A Programmable Interrupt Controller (PIC)?",
        answer: "The 8259A is an IC used to expand the interrupt handling capabilities of a microprocessor. It manages up to 8 hardware interrupts and provides their vector addresses to the CPU."
      },
      {
        question: "Can multiple 8259A chips be used together?",
        answer: "Yes, 8259A chips can be cascaded (one master and up to eight slaves) to manage up to 64 hardware interrupts in a single microcomputer system."
      },
      {
        question: "What is the 8255A Programmable Peripheral Interface (PPI)?",
        answer: "The 8255A is a widely used multi-port I/O device. It provides three 8-bit programmable I/O ports (Port A, Port B, and Port C) to interface peripheral devices with the microprocessor."
      },
      {
        question: "Explain Mode 0 of the 8255A.",
        answer: "Mode 0 is the Basic I/O mode. It provides simple input and output operations for each of the three ports, without handshaking signals."
      },
      {
        question: "Explain Mode 1 of the 8255A.",
        answer: "Mode 1 is the Strobed I/O mode. Ports A and B function as input or output ports, while Port C lines are used for handshaking (control signals) to synchronize data transfer."
      },
      {
        question: "Explain Mode 2 of the 8255A.",
        answer: "Mode 2 is the Bidirectional Bus mode. Only Port A can be configured in this mode to act as a bidirectional data bus, using Port C lines for handshaking."
      },
      {
        question: "What is the BSR Mode in 8255A?",
        answer: "BSR stands for Bit Set/Reset mode. It is used exclusively to set or reset individual bits of Port C without affecting the other bits."
      },
      {
        question: "What is the Control Word Register (CWR) in 8255A?",
        answer: "The CWR is an internal register where the microprocessor writes an 8-bit command (Control Word) to define the operating modes and input/output directions of Ports A, B, and C."
      },
      {
        question: "How does the microprocessor distinguish between the 8255A's ports and CWR?",
        answer: "The 8255A has two address pins, A0 and A1. By providing the combinations 00, 01, 10, and 11, the microprocessor selects Port A, Port B, Port C, and the CWR respectively."
      },
      {
        question: "What is SIM instruction in 8085?",
        answer: "SIM (Set Interrupt Mask) is used to mask or unmask the RST 7.5, 6.5, and 5.5 hardware interrupts and to implement serial data output (SOD)."
      },
      {
        question: "What is RIM instruction in 8085?",
        answer: "RIM (Read Interrupt Mask) reads the current status of the interrupt masks, pending interrupts, and receives serial data input (SID)."
      },
      {
        question: "What is EI and DI?",
        answer: "EI (Enable Interrupts) turns on the master interrupt flip-flop, allowing maskable interrupts to be recognized. DI (Disable Interrupts) turns it off, ignoring all maskable interrupts."
      },
      {
        question: "What happens on receiving INTR?",
        answer: "The 8085 completes its current instruction, outputs an INTA' (Interrupt Acknowledge) signal, reads the opcode provided by the peripheral on the data bus, and executes it to reach the ISR."
      }
    ],
    mcqs: [
      {
        question: "Which of the following is a non-maskable interrupt?",
        options: ["INTR", "RST 7.5", "RST 6.5", "TRAP"],
        correctAnswer: "TRAP"
      },
      {
        question: "Which hardware interrupt has the highest priority?",
        options: ["TRAP", "RST 7.5", "RST 5.5", "INTR"],
        correctAnswer: "TRAP"
      },
      {
        question: "Which hardware interrupt has the lowest priority?",
        options: ["TRAP", "RST 7.5", "RST 5.5", "INTR"],
        correctAnswer: "INTR"
      },
      {
        question: "What does ISR stand for?",
        options: ["Instruction Service Routine", "Interrupt Service Routine", "Internal Signal Reset", "Interrupt Set Request"],
        correctAnswer: "Interrupt Service Routine"
      },
      {
        question: "Which of the following is a non-vectored interrupt?",
        options: ["TRAP", "RST 7.5", "INTR", "RST 5.5"],
        correctAnswer: "INTR"
      },
      {
        question: "What IC is known as the Programmable Interrupt Controller (PIC)?",
        options: ["8255", "8259", "8253", "8237"],
        correctAnswer: "8259"
      },
      {
        question: "A single 8259A PIC can handle how many hardware interrupts?",
        options: ["4", "8", "16", "64"],
        correctAnswer: "8"
      },
      {
        question: "What IC is known as the Programmable Peripheral Interface (PPI)?",
        options: ["8259A", "8255A", "8251A", "8086"],
        correctAnswer: "8255A"
      },
      {
        question: "How many 8-bit I/O ports does the 8255A have?",
        options: ["2", "3", "4", "5"],
        correctAnswer: "3"
      },
      {
        question: "Which 8255A mode is called Strobed I/O?",
        options: ["Mode 0", "Mode 1", "Mode 2", "BSR Mode"],
        correctAnswer: "Mode 1"
      },
      {
        question: "Which mode of 8255A allows bidirectional data transfer on Port A?",
        options: ["Mode 0", "Mode 1", "Mode 2", "Mode 3"],
        correctAnswer: "Mode 2"
      },
      {
        question: "BSR mode in 8255A is used to manipulate the bits of which port?",
        options: ["Port A", "Port B", "Port C", "Control Word Register"],
        correctAnswer: "Port C"
      },
      {
        question: "Which instruction enables the master interrupt flip-flop?",
        options: ["SIM", "RIM", "EI", "DI"],
        correctAnswer: "EI"
      },
      {
        question: "Which instruction disables all maskable interrupts?",
        options: ["HLT", "NOP", "DI", "SIM"],
        correctAnswer: "DI"
      },
      {
        question: "Which instruction is used to set the mask for RST interrupts?",
        options: ["RIM", "SIM", "EI", "DI"],
        correctAnswer: "SIM"
      },
      {
        question: "The interrupt vector address for RST 7.5 is calculated as:",
        options: ["7.5 * 0008H", "7.5 * 0004H", "7 * 0008H", "7 * 0004H"],
        correctAnswer: "7.5 * 0008H"
      },
      {
        question: "TRAP is also known by which RST name?",
        options: ["RST 1", "RST 4.5", "RST 5.5", "RST 8"],
        correctAnswer: "RST 4.5"
      },
      {
        question: "Which signal is sent by the 8085 to accept an INTR request?",
        options: ["HOLD", "HLDA", "INTA'", "ALE"],
        correctAnswer: "INTA'"
      },
      {
        question: "To configure the 8255A, the CPU writes data to the:",
        options: ["Port A", "Port B", "Control Word Register", "Status Register"],
        correctAnswer: "Control Word Register"
      },
      {
        question: "In 8255A Mode 0, Port C can be used as:",
        options: ["One 8-bit port", "Two 4-bit ports", "Handshake lines only", "Bidirectional bus"],
        correctAnswer: "Two 4-bit ports"
      }
    ]
  },
  {
    chapterNumber: 8,
    chapterName: "Advanced Microprocessors",
    questions: [
      {
        question: "What is the 8086 microprocessor?",
        answer: "The 8086 is a 16-bit microprocessor introduced by Intel. It has a 16-bit data bus, a 20-bit address bus (allowing access to 1 MB of memory), and runs faster than the 8085."
      },
      {
        question: "What are the two main functional units of the 8086?",
        answer: "The 8086 architecture is divided into two independent units: the Bus Interface Unit (BIU) and the Execution Unit (EU)."
      },
      {
        question: "What is the role of the Bus Interface Unit (BIU)?",
        answer: "The BIU handles all data and address transfers on the buses. It fetches instructions, reads/writes data to memory and I/O, and computes the 20-bit physical addresses."
      },
      {
        question: "What is the role of the Execution Unit (EU)?",
        answer: "The EU decodes and executes the instructions. It contains the ALU, general-purpose registers, pointer/index registers, and the flag register."
      },
      {
        question: "What is Pipelining in the 8086?",
        answer: "Pipelining is a technique where the BIU pre-fetches up to 6 bytes of instruction code and stores them in an instruction queue. This allows the EU to execute while the BIU fetches, significantly increasing processing speed."
      },
      {
        question: "What is Memory Segmentation in 8086?",
        answer: "Segmentation divides the 1 MB memory into logical 64 KB blocks called segments. The four main segments are Code, Data, Stack, and Extra segments."
      },
      {
        question: "Why does the 8086 use memory segmentation?",
        answer: "Because internal registers are 16-bit, they can only address 64 KB directly. Segmentation allows these 16-bit registers (like IP) to access the entire 20-bit (1 MB) address space by combining them with Segment registers."
      },
      {
        question: "How is the 20-bit physical address calculated in 8086?",
        answer: "Physical Address = (Segment Register value × 10H) + Offset value. The segment register is shifted left by 4 bits and added to the 16-bit offset."
      },
      {
        question: "What are Minimum and Maximum modes in 8086?",
        answer: "Minimum mode (MN/MX' high) configures the 8086 for single-processor systems, generating its own control signals. Maximum mode (low) configures it for multi-processor systems, requiring an external bus controller (8288)."
      },
      {
        question: "What are the key features of the 80286 microprocessor?",
        answer: "The 80286 is a 16-bit microprocessor with a 24-bit address bus (accessing 16 MB). It introduced the 'Protected Mode', supporting memory protection, virtual memory, and multitasking."
      },
      {
        question: "What is Protected Mode?",
        answer: "Protected mode enforces memory protection and access rights, preventing application programs from crashing the OS or reading other programs' memory. It uses segment descriptors instead of direct addresses."
      },
      {
        question: "What are the key features of the 80386 microprocessor?",
        answer: "The 80386 is Intel's first 32-bit microprocessor. It has 32-bit registers, a 32-bit data bus, and a 32-bit address bus, allowing it to address up to 4 GB of physical memory."
      },
      {
        question: "What is a Segment Descriptor?",
        answer: "A segment descriptor is an 8-byte data structure used in Protected Mode (80286/386) that contains the base address, limit (size), and access rights (privileges) of a memory segment."
      },
      {
        question: "What is a Descriptor Table?",
        answer: "A Descriptor Table is an array of segment descriptors stored in memory. The CPU uses it to translate logical addresses to physical addresses and enforce protection rules."
      },
      {
        question: "What are the GDT and LDT?",
        answer: "The Global Descriptor Table (GDT) contains descriptors available to all tasks in the system (like the OS kernel). The Local Descriptor Table (LDT) contains descriptors private to a specific user task."
      },
      {
        question: "What is a Selector?",
        answer: "In protected mode, segment registers hold a 16-bit 'Selector' instead of a base address. The selector acts as an index into the Descriptor Table to pick the correct segment descriptor."
      },
      {
        question: "What is the Instruction Pointer (IP) in 8086?",
        answer: "The IP is a 16-bit register in the EU that holds the offset address of the next instruction within the Code Segment (CS). It is analogous to the Program Counter in the 8085."
      },
      {
        question: "Name the segment registers in 8086.",
        answer: "The four segment registers are CS (Code Segment), DS (Data Segment), SS (Stack Segment), and ES (Extra Segment)."
      },
      {
        question: "What is Virtual Memory?",
        answer: "Virtual memory is a memory management capability allowing a system to appear to have more memory than physically exists, by swapping data between RAM and disk. Supported by 80286 and 80386."
      },
      {
        question: "How does 80386 differ from 80286 in segmentation?",
        answer: "While 80286 segments are limited to 64 KB, the 80386 allows segments to be as large as 4 GB. The 80386 also introduced paging hardware for advanced virtual memory management."
      }
    ],
    mcqs: [
      {
        question: "The 8086 microprocessor is a:",
        options: ["8-bit processor", "16-bit processor", "32-bit processor", "64-bit processor"],
        correctAnswer: "16-bit processor"
      },
      {
        question: "How much physical memory can the 8086 access?",
        options: ["64 KB", "1 MB", "16 MB", "4 GB"],
        correctAnswer: "1 MB"
      },
      {
        question: "The 8086 is internally divided into which two units?",
        options: ["ALU and CU", "Memory and I/O", "BIU and EU", "Registers and Stack"],
        correctAnswer: "BIU and EU"
      },
      {
        question: "Which component of 8086 allows instruction pre-fetching?",
        options: ["ALU", "Instruction Queue", "Flag Register", "Segment Register"],
        correctAnswer: "Instruction Queue"
      },
      {
        question: "The technique of fetching the next instruction while executing the current one is called:",
        options: ["Multitasking", "Paging", "Pipelining", "Segmentation"],
        correctAnswer: "Pipelining"
      },
      {
        question: "Memory in 8086 is divided into logical blocks of 64KB called:",
        options: ["Pages", "Blocks", "Sectors", "Segments"],
        correctAnswer: "Segments"
      },
      {
        question: "To calculate the 20-bit physical address, the Segment Register value is shifted left by:",
        options: ["2 bits", "4 bits", "8 bits", "16 bits"],
        correctAnswer: "4 bits"
      },
      {
        question: "If CS = 1000H and IP = 0005H, what is the physical address?",
        options: ["10005H", "10050H", "1005H", "01005H"],
        correctAnswer: "10005H"
      },
      {
        question: "Which pin determines if the 8086 operates in minimum or maximum mode?",
        options: ["READY", "MN/MX'", "HOLD", "TEST'"],
        correctAnswer: "MN/MX'"
      },
      {
        question: "Maximum mode of 8086 is used for:",
        options: ["Single processor systems", "Multiprocessor systems", "Saving power", "Accessing more memory"],
        correctAnswer: "Multiprocessor systems"
      },
      {
        question: "Which microprocessor introduced the 'Protected Mode'?",
        options: ["8085", "8086", "80286", "8088"],
        correctAnswer: "80286"
      },
      {
        question: "The 80386 is a:",
        options: ["8-bit processor", "16-bit processor", "32-bit processor", "64-bit processor"],
        correctAnswer: "32-bit processor"
      },
      {
        question: "How much physical memory can the 80386 access?",
        options: ["1 MB", "16 MB", "4 GB", "64 GB"],
        correctAnswer: "4 GB"
      },
      {
        question: "In protected mode, what holds the base address and access rights of a segment?",
        options: ["Segment Register", "Descriptor", "Selector", "Offset"],
        correctAnswer: "Descriptor"
      },
      {
        question: "Which table stores the descriptors for the operating system kernel?",
        options: ["GDT", "LDT", "IDT", "Page Table"],
        correctAnswer: "GDT"
      },
      {
        question: "In protected mode, a segment register contains a:",
        options: ["20-bit physical address", "16-bit base address", "16-bit selector", "32-bit physical address"],
        correctAnswer: "16-bit selector"
      },
      {
        question: "Which segment register is paired with the Instruction Pointer (IP)?",
        options: ["DS", "SS", "CS", "ES"],
        correctAnswer: "CS"
      },
      {
        question: "The size of a Segment Descriptor in 80286/80386 is:",
        options: ["2 bytes", "4 bytes", "8 bytes", "16 bytes"],
        correctAnswer: "8 bytes"
      },
      {
        question: "Which processor first introduced paging unit hardware?",
        options: ["8086", "80286", "80386", "Pentium"],
        correctAnswer: "80386"
      },
      {
        question: "Which segment register is paired with the Stack Pointer (SP)?",
        options: ["CS", "ES", "DS", "SS"],
        correctAnswer: "SS"
      }
    ]
  }
];