export interface VivaQuestion {
question: string;
answer: string;
}

export interface MCQ {
question: string;
options: string[];
answer: string;
}

export interface ChapterData {
chapterNumber: number;
chapterName: string;
vivaQuestions: VivaQuestion[];
mcqs: MCQ[];
}

export interface SubjectData {
subjectName: string;
totalChapters: number;
chapters: ChapterData[];
}

export const gtuSoftwareEngineeringViva: SubjectData = {
subjectName: "SOFTWARE ENGINEERING",
totalChapters: 10,
chapters: [
{
chapterNumber: 1,
chapterName: "Introduction to Software and Software Engineering",
vivaQuestions: [
{ question: "What is Software Engineering?", answer: "Sir, Software Engineering is a systematic, disciplined, and quantifiable approach to the development, operation, and maintenance of software. It applies engineering principles to software creation." },
{ question: "What do you mean by Software Crisis?", answer: "Yes sir, the software crisis refers to the historical difficulty in writing useful and efficient computer programs in the required time, often resulting in projects running over budget or failing completely." },
{ question: "What are Software Myths?", answer: "Sir, software myths are false beliefs or misconceptions about software development, like thinking that adding more programmers to a delayed project will speed it up." },
{ question: "Can you explain the Waterfall Model?", answer: "Certainly. The Waterfall Model is a linear sequential life cycle model where each phase must be completed before the next one begins, flowing steadily downwards like a waterfall." },
{ question: "When should we use the Prototyping Model?", answer: "Sir, we should use the Prototyping model when the exact requirements of the system are not clear or well understood by the customer at the beginning." },
{ question: "What is the RAD model?", answer: "Yes sir, RAD stands for Rapid Application Development. It is an incremental process model that emphasizes extremely short development cycles using component-based construction." },
{ question: "What is the Evolutionary Process Model?", answer: "Sir, evolutionary models are iterative. They are designed to accommodate software that evolves over time, such as the Spiral Model which combines iteration with systematic aspects of the waterfall model." },
{ question: "What is the Spiral Model?", answer: "Sir, the Spiral Model is a risk-driven process model. It combines features of the prototyping and waterfall models, focusing heavily on risk analysis in each loop or iteration." },
{ question: "What is Component-Based Development?", answer: "Sir, it is a process that focuses on integrating pre-existing software components to build a system, rather than developing everything from scratch, which saves time and effort." },
{ question: "Define Process, Product, and People in SE.", answer: "Sir, the Process is the framework of tasks to build software, the Product is the final software delivered to the client, and People are the stakeholders and developers involved." },
{ question: "What is the difference between a program and a software product?", answer: "Sir, a program is just source code. A software product includes the program, documentation, operating procedures, and configuration data needed to make the program operate correctly." },
{ question: "What are the characteristics of software?", answer: "Sir, unlike hardware, software is engineered, not manufactured. It does not wear out over time, and it is largely custom-built rather than assembled from existing components." },
{ question: "What is a Layered Technology in SE?", answer: "Sir, SE is considered a layered technology consisting of tools, methods, process, and a bedrock focus on quality." },
{ question: "What is the main drawback of the Waterfall model?", answer: "Sir, its biggest drawback is its rigidity. It is very difficult to go back and change requirements once a phase is completed without incurring high costs." },
{ question: "What is an iterative process?", answer: "Sir, an iterative process develops software in repeated cycles or iterations, allowing the team to learn and refine the software as it is being built." },
{ question: "What is Agile Process Model?", answer: "Sir, Agile is an iterative approach that focuses on flexibility, customer collaboration, and rapid delivery of working software in small increments." },
{ question: "Why does software not 'wear out'?", answer: "Sir, hardware wears out due to environmental factors like dust and heat. Software is logical, so it doesn't degrade physically, though it may deteriorate due to bad modifications." },
{ question: "What is the role of tools in SE?", answer: "Sir, software engineering tools provide automated or semi-automated support for the process and methods, like IDEs and version control systems." },
{ question: "What is system engineering?", answer: "Sir, before software engineering begins, system engineering focuses on analyzing the entire system, including hardware, software, people, and databases, to understand how they interact." },
{ question: "What is the biggest cause of software project failure?", answer: "Sir, the biggest causes are usually poorly defined requirements, lack of user involvement, and poor project management." }
],
mcqs: [
{ question: "Which is not a characteristic of software?", options: ["Software does not wear out", "Software is manufactured", "Software is engineered", "Software is custom-built"], answer: "Software is manufactured" },
{ question: "The Waterfall model is also known as:", options: ["Linear Sequential Model", "Iterative Model", "RAD Model", "Spiral Model"], answer: "Linear Sequential Model" },
{ question: "Which model focuses heavily on risk analysis?", options: ["Waterfall", "RAD", "Spiral", "Prototype"], answer: "Spiral" },
{ question: "RAD stands for:", options: ["Rapid Application Development", "Relative Application Design", "Rapid Application Design", "Recent Application Development"], answer: "Rapid Application Development" },
{ question: "Which is an evolutionary process model?", options: ["Waterfall", "Linear", "Spiral", "RAD"], answer: "Spiral" },
{ question: "Prototyping is best when:", options: ["Requirements are fixed", "Requirements are unclear", "Project is short", "Team is large"], answer: "Requirements are unclear" },
{ question: "Software Engineering is a:", options: ["Layered technology", "Hardware process", "Testing tool", "Programming language"], answer: "Layered technology" },
{ question: "Component-based development focuses on:", options: ["Writing new code", "Reusability", "Hardware setup", "Testing only"], answer: "Reusability" },
{ question: "The first phase of the Waterfall model is:", options: ["Design", "Coding", "Requirement Analysis", "Testing"], answer: "Requirement Analysis" },
{ question: "Which layer is the foundation of SE?", options: ["Tools", "Methods", "Process", "Quality focus"], answer: "Quality focus" },
{ question: "Software myths are:", options: ["True facts", "Misleading attitudes", "Testing strategies", "Design patterns"], answer: "Misleading attitudes" },
{ question: "The outcome of a software project is a:", options: ["Process", "Product", "Paradigm", "People"], answer: "Product" },
{ question: "Which model is suitable for small projects with fixed requirements?", options: ["Spiral", "Waterfall", "Agile", "RAD"], answer: "Waterfall" },
{ question: "Iterative enhancement is a feature of:", options: ["Waterfall", "Spiral", "Evolutionary models", "Both B and C"], answer: "Both B and C" },
{ question: "SE tools provide:", options: ["Automated support", "Manual coding", "Hardware", "Bugs"], answer: "Automated support" },
{ question: "Which of these is NOT a software myth?", options: ["Adding people speeds up project", "Software is easy to change", "Hardware is cheaper than software", "Testing is the only quality check"], answer: "Hardware is cheaper than software" },
{ question: "A working version of software for demonstration is a:", options: ["Final product", "Prototype", "Component", "Method"], answer: "Prototype" },
{ question: "Agile processes prioritize:", options: ["Documentation", "Individuals and interactions", "Strict plans", "Tools"], answer: "Individuals and interactions" },
{ question: "The software crisis was recognized in which decade?", options: ["1950s", "1960s", "1990s", "2010s"], answer: "1960s" },
{ question: "What does the 'Method' layer provide?", options: ["How-to's for building software", "Hardware support", "Automation", "Quality"], answer: "How-to's for building software" }
]
},
{
chapterNumber: 2,
chapterName: "Agile Development",
vivaQuestions: [
{ question: "What is Agile Development?", answer: "Sir, Agile is a software development methodology that promotes continuous iteration of development and testing throughout the software development lifecycle." },
{ question: "What is Agility in software?", answer: "Yes sir, agility is the ability to adapt and respond to changes quickly and effectively, prioritizing working software and customer collaboration." },
{ question: "What is Extreme Programming (XP)?", answer: "Sir, XP is an Agile framework that aims to produce higher quality software through practices like pair programming, test-driven development, and frequent releases." },
{ question: "Can you name some Agile process models besides XP?", answer: "Yes sir, some other popular Agile models include Scrum, Kanban, Crystal, and Feature-Driven Development (FDD)." },
{ question: "What is Pair Programming?", answer: "Sir, pair programming is an XP practice where two developers work together at one workstation. One writes the code while the other reviews it simultaneously." },
{ question: "What is a 'Sprint' in Agile?", answer: "Sir, a sprint is a short, time-boxed period (usually 1 to 4 weeks) during which a specific set of work must be completed and made ready for review." },
{ question: "What is the Agile Manifesto?", answer: "Sir, it is a formal proclamation of 4 core values and 12 principles that guide an iterative and people-centric approach to software development." },
{ question: "How does Agile differ from Waterfall?", answer: "Sir, Waterfall is rigid and sequential, meaning you can't easily go back. Agile is flexible, iterative, and welcomes changing requirements even late in development." },
{ question: "What is Test-Driven Development (TDD)?", answer: "Sir, TDD is a practice where developers write automated test cases before they write the actual code to fulfill that test." },
{ question: "What is Refactoring?", answer: "Sir, refactoring is the process of restructuring existing computer code without changing its external behavior, mainly to improve readability and reduce complexity." },
{ question: "What is continuous integration?", answer: "Sir, it is an agile practice where developers frequently merge their code changes into a central repository, followed by automated builds and tests." },
{ question: "What is the role of the customer in Agile?", answer: "Sir, in Agile, the customer or product owner is heavily involved throughout the project, providing continuous feedback to ensure the product meets their needs." },
{ question: "What is a Daily Stand-up?", answer: "Sir, it is a short, usually 15-minute daily meeting where team members discuss what they did yesterday, what they will do today, and any blockers they face." },
{ question: "What is a User Story?", answer: "Sir, a user story is a short, simple description of a feature told from the perspective of the person who desires the new capability, usually a user or customer." },
{ question: "What are Agile tools?", answer: "Sir, Agile tools are software applications like Jira, Trello, or Rally that help teams manage projects, track tasks, and collaborate effectively." },
{ question: "What does working software over comprehensive documentation mean?", answer: "Sir, it means that while documentation is useful, the primary measure of progress and success in Agile is delivering functional, working software to the user." },
{ question: "What is the Product Backlog?", answer: "Sir, the product backlog is a prioritized list of everything that is known to be needed in the product, managed by the Product Owner." },
{ question: "What is Sprint Planning?", answer: "Sir, it is a meeting at the beginning of a sprint where the team determines which items from the product backlog they will complete during that sprint." },
{ question: "What is Scrum?", answer: "Sir, Scrum is one of the most popular Agile frameworks, emphasizing teamwork, accountability, and iterative progress toward a well-defined goal." },
{ question: "Why is Agile preferred for dynamic projects?", answer: "Sir, because Agile's iterative nature makes it highly responsive to changing market conditions and evolving client requirements." }
],
mcqs: [
{ question: "Agile values emphasize:", options: ["Processes over people", "Individuals and interactions over processes", "Tools over individuals", "Documentation over software"], answer: "Individuals and interactions over processes" },
{ question: "XP stands for:", options: ["Extreme Programming", "Extra Process", "Extended Programming", "Execution Process"], answer: "Extreme Programming" },
{ question: "Which is a practice of Extreme Programming?", options: ["Heavy documentation", "Pair programming", "No testing", "Yearly releases"], answer: "Pair programming" },
{ question: "In Agile, the primary measure of progress is:", options: ["Documentation", "Working software", "Lines of code", "Hours worked"], answer: "Working software" },
{ question: "Scrum is a type of:", options: ["Database", "Agile process model", "Testing tool", "Hardware"], answer: "Agile process model" },
{ question: "Writing tests before writing code is known as:", options: ["Refactoring", "Pair programming", "Test-Driven Development", "Debugging"], answer: "Test-Driven Development" },
{ question: "Improving internal code structure without changing behavior is:", options: ["Refactoring", "Testing", "Deploying", "Compiling"], answer: "Refactoring" },
{ question: "A short, daily team meeting in Agile is called a:", options: ["Sprint", "Stand-up", "Retrospective", "Review"], answer: "Stand-up" },
{ question: "Agile welcomes changing requirements:", options: ["Never", "Only at the start", "Even late in development", "Only during testing"], answer: "Even late in development" },
{ question: "A requirement written from the user's perspective is a:", options: ["Use case", "Test case", "User story", "Function point"], answer: "User story" },
{ question: "Which tool is commonly used for Agile project management?", options: ["Jira", "Eclipse", "Visual Studio", "Photoshop"], answer: "Jira" },
{ question: "In Scrum, the iterative cycle is called a:", options: ["Loop", "Sprint", "Phase", "Run"], answer: "Sprint" },
{ question: "Merging code to a shared repository frequently is:", options: ["Continuous Delivery", "Continuous Integration", "Refactoring", "Pairing"], answer: "Continuous Integration" },
{ question: "The list of prioritized features to be built is the:", options: ["Sprint Backlog", "Product Backlog", "User Story", "Codebase"], answer: "Product Backlog" },
{ question: "Customer involvement in Agile is:", options: ["Low", "Continuous", "Only at the end", "None"], answer: "Continuous" },
{ question: "Agile teams are typically:", options: ["Self-organizing", "Dictated by managers", "Disconnected", "Very large"], answer: "Self-organizing" },
{ question: "Which is NOT an Agile framework?", options: ["Scrum", "Crystal", "Waterfall", "XP"], answer: "Waterfall" },
{ question: "Pair programming requires how many developers?", options: ["One", "Two", "Three", "An entire team"], answer: "Two" },
{ question: "Agile focuses on delivering software in:", options: ["One final release", "Small increments", "Paper documents", "Hardware modules"], answer: "Small increments" },
{ question: "The Agile Manifesto contains how many principles?", options: ["4", "10", "12", "14"], answer: "12" }
]
},
{
chapterNumber: 3,
chapterName: "Managing Software Project",
vivaQuestions: [
{ question: "What are Software Metrics?", answer: "Sir, software metrics are quantitative measures of the degree to which a software system, component, or process possesses a given attribute, helping in evaluation and estimation." },
{ question: "What is the difference between Process and Product Metrics?", answer: "Yes sir, Process metrics measure the characteristics of the development process like effort and time, whereas Product metrics measure the software itself, like lines of code or complexity." },
{ question: "What are Project Metrics?", answer: "Sir, project metrics are used by the project manager to track project status, assess risks, and adjust the workflow to avoid delays or budget overruns." },
{ question: "What is Software Project Estimation?", answer: "Sir, it is the process of predicting the effort, time, and cost required to complete a software project before it actually begins." },
{ question: "What is MS Project Tool used for?", answer: "Sir, MS Project is a software tool used by managers for project planning, scheduling tasks, allocating resources, and tracking the progress of the project." },
{ question: "What is Project Scheduling?", answer: "Sir, project scheduling involves defining tasks, estimating their durations, establishing dependencies among them, and allocating resources to create a timeline for completion." },
{ question: "What is Project Tracking?", answer: "Sir, tracking is comparing the actual progress of the project against the planned schedule to identify deviations and take corrective actions." },
{ question: "What is Risk Analysis in software projects?", answer: "Sir, Risk Analysis is the process of identifying potential threats to the project, evaluating their probability and impact, and deciding how to handle them." },
{ question: "What are the steps of Risk Management?", answer: "Yes sir, the main steps are Risk Identification, Risk Projection (or estimation), Risk Refinement, and Risk Mitigation, Monitoring, and Management (RMMM)." },
{ question: "What is Risk Identification?", answer: "Sir, it is the systematic attempt to specify threats to the project plan, such as team turnover, technology changes, or requirement creep." },
{ question: "What is Risk Projection?", answer: "Sir, also called risk estimation, it attempts to rate each risk in terms of the likelihood of it happening and the consequences if it does occur." },
{ question: "What is Risk Mitigation?", answer: "Sir, risk mitigation refers to the proactive steps taken to reduce the probability or the impact of a risk before it becomes a real problem." },
{ question: "What is an empirical estimation model?", answer: "Sir, empirical models like COCOMO use historical data and formulas based on software size (like LOC) to predict the required effort and duration." },
{ question: "What does LOC stand for?", answer: "Sir, LOC stands for Lines of Code. It is a traditional size-oriented metric used to measure the size of a software product." },
{ question: "What is Function Point (FP) analysis?", answer: "Sir, Function Point is a metric that measures the size and complexity of software based on the functionality it provides to the user, rather than the lines of code." },
{ question: "What is the Critical Path in scheduling?", answer: "Sir, the critical path is the longest sequence of dependent tasks in a project plan that must be completed on time for the project to finish on schedule." },
{ question: "What is a Gantt Chart?", answer: "Sir, a Gantt chart is a bar chart used in project management that provides a visual timeline of tasks, their durations, and dependencies." },
{ question: "What is Risk Refinement?", answer: "Sir, risk refinement involves breaking down a general risk into more specific, detailed risks so they can be managed and mitigated more effectively." },
{ question: "Why is tracking important?", answer: "Sir, without tracking, a project manager wouldn't know if a project is on schedule or over budget, making it impossible to take corrective actions in time." },
{ question: "What happens if a risk becomes a reality?", answer: "Sir, if a risk occurs, the project manager activates the contingency plan or risk management plan prepared during the RMMM phase to handle the situation." }
],
mcqs: [
{ question: "Metrics used to assess the development process are called:", options: ["Product metrics", "Process metrics", "Project metrics", "Quality metrics"], answer: "Process metrics" },
{ question: "Lines of Code (LOC) is an example of:", options: ["Process metric", "Project metric", "Product metric", "People metric"], answer: "Product metric" },
{ question: "Which tool is commonly used for Project Planning?", options: ["MS Word", "MS Project", "Eclipse", "Photoshop"], answer: "MS Project" },
{ question: "Predicting the cost and effort of a project is called:", options: ["Scheduling", "Estimation", "Risk Analysis", "Tracking"], answer: "Estimation" },
{ question: "The first step in Risk Management is:", options: ["Risk Projection", "Risk Mitigation", "Risk Identification", "Risk Refinement"], answer: "Risk Identification" },
{ question: "RMMM stands for:", options: ["Risk Mitigation, Monitoring, and Management", "Risk Measurement, Mitigation, and Maintenance", "Risk Monitoring, Measurement, and Mitigation", "None of these"], answer: "Risk Mitigation, Monitoring, and Management" },
{ question: "Assessing the probability and impact of a risk is called:", options: ["Risk Identification", "Risk Mitigation", "Risk Projection", "Risk Control"], answer: "Risk Projection" },
{ question: "A visual bar chart used for project scheduling is:", options: ["Pie Chart", "Gantt Chart", "Flowchart", "UML Diagram"], answer: "Gantt Chart" },
{ question: "Function Points (FP) measure software based on:", options: ["Lines of code", "User functionality", "Number of developers", "Hardware requirements"], answer: "User functionality" },
{ question: "Which metric is size-oriented?", options: ["Function Point", "Lines of Code", "Cyclomatic Complexity", "Defect rate"], answer: "Lines of Code" },
{ question: "Taking steps to reduce a risk's impact is known as:", options: ["Risk Mitigation", "Risk Projection", "Risk Identification", "Risk Acceptance"], answer: "Risk Mitigation" },
{ question: "Comparing actual progress with planned schedule is:", options: ["Estimation", "Tracking", "Refinement", "Planning"], answer: "Tracking" },
{ question: "The longest sequence of dependent tasks is the:", options: ["Critical Path", "Shortest Path", "Risk Path", "Project Path"], answer: "Critical Path" },
{ question: "Which is not a component of Risk Management?", options: ["Identification", "Projection", "Estimation", "Mitigation"], answer: "Estimation" },
{ question: "Project metrics help managers to:", options: ["Write code", "Design databases", "Adjust workflows and track status", "Test software"], answer: "Adjust workflows and track status" },
{ question: "COCOMO is an example of a:", options: ["Testing tool", "Empirical estimation model", "Programming language", "Network protocol"], answer: "Empirical estimation model" },
{ question: "Risk refinement involves:", options: ["Ignoring risks", "Detailing and breaking down risks", "Paying for risks", "Deploying software"], answer: "Detailing and breaking down risks" },
{ question: "Effort in software projects is often measured in:", options: ["Kilometers", "Person-months", "Gigabytes", "Hours per line"], answer: "Person-months" },
{ question: "Which factor affects software estimation?", options: ["Complexity", "Size", "Required reliability", "All of the above"], answer: "All of the above" },
{ question: "MS Project helps mainly with:", options: ["Coding", "Scheduling and Resource Allocation", "Compiling", "Risk Identification"], answer: "Scheduling and Resource Allocation" }
]
},
{
chapterNumber: 4,
chapterName: "Requirement Analysis and Specification",
vivaQuestions: [
{ question: "What is the SRS?", answer: "Yes sir, the full form of SRS is Software Requirement Specification. It is a comprehensive document that describes the expected behavior, constraints, and features of the software to be developed." },
{ question: "What is Requirement Elicitation?", answer: "Sir, elicitation is the process of gathering and discovering requirements from the stakeholders, users, and customers through interviews, surveys, and observations." },
{ question: "What is Requirement Engineering?", answer: "Sir, Requirement Engineering is the broad process of eliciting, analyzing, specifying, validating, and managing the requirements of a software system." },
{ question: "Why is Requirement Analysis important?", answer: "Sir, it is crucial because it resolves conflicts, uncovers ambiguities, and ensures that the development team clearly understands what the client actually wants before coding starts." },
{ question: "What is Requirement Modeling?", answer: "Sir, modeling involves creating visual representations, like Data Flow Diagrams or Use Case diagrams, to translate text-based requirements into a structured, easy-to-understand format." },
{ question: "What are Functional Requirements?", answer: "Sir, functional requirements describe specific behaviors, functions, or tasks the system must perform, like 'the system must allow the user to log in'." },
{ question: "What are Non-Functional Requirements?", answer: "Sir, non-functional requirements define system attributes and constraints such as performance, security, usability, and reliability, rather than specific behaviors." },
{ question: "Who prepares the SRS document?", answer: "Sir, the SRS is typically prepared by a Systems Analyst or a Requirements Engineer in collaboration with the client and stakeholders." },
{ question: "What are the characteristics of a good SRS?", answer: "Sir, a good SRS should be unambiguous, complete, consistent, verifiable, modifiable, and traceable." },
{ question: "What is a Use Case?", answer: "Sir, a use case describes a specific scenario of how an actor (user or external system) interacts with the software to achieve a particular goal." },
{ question: "What is Requirement Validation?", answer: "Sir, validation is the process of checking the SRS against the customer's original needs to ensure that the requirements accurately reflect what they want." },
{ question: "What is a Data Flow Diagram (DFD)?", answer: "Sir, a DFD is a graphical representation used in requirement modeling that shows how data flows through a system, including inputs, outputs, and processes." },
{ question: "What happens if requirements are gathered incorrectly?", answer: "Sir, incorrect requirements lead to building the wrong product, resulting in high costs to fix, project delays, and ultimately client dissatisfaction." },
{ question: "Can the SRS be changed once finalized?", answer: "Sir, yes it can, but it requires a formal Change Control Process to evaluate the impact on cost and schedule before the changes are approved." },
{ question: "What is an actor in a Use Case diagram?", answer: "Sir, an actor represents a human user, a hardware device, or another system that interacts directly with the system being modeled." },
{ question: "What is brainstorming in elicitation?", answer: "Sir, brainstorming is a group technique used during elicitation to generate a large number of creative ideas or solutions for system requirements." },
{ question: "What is traceablity in SRS?", answer: "Sir, traceability means that every requirement can be tracked backward to its origin (like a specific stakeholder) and forward to its corresponding design and test cases." },
{ question: "What is the role of a prototype in requirement analysis?", answer: "Sir, creating a quick prototype helps stakeholders visualize the software, making it easier for them to clarify and refine their requirements." },
{ question: "What does 'unambiguous' mean in an SRS?", answer: "Sir, it means every requirement stated in the SRS has only one possible interpretation, preventing developers from building the wrong feature." },
{ question: "What is requirement management?", answer: "Sir, it is the ongoing process of identifying, documenting, and controlling changes to requirements throughout the project lifecycle." }
],
mcqs: [
{ question: "SRS stands for:", options: ["Software Requirement Specification", "System Requirement Standard", "Software Review Structure", "System Rule Specification"], answer: "Software Requirement Specification" },
{ question: "Gathering requirements from clients is known as:", options: ["Requirement Elicitation", "Requirement Validation", "Requirement Specification", "Requirement Modeling"], answer: "Requirement Elicitation" },
{ question: "Which of the following is a Non-Functional Requirement?", options: ["User login", "Generate report", "System security", "Calculate salary"], answer: "System security" },
{ question: "DFD stands for:", options: ["Data Flow Diagram", "Document Flow Design", "Data File Diagram", "Design For Data"], answer: "Data Flow Diagram" },
{ question: "Checking if requirements meet the customer's actual needs is:", options: ["Elicitation", "Analysis", "Validation", "Modeling"], answer: "Validation" },
{ question: "A scenario describing system interaction by a user is a:", options: ["Use case", "DFD", "Test case", "Class diagram"], answer: "Use case" },
{ question: "A good SRS should NOT be:", options: ["Consistent", "Unambiguous", "Ambiguous", "Verifiable"], answer: "Ambiguous" },
{ question: "Functional requirements describe:", options: ["How fast the system is", "What the system should do", "The color of the UI", "Hardware specs"], answer: "What the system should do" },
{ question: "Which is a technique for requirement elicitation?", options: ["Interviews", "Code reviews", "Unit testing", "Deployment"], answer: "Interviews" },
{ question: "An external entity interacting with the system in a Use Case is called:", options: ["An object", "An actor", "A process", "A data store"], answer: "An actor" },
{ question: "Requirement modeling produces:", options: ["Source code", "Visual representations/diagrams", "Executable files", "Test suites"], answer: "Visual representations/diagrams" },
{ question: "Which requirement deals with system performance?", options: ["Functional", "Non-functional", "Business", "User"], answer: "Non-functional" },
{ question: "The primary output of the requirement analysis phase is the:", options: ["Code", "SRS Document", "Test Plan", "Architecture"], answer: "SRS Document" },
{ question: "Handling changes to requirements over time is called:", options: ["Requirement Management", "Version Control", "Refactoring", "Maintenance"], answer: "Requirement Management" },
{ question: "Which characteristic ensures a requirement's origin can be tracked?", options: ["Completeness", "Consistency", "Traceability", "Modifiability"], answer: "Traceability" },
{ question: "Who primarily consumes the SRS?", options: ["Developers and Testers", "Only the CEO", "End users", "Network administrators"], answer: "Developers and Testers" },
{ question: "Resolving conflicting requirements is done during:", options: ["Requirement Analysis", "Coding", "Testing", "Deployment"], answer: "Requirement Analysis" },
{ question: "Prototyping helps mostly in:", options: ["Writing code faster", "Requirement elicitation and validation", "Server optimization", "Database tuning"], answer: "Requirement elicitation and validation" },
{ question: "The SRS acts as a ______ between the client and development team.", options: ["Compiler", "Contract", "Debugger", "Server"], answer: "Contract" },
{ question: "Requirement engineering does NOT include:", options: ["Elicitation", "Specification", "Validation", "Compiling code"], answer: "Compiling code" }
]
},
{
chapterNumber: 5,
chapterName: "Software Design",
vivaQuestions: [
{ question: "What is Software Design?", answer: "Sir, software design is the process of transforming the requirements specified in the SRS into a blueprint or architecture for constructing the software." },
{ question: "What are Design Principles?", answer: "Sir, design principles are fundamental guidelines that help software engineers create a robust, maintainable, and efficient system architecture." },
{ question: "What is Architectural Design?", answer: "Sir, it defines the overall structure of the software, identifying the major components or modules and how they communicate with one another." },
{ question: "What is Component Level Design?", answer: "Sir, component level design focuses on the internal details of each software component, specifying its data structures, algorithms, and interface." },
{ question: "What is Function Oriented Design?", answer: "Sir, it is a design approach that breaks the system down into smaller, interacting functions or procedures to accomplish tasks." },
{ question: "What is Object Oriented Design (OOD)?", answer: "Yes sir, OOD designs a system based on interacting objects, which contain both data (attributes) and methods (behaviors), promoting reusability." },
{ question: "What is Cohesion?", answer: "Sir, cohesion measures how strongly related and focused the responsibilities of a single module are. High cohesion is desirable." },
{ question: "What is Coupling?", answer: "Sir, coupling measures the degree of interdependence between different modules. Low coupling is desirable to make modules independent." },
{ question: "What is the ideal relationship between coupling and cohesion?", answer: "Sir, a good software design should aim for High Cohesion and Low Coupling to ensure functional independence." },
{ question: "What is Abstraction?", answer: "Sir, abstraction is the concept of hiding complex implementation details and showing only the essential features to the outside world." },
{ question: "What is Information Hiding?", answer: "Sir, it is a design principle where the internal details and data of a module are hidden from other modules, preventing unintended interference." },
{ question: "What is Modularity?", answer: "Sir, modularity is dividing a complex software system into smaller, manageable, and independent pieces called modules." },
{ question: "What is User Interface (UI) Design?", answer: "Sir, UI design focuses on the visual aspects and interactions between the user and the software, aiming for an intuitive and user-friendly experience." },
{ question: "What is Web Application Design?", answer: "Sir, it involves designing the architecture, navigation, and user interface specifically for web-based applications, considering network and browser limitations." },
{ question: "What does UML stand for?", answer: "Sir, UML stands for Unified Modeling Language, which is a standardized graphical language used to visualize, specify, and document object-oriented systems." },
{ question: "What is a Class in OOD?", answer: "Sir, a class is a blueprint or template from which objects are created. It defines the properties and behaviors that the objects will possess." },
{ question: "What is an Object?", answer: "Sir, an object is a runtime instance of a class that encapsulates state and behavior." },
{ question: "What is Refinement in design?", answer: "Sir, refinement is a top-down strategy where you start with a high-level abstract design and progressively elaborate it to reveal more details." },
{ question: "Why is Software Design important?", answer: "Sir, design is the foundation of quality. Without a good design, a system will be unstable, difficult to test, and nearly impossible to maintain." },
{ question: "What is Functional Independence?", answer: "Sir, it is the result of high cohesion and low coupling, meaning a module performs a single specific task and requires little interaction with other modules." }
],
mcqs: [
{ question: "Which is a characteristic of a good software design?", options: ["High Cohesion, Low Coupling", "Low Cohesion, High Coupling", "High Cohesion, High Coupling", "Low Cohesion, Low Coupling"], answer: "High Cohesion, Low Coupling" },
{ question: "OOD stands for:", options: ["Object Oriented Data", "Object Oriented Design", "Open Oriented Design", "Object Order Design"], answer: "Object Oriented Design" },
{ question: "Hiding complex internal details of a module is called:", options: ["Coupling", "Abstraction", "Cohesion", "Modularity"], answer: "Abstraction" },
{ question: "Coupling measures the degree of:", options: ["Internal module strength", "Interdependence between modules", "User satisfaction", "Lines of code"], answer: "Interdependence between modules" },
{ question: "Cohesion measures the degree of:", options: ["Interdependence", "Functional relatedness within a module", "Hardware dependency", "Cost"], answer: "Functional relatedness within a module" },
{ question: "Dividing software into smaller, manageable parts is:", options: ["Modularity", "Coupling", "Refinement", "Abstraction"], answer: "Modularity" },
{ question: "The overall structure of the software is defined in:", options: ["UI Design", "Component Design", "Architectural Design", "Testing"], answer: "Architectural Design" },
{ question: "Function Oriented Design is based on:", options: ["Objects", "Classes", "Functions/Procedures", "Hardware components"], answer: "Functions/Procedures" },
{ question: "Information Hiding helps to:", options: ["Make code faster", "Prevent unintended interference between modules", "Improve UI colors", "Reduce database size"], answer: "Prevent unintended interference between modules" },
{ question: "Which design focuses on human-computer interaction?", options: ["Architectural Design", "Component Design", "User Interface Design", "Database Design"], answer: "User Interface Design" },
{ question: "UML stands for:", options: ["Unified Modeling Language", "Universal Markup Language", "Unified Machine Logic", "User Modeling Language"], answer: "Unified Modeling Language" },
{ question: "An instance of a class is known as:", options: ["Function", "Object", "Variable", "Module"], answer: "Object" },
{ question: "Progressively detailing a design from high-level to low-level is:", options: ["Refactoring", "Refinement", "Abstraction", "Coupling"], answer: "Refinement" },
{ question: "Component-level design occurs:", options: ["Before Requirement Analysis", "After Architectural Design", "During Testing", "After Deployment"], answer: "After Architectural Design" },
{ question: "Functional independence requires:", options: ["Low cohesion", "High coupling", "High cohesion and low coupling", "No modules"], answer: "High cohesion and low coupling" },
{ question: "Web Application Design must heavily consider:", options: ["Printer drivers", "Navigation and network latency", "CPU registers", "Assembly code"], answer: "Navigation and network latency" },
{ question: "The blueprint for constructing software is the:", options: ["Design", "Test Plan", "SRS", "Maintenance Log"], answer: "Design" },
{ question: "Which principle restricts access to a module's local data?", options: ["Modularity", "Information Hiding", "Coupling", "Refinement"], answer: "Information Hiding" },
{ question: "A class encapsulates:", options: ["Only data", "Only behaviors", "Data and behaviors", "Files and folders"], answer: "Data and behaviors" },
{ question: "Design translates requirements into:", options: ["Hardware specs", "A software architecture", "User manuals", "Bug reports"], answer: "A software architecture" }
]
},
{
chapterNumber: 6,
chapterName: "Software Coding & Testing",
vivaQuestions: [
{ question: "What are Coding Standards?", answer: "Sir, coding standards are a set of rules and guidelines that developers follow to ensure code is uniform, readable, and easy to maintain." },
{ question: "What is Code Review?", answer: "Sir, code review is a systematic examination of source code by other developers to find mistakes overlooked in the initial development phase." },
{ question: "What is Software Documentation?", answer: "Sir, documentation is the written text or illustrations that accompany software, providing instructions for developers, testers, and end-users." },
{ question: "What is the primary goal of Software Testing?", answer: "Yes sir, the primary goal of testing is to find errors or defects in the software before it is delivered to the customer." },
{ question: "What is a Test Case?", answer: "Sir, a test case is a specific set of inputs, execution conditions, and expected results developed for a particular objective, like exercising a specific program path." },
{ question: "What is a Test Suite?", answer: "Sir, a test suite is simply a collection or grouping of multiple test cases intended to be executed together to test a software program." },
{ question: "What is Unit Testing?", answer: "Sir, unit testing focuses on verifying the smallest testable parts of an application, typically individual functions or modules, in isolation." },
{ question: "What is Integration Testing?", answer: "Sir, integration testing combines individual units and tests them as a group to expose faults in the interaction and interfaces between integrated modules." },
{ question: "What is System Testing?", answer: "Sir, system testing evaluates the completely integrated system to verify that it meets the specified requirements in an environment similar to production." },
{ question: "What is Regression Testing?", answer: "Sir, regression testing involves re-running previously completed tests after a code change to ensure that the modification has not introduced new bugs." },
{ question: "What is White Box Testing?", answer: "Sir, white box testing, or glass box testing, is a method where the tester has knowledge of the internal code structure and designs tests based on that internal logic." },
{ question: "What is Black Box Testing?", answer: "Sir, black box testing examines the functionality of an application without looking at its internal structures. The tester only knows the expected inputs and outputs." },
{ question: "What is Alpha Testing?", answer: "Sir, alpha testing is simulated or actual operational testing performed by potential users or an independent test team at the developer's site." },
{ question: "What is Beta Testing?", answer: "Sir, beta testing is conducted at the user's site by the end-users themselves in a real-world environment before the final release." },
{ question: "What is Cyclomatic Complexity?", answer: "Sir, cyclomatic complexity is a software metric used to indicate the logical complexity of a program by measuring the number of independent paths through the code." },
{ question: "What does the WinRunner tool do?", answer: "Sir, WinRunner was an automated functional GUI testing tool that allowed users to record and play back user interface interactions." },
{ question: "What is the LoadRunner tool used for?", answer: "Sir, LoadRunner is a performance testing tool used to simulate thousands of users applying load to a system to evaluate its behavior and performance." },
{ question: "How is testing Object-Oriented software different?", answer: "Sir, OO testing focuses on classes and objects rather than individual functions, requiring testing of methods, object interactions, and inheritance." },
{ question: "How do you test Web Applications?", answer: "Sir, web app testing involves checking UI functionality, browser compatibility, security vulnerabilities, database interactions, and load performance." },
{ question: "What is a Stub and a Driver in testing?", answer: "Sir, during integration testing, a Stub acts as a dummy called module, and a Driver acts as a dummy calling module to facilitate testing incomplete systems." }
],
mcqs: [
{ question: "Testing individual functions or modules in isolation is:", options: ["System Testing", "Unit Testing", "Integration Testing", "Beta Testing"], answer: "Unit Testing" },
{ question: "Testing the interaction between combined modules is:", options: ["Unit Testing", "Integration Testing", "White Box Testing", "Regression Testing"], answer: "Integration Testing" },
{ question: "Re-testing the software after making code modifications is called:", options: ["Alpha Testing", "Regression Testing", "Stress Testing", "System Testing"], answer: "Regression Testing" },
{ question: "Testing without knowledge of internal code structure is:", options: ["White Box Testing", "Black Box Testing", "Glass Box Testing", "Code Review"], answer: "Black Box Testing" },
{ question: "White Box Testing is also known as:", options: ["Black Box Testing", "Glass Box Testing", "Beta Testing", "System Testing"], answer: "Glass Box Testing" },
{ question: "A collection of test cases is called a:", options: ["Test Suite", "Test Plan", "Test Log", "Test Strategy"], answer: "Test Suite" },
{ question: "Cyclomatic complexity measures:", options: ["UI colors", "Database size", "Logical complexity of code", "Network speed"], answer: "Logical complexity of code" },
{ question: "Which tool is primarily used for performance and load testing?", options: ["WinRunner", "LoadRunner", "Photoshop", "MS Word"], answer: "LoadRunner" },
{ question: "Testing done by end-users at their own site is:", options: ["Alpha Testing", "Beta Testing", "Unit Testing", "Integration Testing"], answer: "Beta Testing" },
{ question: "Which specifies inputs, execution conditions, and expected results?", options: ["Code guideline", "Test case", "UI Design", "SRS"], answer: "Test case" },
{ question: "The primary objective of software testing is to:", options: ["Show that there are no errors", "Find errors", "Write better code", "Design UI"], answer: "Find errors" },
{ question: "Code review is a form of:", options: ["Dynamic testing", "Static testing", "Load testing", "Black box testing"], answer: "Static testing" },
{ question: "Testing the entire, fully integrated software product is:", options: ["System Testing", "Unit Testing", "Module Testing", "White Box Testing"], answer: "System Testing" },
{ question: "Dummy modules used to call the module being tested are:", options: ["Stubs", "Drivers", "Objects", "Classes"], answer: "Drivers" },
{ question: "Dummy modules called BY the module being tested are:", options: ["Stubs", "Drivers", "Networks", "Hardware"], answer: "Stubs" },
{ question: "Testing Web Apps specifically involves checking:", options: ["CPU temperature", "Browser compatibility", "Assembly code", "Hardware constraints"], answer: "Browser compatibility" },
{ question: "Testing Object Oriented Applications focuses heavily on:", options: ["Global variables", "Classes and Objects", "Procedural loops", "Network packets"], answer: "Classes and Objects" },
{ question: "Coding standards aim to improve:", options: ["Code readability and consistency", "Execution speed", "Hardware performance", "Bug generation"], answer: "Code readability and consistency" },
{ question: "Which metric guarantees all independent paths are tested?", options: ["Basis Path Testing", "Black Box Testing", "Load Testing", "UI Testing"], answer: "Basis Path Testing" },
{ question: "Software documentation is crucial for:", options: ["Compiler optimization", "Future maintenance and usability", "Increasing execution speed", "Decreasing file size"], answer: "Future maintenance and usability" }
]
},
{
chapterNumber: 7,
chapterName: "Quality Assurance and Management",
vivaQuestions: [
{ question: "What is Software Quality Assurance (SQA)?", answer: "Sir, SQA is a planned and systematic set of activities that ensure the software processes and products conform to established requirements and standards." },
{ question: "What is the difference between QA and QC?", answer: "Sir, Quality Assurance (QA) is process-oriented and focuses on preventing defects. Quality Control (QC) is product-oriented and focuses on identifying defects in the final product." },
{ question: "What are Quality Concepts?", answer: "Sir, quality concepts refer to the attributes of software that measure its excellence, like reliability, maintainability, usability, and performance." },
{ question: "What is an FTR?", answer: "Yes sir, FTR stands for Formal Technical Review. It is a class of review conducted by software engineers to uncover errors in function, logic, or implementation." },
{ question: "What is the primary objective of an FTR?", answer: "Sir, the main objective of an FTR is to find errors early in the development lifecycle so they can be fixed before they become expensive to resolve." },
{ question: "Who is involved in an FTR?", answer: "Sir, an FTR typically involves a Review Leader (moderator), the Producer (author of the work), and several Reviewers." },
{ question: "What is Software Reliability?", answer: "Sir, software reliability is defined as the probability of failure-free operation of a computer program in a specified environment for a specified time." },
{ question: "What does ISO 9000 standard specify?", answer: "Sir, ISO 9000 is an international family of standards that outlines criteria for a quality management system, ensuring organizations meet customer and regulatory needs." },
{ question: "What is CMM?", answer: "Sir, CMM stands for Capability Maturity Model. It is a framework used to assess and improve the maturity of an organization's software development process." },
{ question: "How many levels are there in CMM?", answer: "Sir, CMM consists of 5 maturity levels: Initial, Repeatable, Defined, Managed, and Optimizing." },
{ question: "What is the 'Initial' level in CMM?", answer: "Sir, at level 1 (Initial), processes are ad hoc, chaotic, and heavily dependent on individual heroics rather than standard procedures." },
{ question: "What is Six Sigma for Software Engineering?", answer: "Sir, Six Sigma is a data-driven methodology aimed at eliminating defects and reducing variation in processes to achieve near-perfect quality." },
{ question: "What is an SQA Plan?", answer: "Sir, an SQA plan is a document that identifies the SQA activities, standards, guidelines, and procedures to be followed throughout the software project." },
{ question: "What is defect prevention?", answer: "Sir, it is a proactive approach in QA where root causes of past errors are analyzed to improve processes so those errors do not occur again." },
{ question: "Are reviews considered testing?", answer: "Sir, yes, reviews are considered 'static testing' because they evaluate the work product without actually executing the code." },
{ question: "What is 'Conformance to Requirements'?", answer: "Sir, it is a definition of quality meaning the software accurately does what the specified requirements (SRS) state it should do." },
{ question: "How is Software Reliability measured?", answer: "Sir, it is often measured using mathematical and statistical models based on historical failure data, like Mean Time Between Failures (MTBF)." },
{ question: "What is the 'Optimizing' level in CMM?", answer: "Sir, Level 5 (Optimizing) is the highest level, where the organization focuses on continuous process improvement through quantitative feedback." },
{ question: "Why are FTRs restricted in time and participants?", answer: "Sir, keeping meetings under two hours and involving only 3-5 people ensures the review remains focused and productive without wasting resources." },
{ question: "What is a baseline in quality management?", answer: "Sir, a baseline is a fully reviewed and approved work product that serves as a foundation for further development and can only be changed through formal procedures." }
],
mcqs: [
{ question: "SQA stands for:", options: ["System Quality Assurance", "Software Quality Assurance", "Standard Quality Analysis", "Software Quantity Assured"], answer: "Software Quality Assurance" },
{ question: "QA focuses on _____, while QC focuses on _____.", options: ["Process, Product", "Product, Process", "People, Tools", "Tools, People"], answer: "Process, Product" },
{ question: "FTR stands for:", options: ["Fast Technical Review", "Formal Technical Review", "Final Test Record", "File Transfer Request"], answer: "Formal Technical Review" },
{ question: "The primary objective of an FTR is to:", options: ["Appraise developer performance", "Find errors early", "Reduce team size", "Decrease budget"], answer: "Find errors early" },
{ question: "CMM stands for:", options: ["Capability Maturity Model", "Control Management Model", "Coding Maturity Metric", "Common Measurement Model"], answer: "Capability Maturity Model" },
{ question: "How many maturity levels are defined in CMM?", options: ["3", "4", "5", "6"], answer: "5" },
{ question: "Level 1 of CMM is called:", options: ["Defined", "Managed", "Initial", "Optimizing"], answer: "Initial" },
{ question: "Which level of CMM focuses on continuous process improvement?", options: ["Level 1 (Initial)", "Level 2 (Repeatable)", "Level 3 (Defined)", "Level 5 (Optimizing)"], answer: "Level 5 (Optimizing)" },
{ question: "ISO 9000 is related to:", options: ["Network Protocols", "Quality Management Standards", "Programming Syntax", "Hardware Specifications"], answer: "Quality Management Standards" },
{ question: "Probability of failure-free operation for a specified time is called:", options: ["Software Quality", "Software Reliability", "Software Maintenance", "Software Design"], answer: "Software Reliability" },
{ question: "Six Sigma is a methodology primarily used for:", options: ["Increasing code speed", "Eliminating defects and variations", "UI Design", "Network routing"], answer: "Eliminating defects and variations" },
{ question: "Which is a static testing technique?", options: ["Unit Testing", "System Testing", "Formal Technical Review", "Stress Testing"], answer: "Formal Technical Review" },
{ question: "The SQA plan is prepared to:", options: ["Write code", "Define QA activities and standards", "Design databases", "Compile software"], answer: "Define QA activities and standards" },
{ question: "Quality is often defined as:", options: ["Conformance to explicitly stated requirements", "Having many features", "Using the newest language", "Low cost"], answer: "Conformance to explicitly stated requirements" },
{ question: "Who moderates an FTR?", options: ["The Client", "The CEO", "The Review Leader", "The Compiler"], answer: "The Review Leader" },
{ question: "Defect prevention saves:", options: ["Lines of code", "Memory usage", "Time and Cost", "Network bandwidth"], answer: "Time and Cost" },
{ question: "SQA activities are performed:", options: ["Only at the end of the project", "Only during coding", "Throughout the software life cycle", "Before requirements gathering"], answer: "Throughout the software life cycle" },
{ question: "Software reliability is often calculated using:", options: ["Astrology", "Statistical models (like MTBF)", "Lines of code", "Color depth"], answer: "Statistical models (like MTBF)" },
{ question: "An approved specification that can only be changed via formal control is a:", options: ["Bug", "Baseline", "Test case", "Prototype"], answer: "Baseline" },
{ question: "Which of the following is NOT a CMM level?", options: ["Initial", "Repeatable", "Predictable", "Managed"], answer: "Predictable" }
]
},
{
chapterNumber: 8,
chapterName: "Software Maintenance and Configuration Management",
vivaQuestions: [
{ question: "What is Software Maintenance?", answer: "Sir, software maintenance involves modifying a software product after it has been delivered to correct faults, improve performance, or adapt it to a new environment." },
{ question: "What are the four types of Software Maintenance?", answer: "Yes sir, the four types are Corrective, Adaptive, Perfective, and Preventive maintenance." },
{ question: "What is Corrective Maintenance?", answer: "Sir, corrective maintenance is reactive. It involves fixing bugs and errors that are discovered by users after the software has been deployed." },
{ question: "What is Adaptive Maintenance?", answer: "Sir, adaptive maintenance involves modifying the software to keep it usable in a changing environment, such as a new operating system or database." },
{ question: "What is Perfective Maintenance?", answer: "Sir, perfective maintenance enhances the software by adding new features or functionalities based on new user requirements." },
{ question: "What is Preventive Maintenance?", answer: "Sir, preventive maintenance involves making changes to prevent future problems, like restructuring code to make it more maintainable." },
{ question: "What is Reverse Engineering?", answer: "Sir, reverse engineering is the process of analyzing an existing system to identify its components and extract higher-level design or requirements from the source code." },
{ question: "What is Forward Engineering?", answer: "Sir, forward engineering is the normal software engineering process of moving from high-level requirements to design, and finally to implementation." },
{ question: "What is Re-Engineering?", answer: "Sir, re-engineering is examining and altering an existing software system to reconstitute it in a new form, improving its maintainability without changing its core functionality." },
{ question: "What is SCM?", answer: "Sir, SCM stands for Software Configuration Management. It is the discipline of managing and controlling changes to the software throughout its lifecycle." },
{ question: "What is a Software Configuration Item (SCI)?", answer: "Sir, an SCI is any piece of information created as part of the software engineering process, such as a design document, source code file, or test case." },
{ question: "What is Version Control?", answer: "Sir, version control is the management of multiple revisions or versions of software components, ensuring that developers don't overwrite each other's changes." },
{ question: "What is Change Control?", answer: "Sir, change control is a formal process used to ensure that modifications to a system are evaluated, approved, and tracked before they are implemented." },
{ question: "What is a Baseline in SCM?", answer: "Sir, a baseline is a formally reviewed and approved version of an SCI that serves as a stable foundation for further development." },
{ question: "Why does software require maintenance?", answer: "Sir, software requires maintenance because bugs are found, user needs change, business rules evolve, and underlying hardware or operating systems change." },
{ question: "Which phase consumes the most budget in the SDLC?", answer: "Sir, the maintenance phase consumes the vast majority of the budget, often 60% to 80% of total lifecycle costs." },
{ question: "What is the SCM process?", answer: "Sir, the SCM process includes Identification of objects, Version control, Change control, Configuration auditing, and Status reporting." },
{ question: "What does 'Identification of Objects' mean in SCM?", answer: "Sir, it means uniquely naming and organizing all SCIs so they can be easily tracked and managed by the SCM tools." },
{ question: "What is an example of a Version Control tool?", answer: "Sir, Git, SVN (Subversion), and CVS are common version control tools used in the industry." },
{ question: "Why do we re-engineer legacy systems?", answer: "Sir, legacy systems are often critical to business but difficult to maintain. Re-engineering modernizes the code base making future maintenance easier and cheaper." }
],
mcqs: [
{ question: "SCM stands for:", options: ["Software Control Management", "System Code Maintenance", "Software Configuration Management", "Source Configuration Manager"], answer: "Software Configuration Management" },
{ question: "Fixing bugs reported by users after deployment is:", options: ["Adaptive Maintenance", "Preventive Maintenance", "Perfective Maintenance", "Corrective Maintenance"], answer: "Corrective Maintenance" },
{ question: "Modifying software to run on a new Operating System is:", options: ["Corrective Maintenance", "Adaptive Maintenance", "Perfective Maintenance", "Preventive Maintenance"], answer: "Adaptive Maintenance" },
{ question: "Adding a new feature requested by a client is:", options: ["Corrective Maintenance", "Adaptive Maintenance", "Perfective Maintenance", "Preventive Maintenance"], answer: "Perfective Maintenance" },
{ question: "Restructuring code to make it easier to maintain in the future is:", options: ["Corrective Maintenance", "Adaptive Maintenance", "Perfective Maintenance", "Preventive Maintenance"], answer: "Preventive Maintenance" },
{ question: "Extracting design details from existing source code is called:", options: ["Forward Engineering", "Reverse Engineering", "Re-engineering", "Testing"], answer: "Reverse Engineering" },
{ question: "Developing software from requirements to code is called:", options: ["Reverse Engineering", "Re-engineering", "Forward Engineering", "Maintenance"], answer: "Forward Engineering" },
{ question: "Which process manages different versions of software files?", options: ["Change Control", "Version Control", "Quality Control", "Audit Control"], answer: "Version Control" },
{ question: "A document or code file managed by SCM is called an:", options: ["SCI (Software Configuration Item)", "SRS", "FTR", "OOD"], answer: "SCI (Software Configuration Item)" },
{ question: "Evaluating and approving changes before implementation is done via:", options: ["Version Control", "Change Control", "Reverse Engineering", "Testing"], answer: "Change Control" },
{ question: "Which phase typically costs the most in software development?", options: ["Requirements", "Design", "Coding", "Maintenance"], answer: "Maintenance" },
{ question: "A formally approved version of an SCI is a:", options: ["Draft", "Baseline", "Prototype", "Bug"], answer: "Baseline" },
{ question: "Re-engineering is usually applied to:", options: ["Brand new software", "Legacy systems", "Hardware", "Network switches"], answer: "Legacy systems" },
{ question: "Git is a popular tool for:", options: ["UI Design", "Database querying", "Version Control", "Hardware testing"], answer: "Version Control" },
{ question: "The primary purpose of SCM is to manage:", options: ["Change", "Hardware resources", "Developer salaries", "Office space"], answer: "Change" },
{ question: "Which is NOT a phase of the SCM process?", options: ["Identification", "Version Control", "Change Control", "Code Compilation"], answer: "Code Compilation" },
{ question: "Legacy software refers to:", options: ["Newly released software", "Older, existing critical software", "Open source software", "Mobile apps"], answer: "Older, existing critical software" },
{ question: "What provides a stable foundation for further development?", options: ["A bug report", "A baseline", "A rough draft", "A rejected change"], answer: "A baseline" },
{ question: "Change control ensures that changes are:", options: ["Randomly applied", "Evaluated and authorized", "Ignored entirely", "Done without testing"], answer: "Evaluated and authorized" },
{ question: "Reverse engineering is often the first step in:", options: ["Requirement elicitation", "Re-engineering", "Deployment", "Version control"], answer: "Re-engineering" }
]
},
{
chapterNumber: 9,
chapterName: "DevOps: Overview",
vivaQuestions: [
{ question: "What is DevOps?", answer: "Sir, DevOps is a culture, movement, and set of practices that combines software development (Dev) and IT operations (Ops) to shorten the development lifecycle and provide continuous delivery." },
{ question: "What problem does DevOps solve?", answer: "Sir, historically, Dev and Ops teams worked in isolated 'silos', causing delays and conflicts during deployment. DevOps bridges this gap to ensure smooth and fast releases." },
{ question: "What are the benefits of DevOps?", answer: "Sir, benefits include faster time-to-market, higher deployment frequency, lower failure rates, and quicker recovery times when issues occur." },
{ question: "What is Continuous Integration (CI)?", answer: "Sir, CI is a DevOps practice where developers frequently merge code changes into a central repository, which then triggers automated builds and tests." },
{ question: "What is Continuous Testing in DevOps?", answer: "Sir, it means executing automated tests at every stage of the software delivery pipeline to obtain immediate feedback on the business risks associated with a software release." },
{ question: "What is Continuous Delivery/Deployment (CD)?", answer: "Sir, CD ensures that every change that passes automated tests is automatically deployed to a staging or production environment." },
{ question: "What is Infrastructure Automation?", answer: "Sir, also known as Infrastructure as Code (IaC), it is the practice of managing and provisioning computing infrastructure through machine-readable definition files rather than physical hardware configuration." },
{ question: "What is Configuration Management in DevOps?", answer: "Sir, it involves using tools to automate the setup, configuration, and maintenance of servers to ensure consistency across all environments." },
{ question: "Name a tool used for Continuous Integration.", answer: "Sir, Jenkins (formerly Hudson) is one of the most widely used open-source CI automation servers." },
{ question: "Name a tool used for Containerization.", answer: "Sir, Docker is a highly popular tool used to package applications and their dependencies into standardized units called containers." },
{ question: "Name a Configuration Management tool.", answer: "Sir, Chef, Puppet, and SaltStack are popular configuration management tools." },
{ question: "What is Log Management?", answer: "Sir, log management involves centralizing and analyzing logs generated by applications and infrastructure to monitor health and troubleshoot issues quickly." },
{ question: "What does 'Business Agility' mean in the context of DevOps?", answer: "Sir, it refers to a company's ability to quickly adapt and respond to market changes and customer feedback through rapid software releases." },
{ question: "What are the challenges of DevOps implementation?", answer: "Sir, the biggest challenge is the cultural shift required. People resist changing how they work and breaking down long-standing organizational silos." },
{ question: "How do you choose the right DevOps tool?", answer: "Sir, you must assess the project's specific needs, the current technology stack, team skills, and solution dimensions before selecting a tool." },
{ question: "What is a 'Must Do' for DevOps?", answer: "Sir, automating everything—from builds to testing to deployment—is an absolute 'must do' to achieve true DevOps speed and reliability." },
{ question: "What is Deployment Automation?", answer: "Sir, it is the process of automating the movement of code from development environments through testing and ultimately into production without manual intervention." },
{ question: "Why is Measurement and Feedback important in DevOps?", answer: "Sir, continuous measurement of performance metrics and user feedback allows the team to continuously improve both the product and the pipeline processes." },
{ question: "What does DevOps assessment do?", answer: "Sir, an assessment evaluates an organization's current maturity, tools, and culture to create a roadmap for mapping their applications to a DevOps model." },
{ question: "Is DevOps just about tools?", answer: "No sir, while tools are essential, DevOps is primarily a cultural shift focusing on collaboration, communication, and shared responsibility between Dev and Ops." }
],
mcqs: [
{ question: "DevOps primarily combines which two teams?", options: ["Design and Marketing", "Development and Operations", "Sales and Support", "HR and Finance"], answer: "Development and Operations" },
{ question: "The core problem DevOps aims to solve is:", options: ["Lack of hardware", "Silos between Dev and Ops", "Slow internet", "High salaries"], answer: "Silos between Dev and Ops" },
{ question: "Frequent merging of code with automated builds is called:", options: ["Continuous Integration", "Continuous Delivery", "Log Management", "Infrastructure as Code"], answer: "Continuous Integration" },
{ question: "Jenkins (or Hudson) is widely used for:", options: ["UI Design", "Continuous Integration", "Photo Editing", "Database modeling"], answer: "Continuous Integration" },
{ question: "Docker is a tool primarily used for:", options: ["Containerization", "Word Processing", "Spreadsheets", "Network Cabling"], answer: "Containerization" },
{ question: "Chef and SaltStack are tools for:", options: ["Configuration Management", "Image editing", "Code compiling", "Requirement elicitation"], answer: "Configuration Management" },
{ question: "Managing servers through code scripts is known as:", options: ["Manual Setup", "Infrastructure Automation (IaC)", "Reverse Engineering", "Version Control"], answer: "Infrastructure Automation (IaC)" },
{ question: "Which is a major benefit of DevOps?", options: ["Slower releases", "Increased silos", "Faster time-to-market", "More manual testing"], answer: "Faster time-to-market" },
{ question: "Continuous testing in DevOps emphasizes:", options: ["Manual testing at the end", "Automated testing at every stage", "No testing", "Testing only in production"], answer: "Automated testing at every stage" },
{ question: "A primary challenge in adopting DevOps is:", options: ["Cultural resistance and breaking silos", "Writing code", "Buying monitors", "Finding office space"], answer: "Cultural resistance and breaking silos" },
{ question: "Log Management tools help to:", options: ["Monitor application health and troubleshoot", "Design UI layouts", "Write SRS documents", "Compile Java code"], answer: "Monitor application health and troubleshoot" },
{ question: "DevOps increases 'Business Agility', which means:", options: ["Rapid response to market changes", "Doing physical exercises", "Slower decision making", "Ignoring user feedback"], answer: "Rapid response to market changes" },
{ question: "Deployment automation aims to remove:", options: ["Servers", "Source code", "Manual intervention in releasing software", "Developers"], answer: "Manual intervention in releasing software" },
{ question: "Choosing a DevOps tool should be based on:", options: ["Solution dimensions and project needs", "Alphabetical order", "Random selection", "Color of the logo"], answer: "Solution dimensions and project needs" },
{ question: "DevOps is primarily a:", options: ["Programming Language", "Cultural shift and set of practices", "Hardware device", "Operating System"], answer: "Cultural shift and set of practices" },
{ question: "Which is a 'Must Do' in DevOps?", options: ["Automate everything possible", "Keep teams separate", "Deploy manually", "Stop testing"], answer: "Automate everything possible" },
{ question: "Measurement in DevOps allows for:", options: ["Continuous feedback and improvement", "Blaming developers", "Reducing salaries", "Ignoring errors"], answer: "Continuous feedback and improvement" },
{ question: "DevOps assessment helps organizations:", options: ["Fire people", "Evaluate maturity and plan adoption", "Buy computers", "Design algorithms"], answer: "Evaluate maturity and plan adoption" },
{ question: "Which practice ensures passing code goes straight to staging/production?", options: ["Continuous Deployment", "Continuous Design", "Continuous Delay", "Continuous Documentation"], answer: "Continuous Deployment" },
{ question: "The 7 C's of DevOps lifecycle represent:", options: ["Oceans", "Continuous practices (Integration, Testing, etc.)", "Coding languages", "Hardware components"], answer: "Continuous practices (Integration, Testing, etc.)" }
]
},
{
chapterNumber: 10,
chapterName: "Advanced Topics in Software Engineering",
vivaQuestions: [
{ question: "What is Component-Based Software Engineering (CBSE)?", answer: "Sir, CBSE is a process that emphasizes the design and construction of computer-based systems using reusable, 'off-the-shelf' software components." },
{ question: "What does COTS stand for?", answer: "Sir, COTS stands for Commercial Off-The-Shelf. These are ready-made components purchased from vendors and integrated into a system in CBSE." },
{ question: "What is Client/Server Software Engineering?", answer: "Sir, it is the engineering of applications built on a network architecture where client nodes request services and server nodes provide them." },
{ question: "What is Web Engineering?", answer: "Sir, Web Engineering is the application of systematic, disciplined, and quantifiable approaches to the development, operation, and maintenance of Web-based applications." },
{ question: "How is Web Engineering different from traditional SE?", answer: "Sir, Web apps evolve continuously, have highly variable user loads, focus heavily on UI aesthetics, and require rapid development cycles compared to traditional software." },
{ question: "What does CASE stand for?", answer: "Yes sir, CASE stands for Computer-Aided Software Engineering. It refers to software tools that provide automated support for software engineering activities." },
{ question: "What is the purpose of CASE tools?", answer: "Sir, CASE tools aim to increase productivity, improve software quality, and automate repetitive tasks like drawing UML diagrams or generating skeleton code." },
{ question: "Give an example of a CASE tool.", answer: "Sir, Rational Rose for UML modeling or MS Visio are classic examples of CASE tools." },
{ question: "What are Upper CASE and Lower CASE tools?", answer: "Sir, Upper CASE tools support early phases like requirement analysis and design. Lower CASE tools support later phases like coding and testing." },
{ question: "What is Software Process Improvement (SPI)?", answer: "Sir, SPI is the systematic effort to enhance an organization's software development processes to produce higher quality software more efficiently." },
{ question: "How does CMM relate to SPI?", answer: "Sir, the Capability Maturity Model (CMM) provides the framework and roadmap that organizations use to guide their Software Process Improvement efforts." },
{ question: "What is meant by 'Emerging Trends in SE'?", answer: "Sir, emerging trends refer to new paradigms shaping the field, such as Artificial Intelligence in SE, Cloud Computing, Microservices, and advanced DevOps practices." },
{ question: "Why is CBSE beneficial?", answer: "Sir, by reusing pre-tested components, CBSE significantly reduces development time, lowers costs, and improves overall system reliability." },
{ question: "What is a 'Client' in a Client/Server architecture?", answer: "Sir, the client is the front-end machine or software (like a web browser) that interacts with the user and sends requests to the server." },
{ question: "What is a 'Server' in Client/Server?", answer: "Sir, the server is a powerful backend machine that hosts databases or business logic and responds to the requests sent by the clients." },
{ question: "Is reengineering considered an advanced topic?", answer: "Sir, yes, because modernizing massive, complex legacy systems without breaking existing business operations requires advanced planning and specific engineering techniques." },
{ question: "What drives the need for Web Engineering?", answer: "Sir, the massive explosion of the internet and the demand for highly scalable, secure, and interactive web applications necessitate specific Web Engineering methodologies." },
{ question: "What is an integration challenge in CBSE?", answer: "Sir, the main challenge is ensuring that components built by different vendors communicate perfectly and don't introduce security vulnerabilities." },
{ question: "Can CASE tools write the entire software?", answer: "No sir, CASE tools can generate skeleton code or automate tests, but human engineers are still required for complex logic and architectural decisions." },
{ question: "Why must software engineering continue to evolve?", answer: "Sir, SE must evolve because hardware advances, user expectations grow, and business environments change rapidly, requiring faster and more secure software solutions." }
],
mcqs: [
{ question: "CASE stands for:", options: ["Computer-Aided Software Engineering", "Central Application System Engine", "Control And System Engineering", "Common Architecture Software Element"], answer: "Computer-Aided Software Engineering" },
{ question: "CBSE emphasizes the use of:", options: ["Writing code from scratch", "Reusable components", "Only hardware", "Punch cards"], answer: "Reusable components" },
{ question: "COTS stands for:", options: ["Code On Time System", "Commercial Off-The-Shelf", "Component Oriented Testing System", "Centralized Object Technology System"], answer: "Commercial Off-The-Shelf" },
{ question: "Which engineering specifically deals with web-based applications?", options: ["Civil Engineering", "Web Engineering", "Component Engineering", "Hardware Engineering"], answer: "Web Engineering" },
{ question: "In Client/Server architecture, the node providing the service is the:", options: ["Client", "Network", "Server", "Database"], answer: "Server" },
{ question: "SPI stands for:", options: ["System Program Interface", "Software Process Improvement", "Standard Process Implementation", "Software Product Integration"], answer: "Software Process Improvement" },
{ question: "Which tool is an example of a CASE tool used for UML?", options: ["Rational Rose", "VLC Player", "Notepad", "Google Chrome"], answer: "Rational Rose" },
{ question: "Upper CASE tools generally support which phases?", options: ["Analysis and Design", "Coding and Testing", "Maintenance", "Deployment"], answer: "Analysis and Design" },
{ question: "Lower CASE tools generally support which phases?", options: ["Requirements", "Analysis", "Coding and Testing", "Feasibility Study"], answer: "Coding and Testing" },
{ question: "A major benefit of Component-Based SE is:", options: ["Increased development time", "Reduced reusability", "Reduced time-to-market", "Lower quality"], answer: "Reduced time-to-market" },
{ question: "Web applications are unique because they:", options: ["Never change", "Evolve continuously and face variable loads", "Do not use the internet", "Have no UI"], answer: "Evolve continuously and face variable loads" },
{ question: "SPI is often guided by which framework?", options: ["HTML", "HTTP", "CMM", "USB"], answer: "CMM" },
{ question: "The node that requests a service in a C/S network is the:", options: ["Server", "Client", "Router", "Switch"], answer: "Client" },
{ question: "Emerging trends in SE include technologies like:", options: ["Vacuum tubes", "Floppy disks", "Cloud Computing and AI", "Telegraphs"], answer: "Cloud Computing and AI" },
{ question: "Reengineering legacy systems aims to:", options: ["Make them older", "Improve maintainability", "Destroy data", "Increase hardware size"], answer: "Improve maintainability" },
{ question: "CASE tools provide ____ support for SE activities.", options: ["No", "Automated", "Manual", "Negative"], answer: "Automated" },
{ question: "What is a major challenge in CBSE?", options: ["Typing code", "Integrating disparate components", "Buying keyboards", "Choosing UI colors"], answer: "Integrating disparate components" },
{ question: "Web Engineering differs from traditional SE mainly in its:", options: ["Use of compilers", "Focus on continuous evolution and UI", "Use of mathematics", "Ignore of testing"], answer: "Focus on continuous evolution and UI" },
{ question: "Client/Server systems rely heavily on:", options: ["Standalone execution", "Network communication", "Single thread processing", "No databases"], answer: "Network communication" },
{ question: "The ultimate goal of Software Process Improvement is to:", options: ["Produce higher quality software more efficiently", "Write slower code", "Increase budget", "Avoid testing"], answer: "Produce higher quality software more efficiently" }
]
}
]
};