import { ipdcMcqData } from "@/lib/ipdc/mcqs";

export type SearchItemType = "Semester" | "Subject" | "PYQ" | "Notes" | "MCQ";

export type SearchItem = {
  id: string;
  type: SearchItemType;
  title: string;
  subtitle: string;
  url: string;
  keywords: string[];
  badge: string;
};

const semesterItems: SearchItem[] = [
  {
    id: "semester-3",
    type: "Semester",
    title: "Semester 3",
    subtitle: "Core science and communication resources.",
    url: "/semester/3",
    keywords: ["sem 3", "sem3", "s3", "semester three"],
    badge: "Semester",
  },
  {
    id: "semester-4",
    type: "Semester",
    title: "Semester 4",
    subtitle: "Systems, networks, databases, and software resources.",
    url: "/semester/4",
    keywords: ["sem 4", "sem4", "s4", "semester four"],
    badge: "Semester",
  },
  {
    id: "semester-5",
    type: "Semester",
    title: "Semester 5",
    subtitle: "Software design, data science, ethics, and communication.",
    url: "/semester/5",
    keywords: ["sem 5", "sem5", "s5", "semester five"],
    badge: "Semester",
  },
  {
    id: "semester-6",
    type: "Semester",
    title: "Semester 6",
    subtitle: "Advanced core subjects, electives, and project resources.",
    url: "/semester/6",
    keywords: ["sem 6", "sem6", "s6", "semester six"],
    badge: "Semester",
  },
  {
    id: "semester-7",
    type: "Semester",
    title: "Semester 7",
    subtitle: "Emerging technologies, cloud, and project preparation.",
    url: "/semester/7",
    keywords: ["sem 7", "sem7", "s7", "semester seven"],
    badge: "Semester",
  },
  {
    id: "semester-8",
    type: "Semester",
    title: "Semester 8",
    subtitle: "Capstone work, industrial training, and advanced electives.",
    url: "/semester/8",
    keywords: ["sem 8", "sem8", "s8", "semester eight"],
    badge: "Semester",
  },
];

const subjectItems: SearchItem[] = [
  {
    id: "software-engineering",
    type: "Subject",
    title: "Software Engineering",
    subtitle: "Semester 5 core software design and testing.",
    url: "/pyq/software-engineering",
    keywords: ["3150711", "se", "software eng", "software engineering"],
    badge: "Subject",
  },
  {
    id: "python-for-data-science",
    type: "Subject",
    title: "Python for Data Science",
    subtitle: "Semester 5 data science with Python.",
    url: "/pyq/python-for-data-science",
    keywords: ["3150713", "pds", "python data science", "python"],
    badge: "Subject",
  },
  {
    id: "professional-ethics",
    type: "Subject",
    title: "Professional Ethics",
    subtitle: "Semester 5 humanities and engineering responsibility.",
    url: "/pyq/professional-ethics",
    keywords: ["3150709", "pe", "ethical", "ethics"],
    badge: "Subject",
  },
  {
    id: "ipdc-1",
    type: "Subject",
    title: "Integrated Personality Development Course - I",
    subtitle: "Semester 5 IPDC practice and personality growth.",
    url: "/pyq/ipdc-1",
    keywords: ["3150005", "ipdc", "ipdc-1"],
    badge: "Subject",
  },
  {
    id: "design-engineering-iia",
    type: "Subject",
    title: "Design Engineering IIA",
    subtitle: "Semester 5 project work and design planning.",
    url: "/semester/5",
    keywords: ["3150001", "de iia", "design engineering"],
    badge: "Subject",
  },
  {
    id: "computer-networks",
    type: "Subject",
    title: "Computer Networks",
    subtitle: "Semester 5 networks, routing, and protocols.",
    url: "/pyq/computer-networks",
    keywords: ["3150710", "cn", "computer networking", "networks"],
    badge: "Subject",
  },
  {
    id: "analysis-and-design-of-algorithms",
    type: "Subject",
    title: "Analysis and Design of Algorithms",
    subtitle: "Semester 5 algorithm design and complexity.",
    url: "/pyq/analysis-and-design-of-algorithms",
    keywords: ["3150703", "ada", "algorithms"],
    badge: "Subject",
  },
  {
    id: "theory-of-computation",
    type: "Subject",
    title: "Theory of Computation",
    subtitle: "Semester 6 automata, languages, and Turing machines.",
    url: "/pyq/theory-of-computation",
    keywords: ["3160704", "toc", "theory of computation"],
    badge: "Subject",
  },
  {
    id: "advanced-java-programming",
    type: "Subject",
    title: "Advanced Java Programming",
    subtitle: "Semester 6 enterprise Java and application development.",
    url: "/pyq/advanced-java-programming",
    keywords: ["3160707", "ajp", "java programming", "advanced java"],
    badge: "Subject",
  },
  {
    id: "microprocessor-and-interfacing",
    type: "Subject",
    title: "Microprocessor & Interfacing",
    subtitle: "Semester 6 8086 architecture and peripheral interfacing.",
    url: "/pyq/microprocessor-and-interfacing",
    keywords: ["3160710", "mpi", "microprocessor"],
    badge: "Subject",
  },
  {
    id: "web-programming",
    type: "Subject",
    title: "Web Programming",
    subtitle: "Semester 6 full-stack web development.",
    url: "/pyq/web-programming",
    keywords: ["3160713", "wp", "web programming", "web dev"],
    badge: "Subject",
  },
  {
    id: "data-mining",
    type: "Subject",
    title: "Data Mining",
    subtitle: "Semester 6 pattern discovery and analytics.",
    url: "/pyq/data-mining",
    keywords: ["3160714", "data mining", "dm"],
    badge: "Subject",
  },
  {
    id: "system-software",
    type: "Subject",
    title: "System Software",
    subtitle: "Semester 6 assembler, loader, and compiler design.",
    url: "/pyq/system-software",
    keywords: ["3160715", "system software", "compilers"],
    badge: "Subject",
  },
  {
    id: "iot-and-applications",
    type: "Subject",
    title: "IOT & Applications",
    subtitle: "Semester 6 IoT systems, sensors, and cloud integration.",
    url: "/pyq/iot-and-applications",
    keywords: ["3160716", "iot", "internet of things"],
    badge: "Subject",
  },
  {
    id: "data-visualization",
    type: "Subject",
    title: "Data Visualization",
    subtitle: "Semester 6 dashboards and visual analytics.",
    url: "/pyq/data-visualization",
    keywords: ["3160717", "dv", "data visualization"],
    badge: "Subject",
  },
  {
    id: "design-engineering-iib",
    type: "Subject",
    title: "Design Engineering II B",
    subtitle: "Semester 6 project work and prototype development.",
    url: "/semester/6",
    keywords: ["3160001", "de iib", "design engineering iib"],
    badge: "Subject",
  },
  {
    id: "contributor-personality-development-program",
    type: "Subject",
    title: "Contributor Personality",
    subtitle: "Semester 6 humanities and professional development.",
    url: "/pyq/contributor-personality-development-program",
    keywords: ["3160002", "contributor personality", "cp"],
    badge: "Subject",
  },
  {
    id: "ipdc-course",
    type: "Subject",
    title: "IPDC Course",
    subtitle: "Semester 6 integrated personality and ethics.",
    url: "/pyq/integrated-personality-development-course",
    keywords: ["3160002", "ipdc", "ipdc course"],
    badge: "Subject",
  },
  {
    id: "operating-systems",
    type: "Subject",
    title: "Operating Systems",
    subtitle: "Semester 4 core operating system concepts.",
    url: "/pyq/operating-systems",
    keywords: ["3160401", "os", "operating systems"],
    badge: "Subject",
  },
  {
    id: "database-management-systems",
    type: "Subject",
    title: "Database Management Systems",
    subtitle: "Database concepts, SQL, and transaction processing.",
    url: "/pyq/database-management-systems",
    keywords: ["3160402", "dbms", "database"],
    badge: "Subject",
  },
  {
    id: "probability-and-statistics",
    type: "Subject",
    title: "Probability and Statistics",
    subtitle: "Probability, distributions, and statistical analysis.",
    url: "/pyq/probability-and-statistics",
    keywords: ["3160405", "p&s", "statistics", "probability"],
    badge: "Subject",
  },
  {
    id: "effective-technical-communication",
    type: "Subject",
    title: "Effective Technical Communication",
    subtitle: "Semester 3 communication skills and writing.",
    url: "/pyq/effective-technical-communication",
    keywords: ["3130004", "etc", "technical communication"],
    badge: "Subject",
  },
  {
    id: "indian-constitution",
    type: "Subject",
    title: "Indian Constitution",
    subtitle: "Semester 3 mandatory constitutional law.",
    url: "/pyq/indian-constitution",
    keywords: ["3130007", "constitution"],
    badge: "Subject",
  },
  {
    id: "design-engineering-ia",
    type: "Subject",
    title: "Design Engineering - I A",
    subtitle: "Semester 3 design fundamentals and creativity.",
    url: "/pyq/design-engineering-IA",
    keywords: ["3130008", "de ia", "design engineering"],
    badge: "Subject",
  },
  {
    id: "data-structures",
    type: "Subject",
    title: "Data Structures",
    subtitle: "Semester 3 core data structure concepts.",
    url: "/pyq/data-structures",
    keywords: ["3130702", "ds", "data structures"],
    badge: "Subject",
  },
  {
    id: "digital-fundamentals",
    type: "Subject",
    title: "Digital Fundamentals",
    subtitle: "Semester 3 digital logic and number systems.",
    url: "/pyq/digital-fundamentals",
    keywords: ["3130704", "digital fundamentals"],
    badge: "Subject",
  },
];

const pyqItems: SearchItem[] = subjectItems
  .filter((item) => item.url.startsWith("/pyq/"))
  .map((item) => ({
    ...item,
    id: `pyq-${item.id}`,
    type: "PYQ" as const,
    title: `${item.title} PYQs`,
    subtitle: `Open past papers for ${item.title}.`,
    badge: "PYQ",
  }))
  .concat([
    {
      id: "pyq-ipdc-1",
      type: "PYQ",
      title: "IPDC-I PYQs",
      subtitle: "Practice papers for Integrated Personality Development Course - I.",
      url: "/pyq/ipdc-1",
      keywords: ["ipdc", "ipdc-1", "personality development"],
      badge: "PYQ",
    },
  ]);

const notesItems: SearchItem[] = [
  {
    id: "notes-advanced-java-programming",
    type: "Notes",
    title: "Advanced Java Programming Notes",
    subtitle: "Chapter-wise AJP notes for GTU Semester 6.",
    url: "/notes/advanced-java-programming",
    keywords: ["ajp", "advanced java programming", "3160707"],
    badge: "Notes",
  },
  {
    id: "notes-software-engineering",
    type: "Notes",
    title: "Software Engineering Notes",
    subtitle: "Chapter-wise notes for Semester 5 Software Engineering.",
    url: "/notes/software-engineering",
    keywords: ["se", "software engineering", "3150711"],
    badge: "Notes",
  },
  {
    id: "notes-python-for-data-science",
    type: "Notes",
    title: "Python for Data Science Notes",
    subtitle: "Semester 5 PDS chapter notes.",
    url: "/notes/python-for-data-science",
    keywords: ["pds", "python data science", "3150713"],
    badge: "Notes",
  },
  {
    id: "notes-professional-ethics",
    type: "Notes",
    title: "Professional Ethics Notes",
    subtitle: "Semester 5 ethics revision notes.",
    url: "/notes/professional-ethics",
    keywords: ["pe", "professional ethics", "3150709"],
    badge: "Notes",
  },
  {
    id: "notes-ipdc-1",
    type: "Notes",
    title: "IPDC-I Notes",
    subtitle: "Personality development notes and revision plans.",
    url: "/notes/ipdc-1",
    keywords: ["ipdc", "personality development", "3150005"],
    badge: "Notes",
  },
  {
    id: "notes-computer-networks",
    type: "Notes",
    title: "Computer Networks Notes",
    subtitle: "Semester 5 CN chapter notes.",
    url: "/notes/computer-networks",
    keywords: ["cn", "computer networks", "3150710"],
    badge: "Notes",
  },
  {
    id: "notes-analysis-and-design-of-algorithms",
    type: "Notes",
    title: "Analysis and Design of Algorithms Notes",
    subtitle: "Semester 5 ADA revision notes.",
    url: "/notes/analysis-and-design-of-algorithms",
    keywords: ["ada", "analysis and design of algorithms", "3150703"],
    badge: "Notes",
  },
];

const mcqItems: SearchItem[] = [
  {
    id: "ipdc-test-library",
    type: "MCQ",
    title: "IPDC Free Test Library",
    subtitle: "Open all IPDC mock tests and MCQ practice.",
    url: "/test/ipdc",
    keywords: ["ipdc", "mcq", "test library", "mock test"],
    badge: "MCQ",
  },
  ...Object.values(ipdcMcqData).map((test) => ({
    id: `ipdc-${test.slug}`,
    type: "MCQ" as const,
    title: test.title,
    subtitle: `Practice the ${test.title} IPDC MCQ paper.`,
    url: `/test/ipdc/${encodeURIComponent(test.slug)}`,
    keywords: [test.slug, test.title.toLowerCase(), "ipdc", "mcq", "practice"],
    badge: "MCQ",
  })),
];

export const searchIndex: SearchItem[] = [
  ...semesterItems,
  ...subjectItems,
  ...pyqItems,
  ...notesItems,
  ...mcqItems,
];
