/**
 * Canonical PYQ catalog.
 *
 * - pdf: public URL under /public/pdfs/pyq/...
 * - solutionFile: filename in Supabase bucket "premium-pdfs" (private)
 */
export type Paper = {
  title: string;
  code: string;
  year: string;
  type: "Summer" | "Winter" | string;
  /** e.g. /pdfs/pyq/web-programming/wp-summer-2025.pdf */
  pdf: string;
  solutionAvailable: boolean;
  /** e.g. wp-summer-2025-solution.pdf (bucket: premium-pdfs) */
  solutionFile?: string;
  /** Optional free test route slug for IPDC papers */
  testSlug?: string;
};

export type Subject = {
  title: string;
  code: string;
  semester: number;
  description: string;
  papers: Paper[];
};

export type SubjectData = Record<string, Subject>;

export const subjectData: SubjectData = {
  "effective-technical-communication": {
    title: "Effective Technical Communication",
    code: "3130004",
    semester: 3,
    description:
      "Communication strategies, technical writing, and professional presentation skills.",
    papers: [
      {
        title: "ETC Summer 2025",
        code: "3130004",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/effective-technical-communication/etc-summer-2025.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "data-structures": {
    title: "Data Structures",
    code: "3130702",
    semester: 3,
    description:
      "Stack, queue, tree, and graph structures with algorithmic performance analysis.",
    papers: [
      {
        title: "DS Summer 2025",
        code: "3130702",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/data-structures/ds-summer-2025.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "software-engineering": {
    title: "Software Engineering",
    code: "3150711",
    semester: 5,
    description:
      "Software lifecycle, requirements, agile design, testing, and delivery.",
    papers: [
      {
        title: "SE Summer 2023",
        code: "3150711",
        year: "2023",
        type: "Summer",
        pdf: "/pdfs/pyq/software-engineering/se-summer-2023.pdf",
        solutionAvailable: false,
      },
      {
        title: "SE Winter 2022",
        code: "3150711",
        year: "2022",
        type: "Winter",
        pdf: "/pdfs/pyq/software-engineering/se-winter-2022.pdf",
        solutionAvailable: false,
      },
      {
        title: "SE Winter 2023",
        code: "3150711",
        year: "2023",
        type: "Winter",
        pdf: "/pdfs/pyq/software-engineering/se-winter-2023.pdf",
        solutionAvailable: false,
      },
      {
        title: "SE Winter 2024",
        code: "3150711",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/software-engineering/se-winter-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "SE Summer 2025",
        code: "3150711",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/software-engineering/se-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "SE Winter 2025",
        code: "3150711",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/software-engineering/se-winter-2025.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "python-for-data-science": {
    title: "Python for Data Science",
    code: "3150713",
    semester: 5,
    description:
      "Python data science libraries, analysis, visualization, and model building.",
    papers: [
      {
        title: "PDS Summer 2024",
        code: "3150713",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/python-for-data-science/pds-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "PDS Winter 2023",
        code: "3150713",
        year: "2023",
        type: "Winter",
        pdf: "/pdfs/pyq/python-for-data-science/pds-winter-2023.pdf",
        solutionAvailable: false,
      },
      {
        title: "PDS Winter 2024",
        code: "3150713",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/python-for-data-science/pds-winter-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "PDS Summer 2025",
        code: "3150713",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/python-for-data-science/pds-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "PDS Winter 2025",
        code: "3150713",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/python-for-data-science/pds-winter-2025.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "professional-ethics": {
    title: "Professional Ethics",
    code: "3150709",
    semester: 5,
    description:
      "Ethical decision-making, professional conduct, and engineering responsibility.",
    papers: [
      {
        title: "PE Summer 2024",
        code: "3150709",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/professional ethics/pe-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "PE Winter 2023",
        code: "3150709",
        year: "2023",
        type: "Winter",
        pdf: "/pdfs/pyq/professional ethics/pe-winter-2023.pdf",
        solutionAvailable: false,
      },
      {
        title: "PE Winter 2024",
        code: "3150709",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/professional ethics/pe-winter-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "PE Summer 2025",
        code: "3150709",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/professional ethics/pe-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "PE Winter 2025",
        code: "3150709",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/professional ethics/pe-winter-2025.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "ipdc-1": {
    title: "Integrated Personality Development Course - I",
    code: "3150005",
    semester: 5,
    description:
      "Professional growth, communication, leadership, and personality development for GTU Semester 5.",
    papers: [
      {
        title: "IPDC Summer 2023",
        code: "3150005",
        year: "2023",
        type: "Summer",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-summer-2023.pdf",
        solutionAvailable: false,
        testSlug: "summer-2023",
      },
      {
        title: "IPDC Winter 2023",
        code: "3150005",
        year: "2023",
        type: "Winter",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-winter-2023.pdf",
        solutionAvailable: false,
        testSlug: "winter-2023",
      },
      {
        title: "IPDC Summer 2024",
        code: "3150005",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-summer-2024.pdf",
        solutionAvailable: false,
        testSlug: "summer-2024",
      },
      {
        title: "IPDC Winter 2024",
        code: "3150005",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-winter-2024.pdf",
        solutionAvailable: false,
        testSlug: "winter-2024",
      },
      {
        title: "IPDC Summer 2025",
        code: "3150005",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-summer-2025.pdf",
        solutionAvailable: false,
        testSlug: "summer-2025",
      },
      {
        title: "IPDC Winter 2025",
        code: "3150005",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-winter-2025.pdf",
        solutionAvailable: false,
        testSlug: "winter-2025",
      },
    ],
  },
  "computer-networks": {
    title: "Computer Networks",
    code: "3150710",
    semester: 5,
    description:
      "Network architectures, routing, protocols, and secure data communication.",
    papers: [
      {
        title: "CN Winter 2022",
        code: "3150710",
        year: "2022",
        type: "Winter",
        pdf: "/pdfs/pyq/computer-networks/cn-winter-2022.pdf",
        solutionAvailable: false,
      },
      {
        title: "CN Summer 2024",
        code: "3150710",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/computer-networks/cn-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "CN Winter 2024",
        code: "3150710",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/computer-networks/cn-winter-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "CN Summer 2025",
        code: "3150710",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/computer-networks/cn-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "CN Winter 2025",
        code: "3150710",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/computer-networks/cn-winter-2025.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "analysis-and-design-of-algorithms": {
    title: "Analysis and Design of Algorithms",
    code: "3150703",
    semester: 5,
    description:
      "Algorithm design techniques, complexity analysis, and optimization strategies.",
    papers: [
      {
        title: "ADA Winter 2023",
        code: "3150703",
        year: "2023",
        type: "Winter",
        pdf: "/pdfs/pyq/analysis-and-design-of-algorithms/ada-winter-2023.pdf",
        solutionAvailable: false,
      },
      {
        title: "ADA Winter 2024",
        code: "3150703",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/analysis-and-design-of-algorithms/ada-winter-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "ADA Summer 2024",
        code: "3150703",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/analysis-and-design-of-algorithms/ada-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "ADA Winter 2025",
        code: "3150703",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/analysis-and-design-of-algorithms/ada-winter-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "ADA Summer 2025",
        code: "3150703",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/analysis-and-design-of-algorithms/ada-summer-2025.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "web-programming": {
    title: "Web Programming",
    code: "3160713",
    semester: 6,
    description:
      "Full-stack development techniques including modern frameworks and responsive design.",
    papers: [
      {
        title: "WP Summer 2025",
        code: "3160713",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/web-programming/wp-summer-2025.pdf",
        solutionAvailable: false,
        solutionFile: "wp-summer-2025-solution.pdf",
      },
      {
        title: "WP Winter 2024",
        code: "3160713",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/web-programming/wp-winter-2024.pdf",
        solutionAvailable: false,
        solutionFile: "wp-winter-2024-solution.pdf",
      },
      {
        title: "WP Summer 2024",
        code: "3160713",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/web-programming/wp-summer-2024.pdf",
        solutionAvailable: false,
        solutionFile: "wp-summer-2024-solution.pdf",
      },
      {
        title: "WP Winter 2023",
        code: "3160713",
        year: "2023",
        type: "Winter",
        pdf: "/pdfs/pyq/web-programming/wp-winter-2023.pdf",
        solutionAvailable: false,
        solutionFile: "wp-winter-2023-solution.pdf",
      },
      {
        title: "WP Summer 2023",
        code: "3160713",
        year: "2023",
        type: "Summer",
        pdf: "/pdfs/pyq/web-programming/wp-summer-2023.pdf",
        solutionAvailable: false,
        solutionFile: "wp-summer-2023-solution.pdf",
      },
    ],
  },
  "microprocessor-and-interfacing": {
    title: "Microprocessor and Interfacing",
    code: "3160710",
    semester: 6,
    description:
      "8086 microprocessor architecture, interfacing techniques, DMA, interrupts, and serial communication.",
    papers: [
      {
        title: "MPI Demo Paper",
        code: "3160710",
        year: "Demo",
        type: "Demo",
        pdf: "/pdfs/pyq/microprocessor-and-interfacing/mpi-demo.pdf",
        solutionAvailable: false,
      },
      {
        title: "MPI Winter 2025",
        code: "3160710",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/microprocessor-and-interfacing/mpi-winter-2025.pdf",
        solutionAvailable: true,
        solutionFile: "mpi-winter-2025-solution.pdf",
      },
      {
        title: "MPI Summer 2025",
        code: "3160710",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/microprocessor-and-interfacing/mpi-summer-2025.pdf",
        solutionAvailable: true,
        solutionFile: "mpi-summer-2025-solution.pdf",
      },
      {
        title: "MPI Winter 2024",
        code: "3160710",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/microprocessor-and-interfacing/mpi-winter-2024.pdf",
        solutionAvailable: true,
        solutionFile: "mpi-winter-2024-solution.pdf",
      },
      {
        title: "MPI Summer 2024",
        code: "3160710",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/microprocessor-and-interfacing/mpi-summer-2024.pdf",
        solutionAvailable: true,
        solutionFile: "mpi-summer-2024-solution.pdf",
      },
    ],
  },
  "theory-of-computation": {
    title: "Theory of Computation",
    code: "3160704",
    semester: 6,
    description:
      "Master automata theory, formal languages, and mathematical foundations of computing.",
    papers: [
      {
        title: "TOC Winter 2025",
        code: "3160704",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/theory-of-computation/toc-winter-2025.pdf",
        solutionAvailable: true,
        solutionFile: "toc-winter-2025-solution.pdf",
      },
      {
        title: "TOC Winter 2024",
        code: "3160704",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/theory-of-computation/toc-winter-2024.pdf",
        solutionAvailable: true,
        solutionFile: "toc-winter-2024-solution.pdf",
      },
      {
        title: "TOC Summer 2024",
        code: "3160704",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/theory-of-computation/toc-summer-2024.pdf",
        solutionAvailable: true,
        solutionFile: "toc-summer-2024-solution.pdf",
      },
      {
        title: "TOC Winter 2022",
        code: "3160704",
        year: "2022",
        type: "Winter",
        pdf: "/pdfs/pyq/theory-of-computation/toc-winter-2022.pdf",
        solutionAvailable: true,
        solutionFile: "toc-winter-2022-solution.pdf",
      },
    ],
  },
  "integrated-personality-development-course": {
    title: "Integrated Personality Development Course",
    code: "3160003",
    semester: 6,
    description:
      "Integrated personality development focusing on values, ethics, leadership, and holistic growth.",
    papers: [
      {
        title: "IPDC Winter 2025",
        code: "3160003",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-winter-2025.pdf",
        solutionAvailable: false,
        testSlug: "winter-2025",
      },
      {
        title: "IPDC Summer 2025",
        code: "3160003",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-summer-2025.pdf",
        solutionAvailable: false,
        testSlug: "summer-2025",
      },
      {
        title: "IPDC Winter 2024",
        code: "3160003",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-winter-2024.pdf",
        solutionAvailable: false,
        testSlug: "winter-2024",
      },
      {
        title: "IPDC Summer 2024",
        code: "3160003",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-summer-2024.pdf",
        solutionAvailable: false,
        testSlug: "summer-2024",
      },
      {
        title: "IPDC Winter 2023",
        code: "3160003",
        year: "2023",
        type: "Winter",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-winter-2023.pdf",
        solutionAvailable: false,
        testSlug: "winter-2023",
      },
    ],
  },
  // IoT & Applications: PYQ collection
  "iot-and-applications": {
    title: "IoT & Applications",
    code: "3160713",
    semester: 6,
    description:
      "Internet of Things architecture, protocols, embedded systems, and real-world IoT applications.",
    papers: [
      {
        title: "IoT Free Demo Solution",
        code: "3160713",
        year: "Demo",
        type: "Demo",
        pdf: "/pdfs/pyq/iot-and-applications/iot-demo.pdf",
        solutionAvailable: false,
      },
      {
        title: "IoT Summer 2025",
        code: "3160713",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/iot-and-applications/iot-summer-2025.pdf",
        solutionAvailable: true,
        solutionFile: "iot-summer-2025-solution.pdf",
      },
      {
        title: "IoT Winter 2025",
        code: "3160713",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/iot-and-applications/iot-winter-2025.pdf",
        solutionAvailable: true,
        solutionFile: "iot-winter-2025-solution.pdf",
      },
      {
        title: "IoT Winter 2024",
        code: "3160713",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/iot-and-applications/iot-winter-2024.pdf",
        solutionAvailable: true,
        solutionFile: "iot-winter-2024-solution.pdf",
      },
      {
        title: "IoT Summer 2024",
        code: "3160713",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/iot-and-applications/iot-summer-2024.pdf",
        solutionAvailable: true,
        solutionFile: "iot-summer-2024-solution.pdf",
      },
    ],
  },
  "advanced-java-programming": {
    title: "Advanced Java Programming",
    code: "advanced-java-programming",
    semester: 6,
    description:
      "Advanced Java concepts, enterprise programming, concurrency, JDBC, and practical GTU question solutions for Semester 6 Computer Engineering.",
    papers: [
      {
        title: "Preview Solution Quality",
        code: "advanced-java-programming",
        year: "Demo",
        type: "Demo",
        pdf: "/pdfs/pyq/advanced-java-programming/ajp-demo.pdf",
        solutionAvailable: false,
      },
      {
        title: "AJP Summer 2025",
        code: "advanced-java-programming",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/advanced-java-programming/ajp-summer-2025.pdf",
        solutionAvailable: true,
        solutionFile: "ajp-summer-2025-solution.pdf",
      },
      {
        title: "AJP Summer 2024",
        code: "advanced-java-programming",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/advanced-java-programming/ajp-summer-2024.pdf",
        solutionAvailable: true,
        solutionFile: "ajp-summer-2024-solution.pdf",
      },
      {
        title: "AJP Winter 2025",
        code: "advanced-java-programming",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/advanced-java-programming/ajp-winter-2025.pdf",
        solutionAvailable: true,
        solutionFile: "ajp-winter-2025-solution.pdf",
      },
      {
        title: "AJP Winter 2024",
        code: "advanced-java-programming",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/advanced-java-programming/ajp-winter-2024.pdf",
        solutionAvailable: true,
        solutionFile: "ajp-winter-2024-solution.pdf",
      },
    ],
  },
  "data-visualization": {
    title: "Data Visualization",
    code: "DV",
    semester: 6,
    description:
      "GTU Data Visualization previous year question papers and expert solutions for Semester 6 Computer Engineering.",
    papers: [
      {
        title: "DV Demo Paper",
        code: "DV",
        year: "Demo",
        type: "Demo",
        pdf: "/pdfs/pyq/data-visualization/dv-demo.pdf",
        solutionAvailable: false,
      },
      {
        title: "DV Summer 2025",
        code: "DV",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/data-visualization/dv-summer-2025.pdf",
        solutionAvailable: true,
        solutionFile: "dv-summer-2025-solution.pdf",
      },
      {
        title: "DV Summer 2024",
        code: "DV",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/data-visualization/dv-summer-2024.pdf",
        solutionAvailable: true,
        solutionFile: "dv-summer-2024-solution.pdf",
      },
      {
        title: "DV Winter 2025",
        code: "DV",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/data-visualization/dv-winter-2025.pdf",
        solutionAvailable: true,
        solutionFile: "dv-winter-2025-solution.pdf",
      },
    ],
  },
};

