/**
 * Canonical PYQ catalog.
 *
 * - pdf: public URL under /public/pdfs/pyq/...
 * - solutionFile: filename in Supabase bucket "premium-pdfs" (private)
 */
export type Paper = {
  title: string;
  code: string;
  year: string;
  type: "Summer" | "Winter" | string;
  /** e.g. /pdfs/pyq/web-programming/wp-summer-2025.pdf */
  pdf: string;
  solutionAvailable: boolean;
  /** e.g. wp-summer-2025-solution.pdf (bucket: premium-pdfs) */
  solutionFile?: string;
  /** Optional free test route slug for IPDC papers */
  testSlug?: string;
};

export type Subject = {
  title: string;
  code: string;
  semester: number;
  description: string;
  papers: Paper[];
};

export type SubjectData = Record<string, Subject>;

export const subjectData: SubjectData = {
  "effective-technical-communication": {
    title: "Effective Technical Communication",
    code: "3130004",
    semester: 3,
    description:
      "Communication strategies, technical writing, and professional presentation skills.",
    papers: [
      {
        title: "ETC Summer 2025",
        code: "3130004",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/effective-technical-communication/etc-summer-2025.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "data-structures": {
    title: "Data Structures",
    code: "3130702",
    semester: 3,
    description:
      "Stack, queue, tree, and graph structures with algorithmic performance analysis.",
    papers: [
      {
        title: "DS Summer 2025",
        code: "3130702",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/data-structures/ds-summer-2025.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "software-engineering": {
    title: "Software Engineering",
    code: "3150711",
    semester: 5,
    description:
      "Software lifecycle, requirements, agile design, testing, and delivery.",
    papers: [
      {
        title: "SE Summer 2023",
        code: "3150711",
        year: "2023",
        type: "Summer",
        pdf: "/pdfs/pyq/software-engineering/se-summer-2023.pdf",
        solutionAvailable: false,
      },
      {
        title: "SE Winter 2022",
        code: "3150711",
        year: "2022",
        type: "Winter",
        pdf: "/pdfs/pyq/software-engineering/se-winter-2022.pdf",
        solutionAvailable: false,
      },
      {
        title: "SE Winter 2023",
        code: "3150711",
        year: "2023",
        type: "Winter",
        pdf: "/pdfs/pyq/software-engineering/se-winter-2023.pdf",
        solutionAvailable: false,
      },
      {
        title: "SE Winter 2024",
        code: "3150711",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/software-engineering/se-winter-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "SE Summer 2025",
        code: "3150711",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/software-engineering/se-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "SE Winter 2025",
        code: "3150711",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/software-engineering/se-winter-2025.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "python-for-data-science": {
    title: "Python for Data Science",
    code: "3150713",
    semester: 5,
    description:
      "Python data science libraries, analysis, visualization, and model building.",
    papers: [
      {
        title: "PDS Summer 2024",
        code: "3150713",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/python-for-data-science/pds-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "PDS Winter 2023",
        code: "3150713",
        year: "2023",
        type: "Winter",
        pdf: "/pdfs/pyq/python-for-data-science/pds-winter-2023.pdf",
        solutionAvailable: false,
      },
      {
        title: "PDS Winter 2024",
        code: "3150713",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/python-for-data-science/pds-winter-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "PDS Summer 2025",
        code: "3150713",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/python-for-data-science/pds-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "PDS Winter 2025",
        code: "3150713",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/python-for-data-science/pds-winter-2025.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "professional-ethics": {
    title: "Professional Ethics",
    code: "3150709",
    semester: 5,
    description:
      "Ethical decision-making, professional conduct, and engineering responsibility.",
    papers: [
      {
        title: "PE Summer 2024",
        code: "3150709",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/professional ethics/pe-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "PE Winter 2023",
        code: "3150709",
        year: "2023",
        type: "Winter",
        pdf: "/pdfs/pyq/professional ethics/pe-winter-2023.pdf",
        solutionAvailable: false,
      },
      {
        title: "PE Winter 2024",
        code: "3150709",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/professional ethics/pe-winter-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "PE Summer 2025",
        code: "3150709",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/professional ethics/pe-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "PE Winter 2025",
        code: "3150709",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/professional ethics/pe-winter-2025.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "ipdc-1": {
    title: "Integrated Personality Development Course - I",
    code: "3150005",
    semester: 5,
    description:
      "Professional growth, communication, leadership, and personality development for GTU Semester 5.",
    papers: [
      {
        title: "IPDC Summer 2023",
        code: "3150005",
        year: "2023",
        type: "Summer",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-summer-2023.pdf",
        solutionAvailable: false,
        testSlug: "summer-2023",
      },
      {
        title: "IPDC Winter 2023",
        code: "3150005",
        year: "2023",
        type: "Winter",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-winter-2023.pdf",
        solutionAvailable: false,
        testSlug: "winter-2023",
      },
      {
        title: "IPDC Summer 2024",
        code: "3150005",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-summer-2024.pdf",
        solutionAvailable: false,
        testSlug: "summer-2024",
      },
      {
        title: "IPDC Winter 2024",
        code: "3150005",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-winter-2024.pdf",
        solutionAvailable: false,
        testSlug: "winter-2024",
      },
      {
        title: "IPDC Summer 2025",
        code: "3150005",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-summer-2025.pdf",
        solutionAvailable: false,
        testSlug: "summer-2025",
      },
      {
        title: "IPDC Winter 2025",
        code: "3150005",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-winter-2025.pdf",
        solutionAvailable: false,
        testSlug: "winter-2025",
      },
    ],
  },
  "computer-networks": {
    title: "Computer Networks",
    code: "3150710",
    semester: 5,
    description:
      "Network architectures, routing, protocols, and secure data communication.",
    papers: [
      {
        title: "CN Winter 2022",
        code: "3150710",
        year: "2022",
        type: "Winter",
        pdf: "/pdfs/pyq/computer-networks/cn-winter-2022.pdf",
        solutionAvailable: false,
      },
      {
        title: "CN Summer 2024",
        code: "3150710",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/computer-networks/cn-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "CN Winter 2024",
        code: "3150710",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/computer-networks/cn-winter-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "CN Summer 2025",
        code: "3150710",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/computer-networks/cn-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "CN Winter 2025",
        code: "3150710",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/computer-networks/cn-winter-2025.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "analysis-and-design-of-algorithms": {
    title: "Analysis and Design of Algorithms",
    code: "3150703",
    semester: 5,
    description:
      "Algorithm design techniques, complexity analysis, and optimization strategies.",
    papers: [
      {
        title: "ADA Winter 2023",
        code: "3150703",
        year: "2023",
        type: "Winter",
        pdf: "/pdfs/pyq/analysis-and-design-of-algorithms/ada-winter-2023.pdf",
        solutionAvailable: false,
      },
      {
        title: "ADA Winter 2024",
        code: "3150703",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/analysis-and-design-of-algorithms/ada-winter-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "ADA Summer 2024",
        code: "3150703",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/analysis-and-design-of-algorithms/ada-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "ADA Winter 2025",
        code: "3150703",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/analysis-and-design-of-algorithms/ada-winter-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "ADA Summer 2025",
        code: "3150703",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/analysis-and-design-of-algorithms/ada-summer-2025.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "web-programming": {
    title: "Web Programming",
    code: "3160713",
    semester: 6,
    description:
      "Full-stack development techniques including modern frameworks and responsive design.",
    papers: [
      {
        title: "WP Summer 2025",
        code: "3160713",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/web-programming/wp-summer-2025.pdf",
        solutionAvailable: false,
        solutionFile: "wp-summer-2025-solution.pdf",
      },
      {
        title: "WP Winter 2024",
        code: "3160713",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/web-programming/wp-winter-2024.pdf",
        solutionAvailable: false,
        solutionFile: "wp-winter-2024-solution.pdf",
      },
      {
        title: "WP Summer 2024",
        code: "3160713",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/web-programming/wp-summer-2024.pdf",
        solutionAvailable: false,
        solutionFile: "wp-summer-2024-solution.pdf",
      },
      {
        title: "WP Winter 2023",
        code: "3160713",
        year: "2023",
        type: "Winter",
        pdf: "/pdfs/pyq/web-programming/wp-winter-2023.pdf",
        solutionAvailable: false,
        solutionFile: "wp-winter-2023-solution.pdf",
      },
      {
        title: "WP Summer 2023",
        code: "3160713",
        year: "2023",
        type: "Summer",
        pdf: "/pdfs/pyq/web-programming/wp-summer-2023.pdf",
        solutionAvailable: false,
        solutionFile: "wp-summer-2023-solution.pdf",
      },
    ],
  },
  "microprocessor-and-interfacing": {
    title: "Microprocessor and Interfacing",
    code: "3160710",
    semester: 6,
    description:
      "8086 microprocessor architecture, interfacing techniques, DMA, interrupts, and serial communication.",
    papers: [
      {
        title: "MPI Demo Paper",
        code: "3160710",
        year: "Demo",
        type: "Demo",
        pdf: "/pdfs/pyq/microprocessor-and-interfacing/mpi-demo.pdf",
        solutionAvailable: false,
      },
      {
        title: "MPI Winter 2025",
        code: "3160710",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/microprocessor-and-interfacing/mpi-winter-2025.pdf",
        solutionAvailable: true,
        solutionFile: "mpi-winter-2025-solution.pdf",
      },
      {
        title: "MPI Summer 2025",
        code: "3160710",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/microprocessor-and-interfacing/mpi-summer-2025.pdf",
        solutionAvailable: true,
        solutionFile: "mpi-summer-2025-solution.pdf",
      },
      {
        title: "MPI Winter 2024",
        code: "3160710",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/microprocessor-and-interfacing/mpi-winter-2024.pdf",
        solutionAvailable: true,
        solutionFile: "mpi-winter-2024-solution.pdf",
      },
      {
        title: "MPI Summer 2024",
        code: "3160710",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/microprocessor-and-interfacing/mpi-summer-2024.pdf",
        solutionAvailable: true,
        solutionFile: "mpi-summer-2024-solution.pdf",
      },
    ],
  },
  "theory-of-computation": {
    title: "Theory of Computation",
    code: "3160704",
    semester: 6,
    description:
      "Master automata theory, formal languages, and mathematical foundations of computing.",
    papers: [
      {
        title: "TOC Winter 2025",
        code: "3160704",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/theory-of-computation/toc-winter-2025.pdf",
        solutionAvailable: true,
        solutionFile: "toc-winter-2025-solution.pdf",
      },
      {
        title: "TOC Winter 2024",
        code: "3160704",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/theory-of-computation/toc-winter-2024.pdf",
        solutionAvailable: true,
        solutionFile: "toc-winter-2024-solution.pdf",
      },
      {
        title: "TOC Summer 2024",
        code: "3160704",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/theory-of-computation/toc-summer-2024.pdf",
        solutionAvailable: true,
        solutionFile: "toc-summer-2024-solution.pdf",
      },
      {
        title: "TOC Winter 2022",
        code: "3160704",
        year: "2022",
        type: "Winter",
        pdf: "/pdfs/pyq/theory-of-computation/toc-winter-2022.pdf",
        solutionAvailable: true,
        solutionFile: "toc-winter-2022-solution.pdf",
      },
    ],
  },
  "integrated-personality-development-course": {
    title: "Integrated Personality Development Course",
    code: "3160003",
    semester: 6,
    description:
      "Integrated personality development focusing on values, ethics, leadership, and holistic growth.",
    papers: [
      {
        title: "IPDC Winter 2025",
        code: "3160003",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-winter-2025.pdf",
        solutionAvailable: false,
        testSlug: "winter-2025",
      },
      {
        title: "IPDC Summer 2025",
        code: "3160003",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-summer-2025.pdf",
        solutionAvailable: false,
        testSlug: "summer-2025",
      },
      {
        title: "IPDC Winter 2024",
        code: "3160003",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-winter-2024.pdf",
        solutionAvailable: false,
        testSlug: "winter-2024",
      },
      {
        title: "IPDC Summer 2024",
        code: "3160003",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-summer-2024.pdf",
        solutionAvailable: false,
        testSlug: "summer-2024",
      },
      {
        title: "IPDC Winter 2023",
        code: "3160003",
        year: "2023",
        type: "Winter",
        pdf: "/pdfs/pyq/integrated-personality-development-course/ipdc-winter-2023.pdf",
        solutionAvailable: false,
        testSlug: "winter-2023",
      },
    ],
  },
  // IoT & Applications: PYQ collection
  "iot-and-applications": {
    title: "IoT & Applications",
    code: "3160713",
    semester: 6,
    description:
      "Internet of Things architecture, protocols, embedded systems, and real-world IoT applications.",
    papers: [
      {
        title: "IoT Free Demo Solution",
        code: "3160713",
        year: "Demo",
        type: "Demo",
        pdf: "/pdfs/pyq/iot-and-applications/iot-demo.pdf",
        solutionAvailable: false,
      },
      {
        title: "IoT Summer 2025",
        code: "3160713",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/iot-and-applications/iot-summer-2025.pdf",
        solutionAvailable: true,
        solutionFile: "iot-summer-2025-solution.pdf",
      },
      {
        title: "IoT Winter 2025",
        code: "3160713",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/iot-and-applications/iot-winter-2025.pdf",
        solutionAvailable: true,
        solutionFile: "iot-winter-2025-solution.pdf",
      },
      {
        title: "IoT Winter 2024",
        code: "3160713",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/iot-and-applications/iot-winter-2024.pdf",
        solutionAvailable: true,
        solutionFile: "iot-winter-2024-solution.pdf",
      },
      {
        title: "IoT Summer 2024",
        code: "3160713",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/iot-and-applications/iot-summer-2024.pdf",
        solutionAvailable: true,
        solutionFile: "iot-summer-2024-solution.pdf",
      },
    ],
  },
  "advanced-java-programming": {
    title: "Advanced Java Programming",
    code: "advanced-java-programming",
    semester: 6,
    description:
      "Advanced Java concepts, enterprise programming, concurrency, JDBC, and practical GTU question solutions for Semester 6 Computer Engineering.",
    papers: [
      {
        title: "Preview Solution Quality",
        code: "advanced-java-programming",
        year: "Demo",
        type: "Demo",
        pdf: "/pdfs/pyq/advanced-java-programming/ajp-demo.pdf",
        solutionAvailable: false,
      },
      {
        title: "AJP Summer 2025",
        code: "advanced-java-programming",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/advanced-java-programming/ajp-summer-2025.pdf",
        solutionAvailable: true,
        solutionFile: "ajp-summer-2025-solution.pdf",
      },
      {
        title: "AJP Summer 2024",
        code: "advanced-java-programming",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/advanced-java-programming/ajp-summer-2024.pdf",
        solutionAvailable: true,
        solutionFile: "ajp-summer-2024-solution.pdf",
      },
      {
        title: "AJP Winter 2025",
        code: "advanced-java-programming",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/advanced-java-programming/ajp-winter-2025.pdf",
        solutionAvailable: true,
        solutionFile: "ajp-winter-2025-solution.pdf",
      },
      {
        title: "AJP Winter 2024",
        code: "advanced-java-programming",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/advanced-java-programming/ajp-winter-2024.pdf",
        solutionAvailable: true,
        solutionFile: "ajp-winter-2024-solution.pdf",
      },
    ],
  },
  "data-visualization": {
    title: "Data Visualization",
    code: "DV",
    semester: 6,
    description:
      "GTU Data Visualization previous year question papers and expert solutions for Semester 6 Computer Engineering.",
    papers: [
      {
        title: "DV Demo Paper",
        code: "DV",
        year: "Demo",
        type: "Demo",
        pdf: "/pdfs/pyq/data-visualization/dv-demo.pdf",
        solutionAvailable: false,
      },
      {
        title: "DV Summer 2025",
        code: "DV",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/data-visualization/dv-summer-2025.pdf",
        solutionAvailable: true,
        solutionFile: "dv-summer-2025-solution.pdf",
      },
      {
        title: "DV Summer 2024",
        code: "DV",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/data-visualization/dv-summer-2024.pdf",
        solutionAvailable: true,
        solutionFile: "dv-summer-2024-solution.pdf",
      },
      {
        title: "DV Winter 2025",
        code: "DV",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/data-visualization/dv-winter-2025.pdf",
        solutionAvailable: true,
        solutionFile: "dv-winter-2025-solution.pdf",
      },
    ],
  },
  "compiler-design": {
    title: "Compiler Design",
    code: "3170701",
    semester: 7,
    description:
      "Compiler theory, parsing, syntax trees, and code generation for GTU Semester 7 students.",
    papers: [
      {
        title: "Compiler Design Summer 2026",
        code: "3170701",
        year: "2026",
        type: "Summer",
        pdf: "/pdfs/pyq/compiler-design/cd-summer-2026.pdf",
        solutionAvailable: false,
      },
      {
        title: "Compiler Design Summer 2025",
        code: "3170701",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/compiler-design/cd-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Compiler Design Winter 2025",
        code: "3170701",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/compiler-design/cd-winter-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Compiler Design Summer 2024",
        code: "3170701",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/compiler-design/cd-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "Compiler Design Winter 2024",
        code: "3170701",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/compiler-design/cd-winter-2024.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "artificial-intelligence": {
    title: "Artificial Intelligence",
    code: "3170716",
    semester: 7,
    description:
      "Search strategies, knowledge representation, planning, and intelligent systems for Semester 7.",
    papers: [
      {
        title: "Artificial Intelligence Summer 2026",
        code: "3170716",
        year: "2026",
        type: "Summer",
        pdf: "/pdfs/pyq/artificial-intelligence/ai-summer-2026.pdf",
        solutionAvailable: false,
      },
      {
        title: "Artificial Intelligence Summer 2025",
        code: "3170716",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/artificial-intelligence/ai-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Artificial Intelligence Winter 2025",
        code: "3170716",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/artificial-intelligence/ai-winter-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Artificial Intelligence Summer 2024",
        code: "3170716",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/artificial-intelligence/ai-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "Artificial Intelligence Winter 2024",
        code: "3170716",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/artificial-intelligence/ai-winter-2024.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "cloud-computing": {
    title: "Cloud Computing",
    code: "3170717",
    semester: 7,
    description:
      "Cloud service models, virtualization, deployment models, and scalable infrastructure topics.",
    papers: [
      {
        title: "Cloud Computing Summer 2026",
        code: "3170717",
        year: "2026",
        type: "Summer",
        pdf: "/pdfs/pyq/cloud-computing/cc-summer-2026.pdf",
        solutionAvailable: false,
      },
      {
        title: "Cloud Computing Summer 2025",
        code: "3170717",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/cloud-computing/cc-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Cloud Computing Winter 2025",
        code: "3170717",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/cloud-computing/cc-winter-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Cloud Computing Summer 2024",
        code: "3170717",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/cloud-computing/cc-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "Cloud Computing Winter 2024",
        code: "3170717",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/cloud-computing/cc-winter-2024.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "information-retrieval": {
    title: "Information Retrieval",
    code: "3170718",
    semester: 7,
    description:
      "Indexing, ranking, retrieval models, and search engine design principles for GTU Semester 7.",
    papers: [
      {
        title: "Information Retrieval Summer 2026",
        code: "3170718",
        year: "2026",
        type: "Summer",
        pdf: "/pdfs/pyq/information-retrieval/ir-summer-2026.pdf",
        solutionAvailable: false,
      },
      {
        title: "Information Retrieval Summer 2025",
        code: "3170718",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/information-retrieval/ir-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Information Retrieval Winter 2025",
        code: "3170718",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/information-retrieval/ir-winter-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Information Retrieval Summer 2024",
        code: "3170718",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/information-retrieval/ir-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "Information Retrieval Winter 2024",
        code: "3170718",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/information-retrieval/ir-winter-2024.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "distributed-system": {
    title: "Distributed System",
    code: "3170719",
    semester: 7,
    description:
      "Distributed communication, synchronization, consistency, and fault tolerance concepts.",
    papers: [
      {
        title: "Distributed System Summer 2026",
        code: "3170719",
        year: "2026",
        type: "Summer",
        pdf: "/pdfs/pyq/distributed-system/ds-summer-2026.pdf",
        solutionAvailable: false,
      },
      {
        title: "Distributed System Summer 2025",
        code: "3170719",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/distributed-system/ds-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Distributed System Winter 2025",
        code: "3170719",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/distributed-system/ds-winter-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Distributed System Summer 2024",
        code: "3170719",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/distributed-system/ds-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "Distributed System Winter 2024",
        code: "3170719",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/distributed-system/ds-winter-2024.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "information-security": {
    title: "Information Security",
    code: "3170720",
    semester: 7,
    description:
      "Cryptography, authentication, secure systems, and risk mitigation for Semester 7.",
    papers: [
      {
        title: "Information Security Summer 2026",
        code: "3170720",
        year: "2026",
        type: "Summer",
        pdf: "/pdfs/pyq/information-security/is-summer-2026.pdf",
        solutionAvailable: false,
      },
      {
        title: "Information Security Summer 2025",
        code: "3170720",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/information-security/is-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Information Security Winter 2025",
        code: "3170720",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/information-security/is-winter-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Information Security Summer 2024",
        code: "3170720",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/information-security/is-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "Information Security Winter 2024",
        code: "3170720",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/information-security/is-winter-2024.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "parallel-and-distributed-computing": {
    title: "Parallel and Distributed Computing",
    code: "3170721",
    semester: 7,
    description:
      "Parallel architectures, concurrency, scheduling, and distributed execution patterns.",
    papers: [
      {
        title: "Parallel and Distributed Computing Summer 2025",
        code: "3170721",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/parallel-and-distributed-computing/pdc-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Parallel and Distributed Computing Winter 2025",
        code: "3170721",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/parallel-and-distributed-computing/pdc-winter-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Parallel and Distributed Computing Summer 2024",
        code: "3170721",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/parallel-and-distributed-computing/pdc-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "Parallel and Distributed Computing Winter 2024",
        code: "3170721",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/parallel-and-distributed-computing/pdc-winter-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "Parallel and Distributed Computing Winter 2023",
        code: "3170721",
        year: "2023",
        type: "Winter",
        pdf: "/pdfs/pyq/parallel-and-distributed-computing/pdc-winter-2023.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "big-data-analytics": {
    title: "Big Data Analytics",
    code: "3170722",
    semester: 7,
    description:
      "Big data processing, analytics pipelines, and insight generation for Semester 7.",
    papers: [
      {
        title: "Big Data Analytics Summer 2026",
        code: "3170722",
        year: "2026",
        type: "Summer",
        pdf: "/pdfs/pyq/big-data-analytics/bda-summer-2026.pdf",
        solutionAvailable: false,
      },
      {
        title: "Big Data Analytics Summer 2025",
        code: "3170722",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/big-data-analytics/bda-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Big Data Analytics Winter 2025",
        code: "3170722",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/big-data-analytics/bda-winter-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Big Data Analytics Summer 2024",
        code: "3170722",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/big-data-analytics/bda-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "Big Data Analytics Winter 2024",
        code: "3170722",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/big-data-analytics/bda-winter-2024.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "natural-language-processing": {
    title: "Natural Language Processing",
    code: "3170723",
    semester: 7,
    description:
      "Language modeling, text processing, and semantic interpretation for GTU Semester 7.",
    papers: [
      {
        title: "Natural Language Processing Summer 2026",
        code: "3170723",
        year: "2026",
        type: "Summer",
        pdf: "/pdfs/pyq/natural-language-processing/nlp-summer-2026.pdf",
        solutionAvailable: false,
      },
      {
        title: "Natural Language Processing Summer 2025",
        code: "3170723",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/natural-language-processing/nlp-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Natural Language Processing Winter 2025",
        code: "3170723",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/natural-language-processing/nlp-winter-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Natural Language Processing Summer 2024",
        code: "3170723",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/natural-language-processing/nlp-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "Natural Language Processing Winter 2024",
        code: "3170723",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/natural-language-processing/nlp-winter-2024.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "machine-learning": {
    title: "Machine Learning",
    code: "3170724",
    semester: 7,
    description:
      "Supervised and unsupervised learning, evaluation, and practical model design topics.",
    papers: [
      {
        title: "Machine Learning Summer 2026",
        code: "3170724",
        year: "2026",
        type: "Summer",
        pdf: "/pdfs/pyq/machine-learning/ml-summer-2026.pdf",
        solutionAvailable: false,
      },
      {
        title: "Machine Learning Summer 2025",
        code: "3170724",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/machine-learning/ml-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Machine Learning Winter 2025",
        code: "3170724",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/machine-learning/ml-winter-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Machine Learning Summer 2024",
        code: "3170724",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/machine-learning/ml-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "Machine Learning Winter 2024",
        code: "3170724",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/machine-learning/ml-winter-2024.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "digital-forensics": {
    title: "Digital Forensics",
    code: "3170725",
    semester: 7,
    description:
      "Evidence handling, investigation workflows, and forensic tools for Semester 7.",
    papers: [
      {
        title: "Digital Forensics Summer 2026",
        code: "3170725",
        year: "2026",
        type: "Summer",
        pdf: "/pdfs/pyq/digital-forensics/df-summer-2026.pdf",
        solutionAvailable: false,
      },
      {
        title: "Digital Forensics Summer 2025",
        code: "3170725",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/digital-forensics/df-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Digital Forensics Winter 2025",
        code: "3170725",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/digital-forensics/df-winter-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Digital Forensics Summer 2024",
        code: "3170725",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/digital-forensics/df-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "Digital Forensics Winter 2024",
        code: "3170725",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/digital-forensics/df-winter-2024.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "mobile-computing-and-wireless-communication": {
    title: "Mobile Computing and Wireless Communication",
    code: "3170710",
    semester: 7,
    description:
      "Wireless networks, mobile architectures, and communication systems for Semester 7.",
    papers: [
      {
        title: "Mobile Computing and Wireless Communication Summer 2026",
        code: "3170710",
        year: "2026",
        type: "Summer",
        pdf: "/pdfs/pyq/mobile-computing-and-wireless-communication/mcwc-summer-2026.pdf",
        solutionAvailable: false,
      },
      {
        title: "Mobile Computing and Wireless Communication Summer 2025",
        code: "3170710",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/mobile-computing-and-wireless-communication/mcwc-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Mobile Computing and Wireless Communication Winter 2025",
        code: "3170710",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/mobile-computing-and-wireless-communication/mcwc-winter-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Mobile Computing and Wireless Communication Summer 2024",
        code: "3170710",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/mobile-computing-and-wireless-communication/mcwc-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "Mobile Computing and Wireless Communication Winter 2024",
        code: "3170710",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/mobile-computing-and-wireless-communication/mcwc-winter-2024.pdf",
        solutionAvailable: false,
      },
    ],
  },
  "mobile-application-development": {
    title: "Mobile Application Development",
    code: "3170726",
    semester: 7,
    description:
      "Designing, building, and testing modern mobile apps for current platforms.",
    papers: [
      {
        title: "Mobile Application Development Summer 2026",
        code: "3170726",
        year: "2026",
        type: "Summer",
        pdf: "/pdfs/pyq/mobile-application-development/mad-summer-2026.pdf",
        solutionAvailable: false,
      },
      {
        title: "Mobile Application Development Summer 2025",
        code: "3170726",
        year: "2025",
        type: "Summer",
        pdf: "/pdfs/pyq/mobile-application-development/mad-summer-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Mobile Application Development Winter 2025",
        code: "3170726",
        year: "2025",
        type: "Winter",
        pdf: "/pdfs/pyq/mobile-application-development/mad-winter-2025.pdf",
        solutionAvailable: false,
      },
      {
        title: "Mobile Application Development Summer 2024",
        code: "3170726",
        year: "2024",
        type: "Summer",
        pdf: "/pdfs/pyq/mobile-application-development/mad-summer-2024.pdf",
        solutionAvailable: false,
      },
      {
        title: "Mobile Application Development Winter 2024",
        code: "3170726",
        year: "2024",
        type: "Winter",
        pdf: "/pdfs/pyq/mobile-application-development/mad-winter-2024.pdf",
        solutionAvailable: false,
      },
    ],
  },
};

